### ISSUE TITLE
ACM translator gets wrong place for conference proceedings

### ISSUE THREAD

**Issue by themiurgo** [zotero/translators#1020]
I understand that the `place` entry should be populated with the location where the conference occurred. For many conferences, the ACM Digital Library does not list this information.

Example of a paper for which the information is included:
http://dl.acm.org/citation.cfm?id=1653771&picked=prox

Example of a paper for which the information is missing:
http://dl.acm.org/citation.cfm?doid=1281192.1281230

At the moment using the translator on the first example gets "New York" rather than "Seattle". Even the translator incorrectly tests for "New York" (e.g., https://github.com/zotero/translators/blob/master/ACM%20Digital%20Library.js#L180)

As you can see, the two example documents share the "New York" place, as all the conference proceedings that are published by ACM. Assuming that the `place` entry of a conference proceeding document should contain the conference location, rather than the publisher city, I think the translator should always pick that and if the information is missing it should not populate that field.

**Comment by zuphilip** [comment]
Sorry, for the late answer. In Zotero `place` is mostly for the place of the publisher, similar to the BibTeX field `address`. That part is as expected. However, in CSL there is already the field `event-place` which we could fill through `extra` in Zotero with the BibTeX field `location` for ACM. I will make a PR for that.
