### ISSUE TITLE
ACM Digital Library with Safari Extension

### ISSUE THREAD

**Issue by jsinglet** [zotero/translators#1023]
I use Zotero on a Mac with the Safari extension. I use the ACM digital library extensively, however, the connector never works with the ACM Digital Library on Safari. Other sites work, and the ACM DL works fine on Chrome. 

Zotero Version: 4.0.28.8
Connector Version: 4.0.28-1

Safari 9.0.3
OSX 10.11.3

I did a little debugging and it appears to fail here: 

function scrape(doc) {
var abs = ZU.xpath(doc, '//div/div[@style="display:inline"]')[0];

// Get genric URL, preferring the conference version.
var url = ZU.xpath(doc, '//meta[@name="citation_conference"]\
/following-sibling::meta[@name="citation_abstract_html_url"]/@content')[0]
|| ZU.xpath(doc, '//meta[@name="citation_abstract_html_url"]/@content')[0];
url = url.textContent;

...
}

The XPath expressions always return undefined. I put a breakpoint right before the xpath expression and the following always returns undefined: 

document.getElementsByTagName('meta')

I'm thinking the problem is with the HTML on the ACM's homepage -- the question is what would be an acceptable fix? 

I think to improve user experience, the translators should work by sending the HTML to a backend server and do the processing there. That way we would get consistent translator performance across all browsers. 

Thoughts? 

Best,
JLS

**Comment by jsinglet** [comment]
Update: 

I believe the problem has to do with addthis -- setting some earlier breakpoints I can clearly see the meta tags in a XPATH query --- however, AFTER I see this error, is when the translator runs into trouble.

The exact error is:

Blocked a frame with origin "http://s7.addthis.com" from accessing a frame with origin "http://dl.acm.org". Protocols, domains, and ports must match.
(anonymous function)inject.js:221

**Comment by zuphilip** [comment]
I tried to use some other nodes which hopefully are not injected by ACM during loading the website:

https://github.com/zuphilip/translators/blob/acm/ACM%20Digital%20Library.js

@jsinglet Can you test my current version of the translator with Safari on your Mac?

**Comment by jsinglet** [comment]
Sure, what's the best way to do that?

**Comment by zuphilip** [comment]
Substitute your version with the [new version](https://raw.githubusercontent.com/zuphilip/translators/acm/ACM%20Digital%20Library.js). Your version will be in your data directory from Zotero, which can be found from Zotero by clicking the "Show Data Directory" button:
![](https://www.zotero.org/support/_media/preferences/preferences-advanced-files-z4.0.png?w=400)

**Comment by jsinglet** [comment]
So the Safari translator pulls from my Zotero installation? I assumed it would be packaged in the extension?

**Comment by jsinglet** [comment]
No luck -- Here is the result: 

![screen shot 2016-09-04 at 3 06 24 pm](https://cloud.githubusercontent.com/assets/1062841/18233297/4466871c-72b1-11e6-982d-1a4ce27ed047.png)

**Comment by zuphilip** [comment]
> So the Safari translator pulls from my Zotero installation? I assumed it would be packaged in the extension?

Yes, it is packaged as a Safari extension and works in combination with Zotero Standalone. But some parts (translators, citation styles) are updated frequently. The translators for extracting websites are running in some sandboxing environment.

I cannot see anything suspicious in the picture above. Maybe you can also check error report from within Zotero?

**Comment by jsinglet** [comment]
Nothing useful there; I think the only way to get a useful message is to step through it. When I get a moment I'll see if I can get more useful information. I think the problem is with the share this elements on the page.

**Comment by zuphilip** [comment]
Okay, any debug info might be useful. Another thing which is sometimes a problem are iframes (might also come as advertisements).

**Comment by jsinglet** [comment]
The share this thing IS an iframe. You can probably reproduce it if you just change the user agent string on your browser to match safari. https://addons.mozilla.org/en-US/firefox/addon/user-agent-switcher/

I think chrome has it built in.

**Comment by adam3smith** [comment]
I understand from reports on the forum that this is no longer an issue? @jsinglet can you confirm and if so, close?

**Comment by jsinglet** [comment]
Indeed! It appears to be working now.
