### ISSUE TITLE
locally add translators for testing and personal use

### ISSUE THREAD

**Issue by rubenarslan** [zotero/translators#1024]
I want to adapt translators to a URL proxy that I use (which changes the URL in a predictable way by postfixing it). I'm not sure, others need that functionality and anyway I'd like to test it locally first. How can I do that?

**Comment by adam3smith** [comment]
I doubt the reply is still useful, but you can just specify a target URL in any translator in Scaffold (i.e. Developer Tools --> Translator editor).
