### ISSUE TITLE
No valid TEI output if there is no creator 

### ISSUE THREAD

**Issue by FranziskaHorn** [zotero/translators#1031]
Normally the value for the attribute xml:id is the creator's last name and the year of publication.
If there is no creator, the value for xml:id now contains the URI of the item 
(commit "[TEI.js: switch to item.uri #1029](https://github.com/zotero/translators/pull/1029/commits/131e370cb52c8f17c62f05d6d1c9227f01be9281)" )

`xmlid += 'zoteroItem_' + item.uri;`

```
<biblStruct type="book" xml:id="zoteroItem_http://zotero.org/groups/<groupID>/items/<itemID>" corresp="http://zotero.org/groups/<groupID>/items/<itemID>">
[...] </biblStruct>
```

The URI contains a colon. In consequence, there is validation error in the tei output
because the colon is a non xml NCName character. It's seldom that there is no creator
but is it possible to consider that?

**Comment by adam3smith** [comment]
sure. Any preferences? We'd still want to use the uri information, but I'm happy to consider a shortened form or so.

**Comment by dstillman** [comment]
You could just do `users/<groupID>/items/<itemID>` and `groups/<groupID>/items/<itemID>`.

**Comment by adam3smith** [comment]
yeah, I was thinking along those lines. The slashes won't cause issues anywhere, will they?

**Comment by FranziskaHorn** [comment]
Unfortunately, the slash is also not allowed.

**Comment by dstillman** [comment]
@adam3smith I'm not familiar with TEI, but is there actually a need here for a persistent identifier here? (The itemID was only persistent when dealing with the same local database, anyway.)

**Comment by adam3smith** [comment]
I'm not familiar with TEI, either, that's why I'm asking for input of what makes sense. If all else fails, I can just use the item key (i.e. the last part of the URI), which is at least stable across synced databases.

**Comment by FranziskaHorn** [comment]
I don't know how others use xml:id in TEI output and if there is a need for xml:id, the URI is exported for each entry in attribute corresp. I think it would be a workaround if only the item key is used for xml:id if there is no creator. 

An example would be `xml:id="zoteroItem_itemkey"`. Item keys can start with a digit but [tei-conform](http://teibyexample.org/modules/TBED01v00.htm?target=globalattributes) values for xml:id must start with a letter or the underscore character.

**Comment by adam3smith** [comment]
closed via https://github.com/zotero/translators/pull/1057
