### ISSUE TITLE
Handling of all uppercase words with HTML markup by BibLaTeX translator

### ISSUE THREAD

**Issue by brisk022** [zotero/translators#1033]
In biology, gene names have to be italicised. However, they are often all upper case. The translator converts `<i>FLC</i>` in the title to `{\textless}i{\textgreater}{FLC}{\textless}/i{\textgreater}` rather than `\textit{FLC}`

**Comment by brisk022** [comment]
Sorry, I was slightly wrong. The main problem was not the upper case but rather multiple inclusions of the italics tag. The regular expression for translating the italic tags does not have a global modifier. So, `<i>a</i> and <i>b</i>` is translated into `\textit{a} and {\textless}i{\textgreater}b{\textless}/i{\textgreater}` rather than `\testit{a} and \textit{b}`.

One letter fix.
`characters = characters.replace(/\{\\textless\}i\{\\textgreater\}(((?!\{\\textless\}\/i{\\textgreater\}).)+)\{\\textless\}\/i{\\textgreater\}/g, "\\textit{$1}").replace(/\{\\textless\}b\{\\textgreater\}(((?!\{\\textless\}\/b{\\textgreater\}).)+)\{\\textless\}\/b{\\textgreater\}/g, "\\textbf{$1}");`

**Comment by zuphilip** [comment]
Fixed now. Sorry for the delay.
