### ISSUE TITLE
Vimeo Translator not working

### ISSUE THREAD

**Issue by indemnitypop** [zotero/translators#1044]
Chrome on windows 7 primarily, but I've reproduced the error using Firefox as well. Friends have reproduced the error on Chrom on Mac OS.

Any time I try to add a video from vimeo.com to my library I get an error prompting me to check the known translator issues.

Looking at the vimeo translator code, it looks like Vimeo may have changed the structure of their URLs, but I'm not sure.

**Comment by zuphilip** [comment]
I guess this should be closed by https://github.com/zotero/translators/pull/1155.
