### ISSUE TITLE
IEEE Xplore in Chrome "import multiple" doesn't work after sorting search results

### ISSUE THREAD

**Issue by abhijitchat** [zotero/translators#1052]
If I perform a search from the ieeexplore homepage, my chrome zotero connector will recognize the results page and I can select multiple articles to import.  If, however, I perform another search from the results page or manipulate the results (sort by date or citations, for example), zotero connector no longer will let me import multiple.  Instead it offers me the standard "Save to Zotero (webpage)"

**Comment by adam3smith** [comment]
please report to the Zotero forums first. We can create an issue once this is confirmed, but we first want to run through the troubleshooting.
