### ISSUE TITLE
IEEE Xplore in Chrome "import multiple" only works if search initiated on home page

### ISSUE THREAD

**Issue by bjmuld** [zotero/translators#1053]
If I perform a search from the ieeexplore homepage, my chrome zotero connector will recognize the results page and I can select multiple articles to import.  If, however, I perform another search from the results page or manipulate the results (sort by date or citations, for example), zotero connector no longer will let me import multiple.  Instead it offers me the standard "Save to Zotero (webpage)"

**Comment by adam3smith** [comment]
see my answer on the other ticket. Please report on the Zotero forums, we do all troubleshooting/triage there. https://www.zotero.org/support/troubleshooting_translator_issues
