### ISSUE TITLE
AEA Web.js broken

### ISSUE THREAD

**Issue by jlegewie** [zotero/translators#1058]
Just ran into problems with the AEA translator with this website:

https://www.aeaweb.org/articles?id=10.1257/aer.20150572

Without really knowing anything about translators, it looks like the target doesn't match anymore. The new links use ?id=DOI and not php. I am sure there are other changes as well. In fact, I think AEA just changed their website. There also is a forum discussion about it. 

https://forums.zotero.org/discussion/58707/translator-for-american-economic-review-and-other-aea-journals/

**Comment by adam3smith** [comment]
yep, they changed their page (about time, too. The old one looked decidedly 1990s). Thanks for opening a ticket. I'll see when I can get to it.

**Comment by adam3smith** [comment]
(FWIW, running the Embedded Metadata translator from Zotero should get you very good import -- everything but the abstract, likely including the PDF).

**Comment by zuphilip** [comment]
@adam3smith I can try to look into this issue the next days. Do you think we should switch from calling the RIS translator to the EM translator here?

**Comment by adam3smith** [comment]
might be easier and I don't see the downside -- you'll need to scrape the abstract separately either way.
