### ISSUE TITLE
translator: The Chronicle of Higher Education.js title incorrect

### ISSUE THREAD

**Issue by Jmuccigr** [zotero/translators#1070]
The translator for the CHE is grabbing the title for non-blog posts from the H1 header, but at least in some cases, that doesn't agree with the Open Graph metadata that they're supplying.

For example, an article today: http://chronicle.com/article/A-Historians-Day-in-Court/236656

has *A Reckoning* for H1, but *A Historian's Day in Court* in the og:title (as well as in Twitter:title).

This doesn't seem to happen too often (the piece is question is fairly long and not "news" per se), but it would seem a good idea to use the Open Graph data as a rule, no?

**Comment by adam3smith** [comment]
I'm not sure -- it seems weird to use a title that's only used in the metadata, not on the actual page. Wouldn't "A Reckoning" be more accurate here?

**Comment by zuphilip** [comment]
There is `<title>A Historian&#039;s Day in Court - The Chronicle of Higher Education</title>` and the url http://chronicle.com/article/A-Historians-Day-in-Court/236656 also contains this title. My question is: what is this then in the `h1`-tag, i.e. `<h1 class="content-item__title">A Reckoning</h1>`?

**Comment by adam3smith** [comment]
I'm thinking they may have changed the title at some point after the page was created? (In which case going with the h1 title seems right)

**Comment by zuphilip** [comment]
Yes, indeed. Here is the proof: https://www.google.de/search?q=http://chronicle.com/article/A-Historians-Day-in-Court/236656

**Comment by Jmuccigr** [comment]
Sorry to be dense, but which one is earlier then?

The current CHE main page links to the longer title. Both pages have the same data for the title, except in the link, and in the added disqus title "A Historian's day…" in the Reckoning page (ironically?).

**Comment by adam3smith** [comment]
The article was originally named "A Historian's Day" and created with that title in the URL & the metadata tags.
It was then renamed, ~3hs later, to "A Reckoning," which I would thus consider the correct title at the time of access. CHE did not change the metatags accordingly, which is an oversight on their part (and/or missing functionality in their CMS).
