### ISSUE TITLE
Financial Times translator issues

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1075]
- Pulls author as "Review by Demetri Sevastopulo" in [Review — A bleak outlook on an unequal America](http://www.ft.com/intl/cms/s/0/5c416bca-0233-11e6-99cb-83242733f755.html)
- Pulls a paywalled screenshot when using the translator, even if the page isn't paywalled on view. Embedded Metadata's screenshot pulls what's currently on the page.

Should be easy to fix, but tracking here in case someone gets to it before me

**Comment by owcz** [comment]
@adam3smith looks like this translator is totally down & not detecting on the article previously mentioned—likely needs a rewrite. Wanted to give you the heads up, but if you prefer, I can take a stab

**Comment by jrennstich** [comment]
Same here. It starts to detect, but then never finishes.
