### ISSUE TITLE
HighBeam Research (translator request)

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1088]
> There doesn't seem to be a Zotero translator for HighBeam Research (https://www.highbeam.com). If it's not much trouble, would you file a request for that for me? It's used by a number of Wikipedia editors. Whatamidoing (WMF) (talk) 17:36, 27 June 2016 (UTC)

[via WP](https://en.wikipedia.org/wiki/User_talk:Czar#Would_you_do_me_a_favor.3F)

I have access to this database so I might be able to do it, time permitting

**Comment by zuphilip** [comment]
The Embedded Metadata translator works for this website in Zotero. Maybe, it is better to work on the EM translator such that it also can be used in Citoid resp. the Zotero translation server.

**Comment by adam3smith** [comment]
EM data seems weak on that site though?

**Comment by zuphilip** [comment]
I don't know exactly, because I only looked at [one example](https://www.highbeam.com/doc/1G1-173466649.html) which was not that poor...

**Comment by mvolz** [comment]
translation-server doesn't seem to run EM if the target doesn't match, see thread here: https://groups.google.com/forum/#!topic/zotero-dev/fJdp0NK_2ec

**Comment by owcz** [comment]
1. I think EM will be sufficient here so
2. The issue is getting EM to work with [translation-server](https://github.com/zotero/translation-server)/Citoid. I know dstillman [refreshed](https://github.com/zotero/translators/pull/1066#issuecomment-221977365) t-server's code (to update its Zotero version from 2013 to 2016), updated from 2013) but I'm not sure whether Citoid is using those updates yet.
3. Any way to convert this from a "translators" ticket to a "translation-server" issue? Or would I have to close this one and reopen, if need be?

**Comment by adam3smith** [comment]
@zuphilip -- didn't I understand you on that thread that EM works with the updated translation-server? If that's the case, this is a citoid issue and @mvolz would have to take it.

**Comment by mvolz** [comment]
It is not the case. Even with the updated version of translation-server, any url which does not match a pattern in the translators returns a 501 not implemented status code with the message "No translators available."

Example: 

```
curl -d '{"url":"https://www.highbeam.com/doc/1P2-23197647.html","sessionid":"abc123"}' --header "Content-Type: application/json" 127.0.0.1:1969/web  

No translators available

```

**Comment by owcz** [comment]
See new ticket

**Comment by mvolz** [comment]
I know this is closed, but there are still issues; even with translation-server issue fixed, https://www.highbeam.com/doc/1P2-23197647.html is miscategorised as a journalArticle; I think actually a translator for highbeam could really improve quality.

**Comment by adam3smith** [comment]
I agree -- there's a bunch of things I can see us improving here. This should be done as a non-FW translator to allow for easier post-processing. Start with EM, then fix what needs fixing.

**Comment by zuphilip** [comment]
One could for example add a special translator for highbeam which is calling the Embedded Metadata translator and just change some small adjustments, cf. https://github.com/zuphilip/translators/wiki/Calling-metadata-translator .
