### ISSUE TITLE
Add translator for ArXiv PDFs

### ISSUE THREAD

**Issue by tobiasdiez** [zotero/translators#1093]
If I open a PDF from ArXiv in the browser (e.g. http://arxiv.org/pdf/1402.1516v1.pdf), then Zotero should be able to fetch the metadata present at the corresponding html page (e.g. http://arxiv.org/abs/1402.1516) and import the article (along with the pdf). That is, I don't want to manually visit the html page and click import, but import directly from the open pdf.
Since the PDF link always contains the identifier, this should be relatively easy.

**Comment by bencomp** [comment]
My workflow for arXiv PDFs is (using Firefox and Firefox's PDF.js viewer) to click the *Download* button in PDF.js, select *Save to Zotero* and make sure the box *Retrieve metadata for file* is checked. I believe the correct reference is then always/usually found.

**Comment by adam3smith** [comment]
the feature request is perfectly valid, though. We actually do want to do this for as many translators as possible. (Also, due to changes in Firefox, that option is going away in the download dialog with Zotero 5.0)

**Comment by bencomp** [comment]
Good call, and apologies for the brevity of my comment. I didn't know about the changes, so I will probably have the same feature request :)

**Comment by adam3smith** [comment]
Fixed in https://github.com/zotero/translators/pull/1285
