### ISSUE TITLE
Error with ACS Publications

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1096]
Any news about the problems with ACS, @adam3smith ? I have seen https://forums.zotero.org/discussion/60964/translator-error-with-american-chemistry-society-websites/ and it looks that this is the most frequent error at the moment:

[![firefox_2016-07-27_23-46-08](https://cloud.githubusercontent.com/assets/5199995/17193666/658fc4ec-5454-11e6-85a7-4a7da903ec65.png)](https://repo.zotero.org/errors)

**Comment by adam3smith** [comment]
I just don't have a particularly good idea how to solve this. I'll try after my vacations, but it looks like it'll be a lot of work. ACS didn't react to my tweet.

**Comment by zuphilip** [comment]
I observed the URL calls when performing the steps by hand, and it seems that final call for the RIS file might be much easier to do without any intermediate step. Actually, it might even be that we can just use a GET to `"pubs.acs.org/action/downloadCitation?direct=true&doi="+encodeURIComponent(doi)+"&format=ris&include=cit&submit=Download+Citation"` (or something similar), e.g. http://pubs.acs.org/action/downloadCitation?direct=true&doi=10.1021/acs.est.6b02569&format=ris&include=cit&submit=Download+Citation
