### ISSUE TITLE
Create translator for BBC News (or fix current BBC one)

### ISSUE THREAD

**Issue by josve05a** [zotero/translators#1103]
Example
`				"url": "http://www.bbc.com/news/world-europe-37018562",`
`				"publicationTitle": "BBC News",`
`				"language": "English",`
`				"date": "9 Aug 2016",`
`				"abstractNote": "The leaders of Russia and Turkey have patched up a damaging quarrel, pledging to restore close economic relations.",`
`				"title": "Putin mends broken relations with Turkey's Erdogan",`
`				"libraryCatalog": "BBC News",`
`				"accessDate": "CURRENT_TIMESTAMP",`

**Comment by josve05a** [comment]
Date:
`//div[@data-datetime]`
`//*[@id="page"]/div[2]/div[2]/div/div[1]/div[1]/div[1]/ul/li[1]/div`
AbstractNote:
`//p[@class="story-body__introduction"]`
`//*[@id="page"]/div[2]/div[2]/div/div[1]/div[1]/div[3]/p[1]`
Title:
`//h1[@class="story-body__h1"]`
`//*[@id="page"]/div[2]/div[2]/div/div[1]/div[1]/h1`

**Comment by zuphilip** [comment]
There is a translator for BBC: https://github.com/zotero/translators/blob/master/BBC.js

But it looks that the website and all articles now changed to `.com` from `.co.uk`. Is that correct??

**Comment by josve05a** [comment]
> But it looks that the website and all articles now changed to .com from .co.uk. Is that correct??
That seems to be correct. Not sure how much else has changed...

**Comment by josve05a** [comment]
BTW, I'm from the Wikimeida comunity, and we use these translators in out Citoid tool. Is there an easy way fr me as a novice and newbie to learn how to create these translators? I remember reaing your 'How to' a year ago or so, but i was then at a loss not really understanding how to do it...

**Comment by zuphilip** [comment]
> Is there an easy way fr me as a novice and newbie to learn how to create these translators?

For translator coding you should use Scaffold: https://github.com/zotero/scaffold/releases (Firefox addon)

Moreover, check out @adam3smith material: https://github.com/adam3smith/webinar-translators and you may also look at my collection of recipies for translator coding: https://github.com/zuphilip/translators/wiki/Common-code-blocks-for-translators

**Comment by josve05a** [comment]
Thanks! Waatching github.com/zuphilip/translators/wiki/Common-code-blocks-for-translators to learn te basics first :)

**Comment by josve05a** [comment]
I don't know if i*m doing something wrong, but when starting Scaffold, nothing appens. No generated ID, nothing in the ACtive Ta URL, an it doesn't react when I press any of the top button...

**Comment by zuphilip** [comment]
Okay, I look now a the BBC translator. I think that I will have something soon...
