### ISSUE TITLE
A Contracorriente

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1109]
Example page: http://acontracorriente.chass.ncsu.edu/index.php/acontracorriente/article/view/174

There seems to be a special translator for that site: https://github.com/zotero/translators/blob/master/A%20Contra%20Corriente.js

But currently the EM translator will be applied and there is also a test case in EM. However, currently the type returned there is `webpage` and not `journalArticle`.

Actually, they use the Open Journal System and we should use that translator for that site. Maybe the [`detectWeb`](https://github.com/zotero/translators/blob/master/Open%20Journal%20Systems.js#L15-L19) should be improved there.

What do you think @adam3smith ?

**Comment by adam3smith** [comment]
Improving Open Journal Systems if possible would be nice. This:
<meta name="generator" content="Open Journal Systems 2.4.8.0" />
looks like it might work?
