### ISSUE TITLE
Check & fix char escaping on AEA

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1114]
E.g. https://www.aeaweb.org/articles?id=10.1257/jep.30.3.235
import's the apostrophe with html escaping.

**Comment by zuphilip** [comment]
(AEA is also working on translation server, besides the [known bug with newer XUL-Runner, SDK](https://github.com/zotero/translation-server/issues/26) when calling EM translator. Thus you can add the `v` flag.)

**Comment by zuphilip** [comment]
This can be closed now.
