### ISSUE TITLE
Child Notes in TEI Output

### ISSUE THREAD

**Issue by FranziskaHorn** [zotero/translators#1130]
Hi,

child notes, which belong to a specific item, are exported via API request although the 
TEI translator has the statement `"exportNotes": false,`

Here is an example for the export of a note:
```
<biblStruct type="note" xml:id="zoteroItem_ID" corresp="item.uri">
    <monogr>
		<title/>
		<imprint><!--  no publisher, publication date or place given  --></imprint>
    </monogr>
</biblStruct>

```
The content of the child note is not exported. So the following statement works correctly
`if (item.notes && Zotero.getOption("exportNotes"))`, but an element `biblStruct` is created for a child note. 

Is it possible to adjust the TEI translator so that there is no export, no `biblStruct` for child notes? 

That would be very helpful because the total number of items stated in the HTTP header (`Total-Results`) does not count these notes. It counts items such as books and standalone notes but
not child notes. In consequence the number of exported elements `biblStruct`
is higher than `Total-Results`, the "real number of items" is not stated in the header.

For example, this is a problem for the automatized, daily export of about 2200 entries in our Zotero group. That is how we discovered the problem. The problem does not occur if I export items in Zotero Standalone.

I tried something like` item.itemType != "note" && !item.parentItem` at the beginning of function `generateItem(item, teiDoc)` but it didn't worked, I received an error message when I tried to export in Zotero Standalone.

**Comment by zuphilip** [comment]
I tried to reconstruct the problem with the firefox plugin. I see a difference if I mark the item and its child note together and then click on export to tei:

![tei-export-note](https://cloud.githubusercontent.com/assets/5199995/18368036/23b9f66e-761e-11e6-9b3a-c733e0cd85bc.png)

I guess that this is also happening if you are calling TEI over the API. Is it possible to restrict to the top-level elements when calling the API? I have seen something like `top` there and maybe something like https://api.zotero.org/users/475425/collections/9KH9TNSJ/items/top?format=tei will work for you?

**Comment by FranziskaHorn** [comment]
Thank you for the hint, I used `top` to get the HTTP header and therefore to 
get `Total-Results` but I didn't used it in the request to actually export the items. 
So the export wasn't restricted to top-level elements.

If the requests for the items contain `top`, child notes aren't
exported and the number of exported items is equal to `Total-Results`.
Everything works fine now, thanks again!
