### ISSUE TITLE
Problems with Summon 2 Translator

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1148]
@sircmyst Your company updated the Summon 2.0 interface in August and now the translator is not anymore work properly, see https://forums.zotero.org/discussion/62418/saving-records-from-summon-searches . It looks for me that maybe it is enough to change the lines around `Zotero.monitorDOMChanges` to make sure that the translator is invoked after all your content is dynamically loaded. However, I don't know what exactly one has to change there. Can you look at this issue and maybe fix it?

**Comment by zuphilip** [comment]
Another (similar?) report is available here: https://forums.zotero.org/discussion/62461/chrome-translator-issues-in-proquest

**Comment by sircmyst** [comment]
Hi there,

Thanks for letting me know about the issue. I'll pass word along and we'll try to take a look at this, though it may be a few days before we can.

**Comment by hannahsaur** [comment]
Any update on an ETA for a fix for the translator issue between Zotero and Summon? This issue makes Zotero/Chrome pretty unusable at our institution, so hoping that some fix on Proquest or Zotero's end can resolve the issue. If it's something my institution's IT staff can resolve, let me know. Thanks

**Comment by adam3smith** [comment]
Summons 2 was recently rewritten and now works flawlessly.
