### ISSUE TITLE
Status Zotero Translator for Gene Ontology

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1151]
Currently, the only [test for Gene Ontology](https://github.com/zotero/translators/blob/master/Gene%20Ontology.js#L139) redirects to http://geneontology.org/page/go-citation-policy and fails there to detect anything there. The example citation on that site are not providing any PubMed id and therefore I don't see how to fix this. However, I really don't know what else we have in this database...

Please note that the mention Zotero on that website:

> Both the Gene Ontology website and AmiGO are compatible with Zotero, the Firefox extension for collecting, managing, citing, and sharing research sources. Please contact the GO helpdesk if you would like to request support for an alternative reference collection system. 

@adam3smith Any ideas?

**Comment by AbeJellinek** [comment]
I think I got this fixed a while back. Let me know if there are Gene Ontology use cases that the translator still doesn't cover.
