### ISSUE TITLE
Is Google Blogs still working?

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1152]
The current example https://www.google.com/search?tbm=blg&hl=en&source=hp&biw=1024&bih=656&q=argentina&btnG=Search&gbv=2 does not work anymore. Is the [translator for Google Blogs](https://github.com/zotero/translators/blob/master/Google%20Blogs.js) still working somewhere?

CC @avram

**Comment by adam3smith** [comment]
not listed here: https://www.google.com/intl/en/about/products/ nor as one of the search options, so I'd guess it's gone

**Comment by zuphilip** [comment]
[Blogger](https://en.wikipedia.org/wiki/Blogger_(service)) is part of Google... Okay, then I suggest to delete this translator.

**Comment by adam3smith** [comment]
Yes, confirmed it's gone via https://en.wikipedia.org/wiki/Google_Blog_Search
> For some time it was possible to force Google to access and search the Blogsearch database by manually formatting the URL in your browser's address bar.[3] But in March 2016, Google also took away this access.

go ahead and delete

**Comment by zuphilip** [comment]
Okay, but I will wait until PR with https://github.com/zotero/translators/pull/1144/commits/4a605a748ae507d83f88f03917468f1305abc71d is merged. Otherwise this migtht create a merge conflict or worse...
