### ISSUE TITLE
[Embedded Metadata.js] Use Identifier.URL or canonical URL when available

### ISSUE THREAD

**Issue by niklasholm** [zotero/translators#1160]
I was saving [this page](http://www.diva-portal.org/smash/record.jsf?pid=diva2:766397) using the Embedded Metadata translator, but I noticed that the URL was set to the URL of the current page as shown in the address bar, rather than the canonical URL. I'm no javascript expert, but it seems that when all else fails the URL of the new item is set to doc.location.href, which I assume is the URL of the current page as I saw in my item. However, when looking at the HTML meta tags i notice there is both a canonical link tag:

`<link rel="canonical" href="http://www.diva-portal.org/smash/record.jsf?pid=diva2:766397" />`

and a meta tag

`<meta name="DC.Identifier.url" content="http://urn.kb.se/resolve?urn=urn:nbn:se:liu:diva-112443">`

which would both be better options. I argue that the translator should look for these tags and use one of those URLs instead before resorting to the document href. In this case the second is preferable since it contains the permanent URL (equivalent of an DOI URL).

**Comment by adam3smith** [comment]
Unless someone sees issues with this, that sounds fine to me. Which of the two should be preferred where both exists?

**Comment by zuphilip** [comment]
I don't think that `DC.Identifier.url` exists in the Dublin Core Specs.

**Comment by niklasholm** [comment]
I do not have any affiliation with diva-portal.org so I cannot change anything but I suppose I can contact the webmaster and make them aware of the issue.  However, I cannot see anything in the code that looks for `DC.Identifier` either, so I don't thing that would work anyway.

Either way, the canonical URL should definitely be used if available and should probably be preferred. The problem with `DC.Identifier` is that it isn't necessarily an URL, it can be any unique identifier, as for example in this case a URN:NBN which is used by multiple European national libraries, see [this RFC][1], which could of course be converted to an URL using a lookup service, however there's no standard way to do this. Quote from a DOI factsheet:

> URN architecture assumes a DNS-based Resolution Discovery Service (RDS) to find the service appropriate to the given URN scheme. However no such widely deployed RDS schemes currently exist: browsers cannot action URN strings without some additional programming in the form of a "plug-in". These carry no guarantee of ready interoperability with other deployments, which may require a different plug-in for each implementation and may use conflicting data approaches. Therefore most existing URN implementations embed the URN as a http URI which contains the URL of the relevant resolution service (e.g. for the URN form of the ISBN shown above, resolved via the Finnish national URN service http://urn.fi, the actionable form of the URN is http://urn.fi/URN:ISBN:978-952-10-6154-7). There is no global service aware of national and/or regional URN resolution services, but there are some proposals to provide one (e.g. http://www.persid.org).

> --- [DOI® System and Internet Identifier Specifications][2]

However, the German National Library runs a [service][5] that should be able to resolve many, if not all, URN:NBN identifiers 

In light of the above, I suggest the following approach:

1. If available, use the canonical link as specified by [RFC 6596][3] ([Wikipedia][4])
2. else check if `ID.Identifer.url` exist, if so use it
4. else check if `ID.Identifier` exist and if it's an URL, use it; if it's an `urn:nbn` identifier, try to resolve it using [service][5]


[1]: https://tools.ietf.org/html/rfc3188
[2]: http://www.doi.org/factsheets/DOIIdentifierSpecs.html
[3]: https://tools.ietf.org/html/rfc6596
[4]: https://en.wikipedia.org/wiki/Canonical_link_element
[5]: https://nbn-resolving.org/

**Comment by zuphilip** [comment]
* EM translator might call RDF translator which might handle the standard cases of DC.
 * I don't know if `ID.Identifer.url` is a typo but also `DC.Identifer.url` is not in the specification of Dublin Core and therefore violates the w3 standards. BTW there seems to be [other problems with this site](https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.diva-portal.org%2Fsmash%2Frecord.jsf%3Fpid%3Ddiva2%253A766397%26dswid%3D-5497).
 * If the `DC.identifier` is an url then it is prefixed with `http` or `https`, if it is a urn then it is prefixed with `urn`, if it is a isbn then it is prefixed by `isbn` etc.
 * I don't think we have anywhere handled so far urn...

Besides that I am fine with the canonical link to take into the url field.

**Comment by niklasholm** [comment]
Yeah there seems to be a lot of different schemes for persistent identification, various URN namespaces, DOI, ISSN, ISBN etc. Currently Zotero only handles DOIs and ISBNs AFAIK, perhaps more should be be supported since some large resources doesn't use either of them (like DIVA portal in this example, also multiple other national libraries in Europe). But that's not the job of this translator, such functionality should probably be encapsulated in it's own module. Something for the future?
