### ISSUE TITLE
Translator errors: Reflect is not defined

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1179]
I looked at the [recent translator errors](https://repo.zotero.org/errors) and found the error message
```
ReferenceError: Reflect is not defined
```
for several translators, i.e. at the moment
* Highwire: 17
* Cairn.info: 15
* SpringerLink: 10
* LeMonde: 4
* Nature Publishing Group: 8
* Revues: 6

@dstillman Any idea what the error message means? I guess that this is more related to the sandboxing the translators, then the individual translator code. It seems that all these translators are calling EM.

**Comment by dstillman** [comment]
They're all from Firefox <=40, and the sandboxing code borrowed from Firefox for compatibility with newer Firefox versions doesn't work on older versions. Firefox 38esr is well out of its Mozilla support window, so I don't think we need to worry about this.

**Comment by dstillman** [comment]
(They might not have an effect, but I'll update `minVersion` in our install and update manifests.)
