### ISSUE TITLE
Frontiers import gives misinformation

### ISSUE THREAD

**Issue by adunning** [zotero/translators#1186]
If I try to import an article from Frontiers, e.g. <https://doi.org/10.3389/fdigh.2016.00003>, I end up with complete nonsense in Zotero (e.g. using the research collection as the journal title, placing the volume number in the pages, not getting the full date). Taking the data from CrossRef is much more accurate, though it doesn't include the abstract.

**Comment by adam3smith** [comment]
thanks. closed in https://github.com/zotero/translators/commit/838477428f21ac49d09229fe3548fc5fc96b0ff6

**Comment by adunning** [comment]
Thanks for taking care of it!\
