### ISSUE TITLE
Springer Link translator no longer captures date for Conference Papers in New Layout

### ISSUE THREAD

**Issue by niklasholm** [zotero/translators#1187]
Example paper: http://link.springer.com/chapter/10.1007/978-3-642-19571-6_16

Capturing this paper with the translator will result in no date set. Worked a couple of months ago, probably have to to with their new layout.

**Comment by adam3smith** [comment]
Also reported here https://forums.zotero.org/discussion/comment/264732/ 
It'd be great if more people reported this to Springer (the data is missing in the meta header, specifically). We can work around this, but it's tedious, less stable, and requires more network traffic.

**Comment by eudactus** [comment]
I'm fixing this now on SpringerLink

**Comment by adam3smith** [comment]
@eudactus very much appreciated. Let us know when we can test.

**Comment by eudactus** [comment]
The citation_publication_date has now returned for conference papers. I'm looking at the other missing meta tags now.

**Comment by adam3smith** [comment]
@eudactus thanks! That works great. One other thing I'm spotting is the book title. E.g. for http://link.springer.com/chapter/10.1007/978-3-642-19571-6_16 you have  'BookTitle':'Theory of Cryptography', in the data layer and there is no corresponding meta tag. This used to be in 
`<meta name="citation_inbook_title"` -- getting that (or a similar tag) back would be great.

**Comment by zuphilip** [comment]
It is great to see that date is back! Thank you for that @eudactus !

BookTitle is still missing as @adam3smith mentioned and also book series, i.e. LNCS here, with number is missing. Currently, we are taking this information from the "About this Chapter" section at the bottom (see [here](https://github.com/zotero/translators/blob/master/Springer%20Link.js#L142-L146)), but a more stable solution in any suitable metadata field would be appreciated.

Also all conference fields are missing, it looks that complete lower part was missing, [e.g.](http://link.springer.com/chapter/10.1007/978-3-540-88682-2_1)
```html
  <meta name="citation_inbook_title" content="Computer Vision – ECCV 2008"/>
  <meta name="citation_publication_date" content="2008/10/12"/>
  <meta name="citation_conference_series_id" content="springer/eccv"/>
  <meta name="citation_conference_title" content="European Conference on Computer Vision"/>
  <meta name="citation_conference_sequence_num" content="10"/>
  <meta name="citation_conference_abbrev" content="ECCV"/>
```
Currently, we don't use the `citation_conference_abbrev` and the `citation_conference_sequence_num` but we could for example use that to distinguish `conferencePaper` from other `chapter`s and then fill in the conference name.

**Comment by eudactus** [comment]
citation_inbook_title and citation_conference_series_id have returned. Getting there slowly...

**Comment by eudactus** [comment]
citation_conference_title, citation_conference_sequence_num and citation_conference_abbrev have now returned. I think that's everything now for conference papers.

**Comment by zuphilip** [comment]
That looks pretty good! @eudactus : What do you think about the book series, e.g. "Lecture Notes of Computer Science"? You could use `citation_series_title` together with `citation_volume`.

**Comment by adam3smith** [comment]
While we'll still take improvements along the lines of what zuphilip describes, this has actually now overall improved import of conference papers from Springers, so closing this issues. Thanks again to @eudactus for being in touch and fixing this.
