### ISSUE TITLE
Add ISSN's to  Newsnet/Tamedia

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1216]
Should just be a simple host to ISSN matching table

**Comment by zuphilip** [comment]
I couldn't find any ISSNs for these newspapers. I looked for example here http://dispatch.opac.d-nb.de/DB=1.1/SET=1/TTL=72/CLK?IKT=12&TRM=01526324X

**Comment by adam3smith** [comment]
That one at least does have an ISSN: https://en.wikipedia.org/wiki/Tages-Anzeiger (cross-checked with other sources)

**Comment by zuphilip** [comment]
Hm... your are right. They are not in the German Wikipedia and not in the German sources I looked at. But now I found all these ISSN which I will add:
 * Tagesanzeiger -> 1422-9994 https://en.wikipedia.org/wiki/Tages-Anzeiger
 * Der Bund -> 0774-6156 http://primo.lib.umn.edu/TWINCITIES:default_scope:UMN_ALMA51537576010001701
 * Basler Zeitung -> 1420-3006 https://baselbern.swissbib.ch/Record/271430184/Description
 * Berner Zeitung -> 1424-1021 http://pubget.com/journal/1424-1021/berner-zeitung-german-language
 * Le Matin -> 1018-3736 http://pubget.com/journal/1018-3736/le-matin-french-language
 * 24 Heures -> 1424-4039 http://pubget.com/journal/1424-4039/24-heures-fr

**Comment by zuphilip** [comment]
BTW the official ISSN-L table might be useful for cases like this: http://www.issn.org/services/online-services/access-to-issn-l-table/ . @adam3smith Do you have tried to receive a copy at any time?

**Comment by adam3smith** [comment]
No, I haven't, but without the title information, I'm not sure how that'd help here?
Thank again for adding the ISSNs to the translator.

**Comment by zuphilip** [comment]
Ah, I haven't read the info that carefully. But you are right, the extract of the table only shows different types of ISSNs and not hint of the name behind that number. I guess, that then this list wouldn't be helpful.
