### ISSUE TITLE
Is there still a journal published under the Palgrave website?

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1217]
From #1205 resp. https://github.com/zotero/translators/pull/1205/commits/5451810d4dcd90ade4df09ce71f6efb0cb352bd6

>> @zuphilip: Is there still a journal published under the Palgrave website? Otherwise we may simplify the target regexp.

> @adam3smith: I don't know the answer for Palgrave. We'll have to look for that.

**Comment by owcz** [comment]
Looks like Palgrave (full name Palgrave Macmillan) has moved all its journals to Springer

> From June 1, 2016, Palgrave Macmillan journals’ content hosted on palgrave-journals.com will
be moved and made accessible on SpringerLink. This move will reunite Palgrave Macmillan
journals and eBooks on to the same platform with all Springer journals. The benefits of a single
platform will be an improved user experience and more consolidated library administration
functions.

http://resource-cms.springer.com/springer-cms/rest/v1/content/10214316/data/v1/1062016_Palgrave_Journals_new_platform_overview

**Comment by zuphilip** [comment]
Okay, also all the links here https://www.palgrave.com/gp/journal-authors/contact-us are pointing to springer.
