### ISSUE TITLE
Translator "The Open Library.js" returns incorrect author information

### ISSUE THREAD

**Issue by sonali0901** [zotero/translators#1244]
For the URL https://openlibrary.org/works/OL4957765W/Days_of_our_lives
 the following query,

```
curl -d '{"url":"https://openlibrary.org/works/OL4957765W/Days_of_our_lives","sessionid":"abc123"}' --header "Content-Type: application/json" 127.0.0.1:1969/web 
```
returns information as  follows-

```
[{"itemType":"book","creators":[{"firstName":"Paul Avrich Collection (Library 
of","lastName":"Congress)","creatorType":"author"},
{"firstName":"Rose","lastName":"Pesotta","creatorType":"author"}],"notes":
[{"itemType":"note","note":"\"First printing.\""}],"tags":[{"tag":"Soviet Union -- Social 
conditions.","type":1}],"title":"Days of our 
lives","publisher":"Excelsior","date":"1958","language":"eng","numPages":"262",
"place":"Boston","libraryCatalog":"The Open Library"}]
```
The author information ` {"firstName":"Paul Avrich Collection (Library of","lastName":"Congress)","creatorType":"author"} `is unexpected and erroneous.

**Comment by owcz** [comment]
I haven't looked at the code and I haven't been able to connect to the Library of Congress ("No Connections Available") but the Paul Avrich Collection is a LoC collection. I imagine the translator is pulling from [the linked LCCN](http://lccn.loc.gov/58007925) as I don't see any metadata in this entry's Open Library listing re: the Paul Avrich Collection (which is a great collection, by the way)
