### ISSUE TITLE
IEEE Xplore: Don't trigger open/save dialog when saving from PDF URL

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1249]
So this one's tricky, and has larger implications.

In https://github.com/zotero/zotero-connectors/issues/104, we noticed that, when saved an IEEE Xplore PDF URL from the connector, the translator is used, but it ends up triggering the file open/save dialog in Zotero and hanging the save in Chrome. (Tested in 5.0.)

What's happening is that the translator is saving normally, but it doesn't realize it's on a PDF URL and tries to include the current document — which is a PDF — as the HTML snapshot. And it doesn't try to save a PDF URL, because it doesn't find it on the page, even though the current URL is already the PDF URL.

When the translation architecture passes the attachment info to Zotero, it can't pass a document natively, so it replaces the document with the URL, which is the PDF URL, and adds `text/html`. The hard-coded content type ends up circumventing the normal HEAD request that Zotero makes before saving an attachment to determine if the file can be handled internally (e.g., HTML) or should be saved directly as a file (e.g., PDF), so Zotero erroneously makes an internal request for the PDF, which ends up popping up the save dialog.

One partial fix would be to use the actual content type of the document instead of `text/html` when replacing the document in the attachment info sent to the client, which would help avoid erroneous save dialogs and save the PDF sort of by accident, but then it would still say "IEEE Xplore Abstract Record" when saved.

The real fix would be for the translator to detect that it's on the PDF page, skip the HTML attachment, and include the current URL as the PDF attachment. Any other translator that can optionally trigger on a PDF URL is susceptible to the same problem and should be adjusted as well.

**Comment by adam3smith** [comment]
> The real fix would be for the translator to detect that it's on the PDF page, skip the HTML attachment, and include the current URL as the PDF attachment. Any other translator that can optionally trigger on a PDF URL is susceptible to the same problem and should be adjusted as well.

I haven't looked at IEEE Xplore yet, but that can't be hard. I'll check and fix. We don't have that many other translators detecting on PDFs.

**Comment by adam3smith** [comment]
This works as intended for me now (without relevant code changes). Tested successfully in Chrome. Would someone else check?
