### ISSUE TITLE
EM: add meta[@property="author"]

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1283]
This was mentioned in https://github.com/zotero/translators/pull/977#issuecomment-162964822 and supposed to be added to the Embedded Metadata translator in https://github.com/zotero/translators/issues/932#issuecomment-162966354 but it isn't working in the following example:

`<meta property="author" content="Andrew Webster">`
http://www.theverge.com/2015/7/23/9016313/prune-iphone-ipad-game

**Comment by adam3smith** [comment]
that's because we're looking for `name="author"`, not `property="author"`. I don't know how common the latter is. For the verge, we should in the short-medium run just be able to rely on JSON-LD

```
     <script type="application/ld+json">
  {
  "@context": "http://schema.org",
  "@type": "NewsArticle",
  "mainEntityOfPage": "http://www.theverge.com/2015/7/23/9016313/prune-iphone-ipad-game",
  "headline": "The best new iOS game is about growing trees",
  "description": "Prune is a bonsai tree in your pocket",
    "datePublished": "2015-07-23T08:30:30-04:00",
    "dateModified": "2015-07-23T08:30:30-04:00",
    "image": { "@type": "ImageObject", "url": "https://cdn0.vox-cdn.com/thumbor/jyV4fw9rKEuFEsPgYdar1RyBLJQ=/5x0:1014x673/1310x873/cdn0.vox-cdn.com/uploads/chorus_image/image/46803172/prune.0.0.jpg", "width": 1310, "height": 873 },
  "author": {
  "@type": "Person",
  "name": "Andrew Webster"
  },
  "publisher": {
  "@type": "Organization",
    "logo": { "@type": "ImageObject", "url": "https://cdn0.vox-cdn.com/community_logos/35025/verge-logo-lg.jpg", "width": 300, "height": 266 },
  "name": "The Verge"
  }
  }
```
for which we'll hopefully be adding support in Zotero relatively soon.

**Comment by owcz** [comment]
Vox.com (#977) appears to have the same structure:

`<meta property="author" content="Ezra Klein">`
http://www.vox.com/policy-and-politics/2017/3/17/14961066/donald-trump-gop-health-bill

so it looks like the parameter was changed from `name` to `property` on Vox sites
