### ISSUE TITLE
BnF translator

### ISSUE THREAD

**Issue by symac** [zotero/translators#1302]
Hello,
when using the [bibliothèque nationale de France](https://github.com/zotero/translators/blob/master/Bibliotheque%20nationale%20de%20France.js) translator, there is a small issue. To get the metadata, the script is getting the unimarc view of the record page (constructed [via reformURL](https://github.com/zotero/translators/blob/master/Bibliotheque%20nationale%20de%20France.js#L464))
Starting with a page like http://catalogue.bnf.fr/ark:/12148/cb42623688t the translator is going to get http://catalogue.bnf.fr/ark:/12148/cb42623688t.unimarc to process the unimarc. I believe that by getting this page, some cookie might be updated and the translator believes the user now wants the unimarc view as the default one. So starting from there when the user tries to look at a record, if he doesn't chose to move back to public view, he will be shown the unimarc view.
The easiest option would be I believe to retrieve the http://catalogue.bnf.fr/ark:/12148/cb42623688t.public page after the harvesting is finished to revert the cookie to the correct default view but that is an extra step for something that might be easier to fix. 

Any idea anybody ?

**Comment by zuphilip** [comment]
I don't see any change in the cookies when switching from one view to the other. I guess that the latest used view is saved in the session id on the server side. Thus, the only fix IMO would be to navigate after the metadata extraction to the public version again with an additional call. Is it worth to do that?

**Comment by Lully** [comment]
@zuphilip Yes, the translator should "restore" the public view (URL with ".public" extension) after using the ".unimarc". I thought with @symac that it should be easy to do (I'm of course unable to do that).
And it's rather disturbing for patrons to see the .unimarc record (we heard some critics) : so yes, if it's easy it's worth to do that.

**Comment by zuphilip** [comment]
Okay, let me try to help some colleagues in France. I propose a fix for this in #1358. @Lully, @symac maybe you can test this?

**Comment by symac** [comment]
Thanks @zuphilip that seems to fix the issue according to the tests I have been doing. I will let @Lully confirm that it's ok for him.

**Comment by Lully** [comment]
Thanks @zuphilip, it works well -- but only if you import a record from the detailed view : if you use the translator with a list of results, the next record you will see will be in Unimarc.
Can this be fixed too ?

**Comment by zuphilip** [comment]
@Lully Try again with the new version.

**Comment by Lully** [comment]
@zuphilip that's perfect !

**Comment by adam3smith** [comment]
code is now live for all Zotero users & will propagate through the next 24hs
