### ISSUE TITLE
Language field for NY Times missing

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1303]
The language field for NY Times missing and it should be simple to add that. This would improve the usefulness for Wikidata. Maybe we can also think about other possible translators missing the language field... I can look into this later.

HT @filbertkm #WikiCite.

**Comment by dstillman** [comment]
[Quoting](https://github.com/zotero/translators/commit/427690f75646c0f00a730b74b4f7c18d30b26c23#commitcomment-22257632) @avram:

> So NYT makes a regular practice of publishing non English versions of stories of particular interest to speakers of a given language- I've seen it with Russian, and Spanish and Chinese and I'm sure other languages have appeared as well

E.g.: https://www.nytimes.com/2015/05/10/nyregion/manicurists-in-new-york-area-are-underpaid-and-unprotected.html

There's an `inLanguage` field that it seems like we could probably use.

**Comment by zuphilip** [comment]
Okay, I will do another PR for that and rewrite some of the old code ...
