### ISSUE TITLE
CrossRef: Handle predefined entities from API

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1312]
https://forums.zotero.org/discussion/65879/zotero-5-special-char-not-filtered

E.g.:

```
<title>The Chinese &lt;i&gt;Hukou&lt;/i&gt; System at 50</title>
```

I'm actually surprised we're not getting this automatically.

**Comment by zuphilip** [comment]
> I'm actually surprised we're not getting this automatically.

For the web translator `DOI.js` this seems to automatically replaced but not for the search translator `CrossRef.js`.
