### ISSUE TITLE
Delete ReliefWeb?

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1319]
There is no test case for [ReliefWeb.js](https://github.com/zotero/translators/blob/master/ReliefWeb.js) and the code suggest that we only consider urls from http://reliefweb.int/ with also have '/OpenDocument/' as part of their url. I cannot find any such example at the current website, but in 2008 there seems to be some [potential urls of this form](https://web.archive.org/web/20080313051512/http://www.reliefweb.int/rw/RWB.NSF/db900SID/ASAZ-7C8KH9?OpenDocument). Most of the code is very old.

Can we maybe just delete this translator? The EM translator seems to work quite okay on these websites.

**Comment by adam3smith** [comment]
Yeah, makes sense.
