### ISSUE TITLE
EM produces tags containing single characters

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1323]
In the recent days I have seen that EM translator when called from another translator sometimes produces tags containing single characters. For example https://dialnet.unirioja.es/servlet/libro?codigo=293780 :

```diff
"tags": [ 
- "Libres" 
+ "" 
- "Libro" 
+ " " 
- "buenos y justos como miembros de un mismo cuerpo: lecciones de teoría del derecho y de derecho natural" 
+ ":" 
+ "L" 
+ "a" 
+ "b" 
+ "c" 
+ "d" 
+ "e" 
+ "h" 
+ "i" 
+ "j" 
+ "l" 
+ "m" 
+ "n" 
+ "o" 
+ "p" 
+ "r" 
+ "s" 
+ "t" 
+ "u" 
+ "y" 
+ "í" 
]
```

The problem seems to be some string vs. array type confusion with an automatic transformation of the string into its array of characters.

I will fix this with my next commit.

**Comment by adam3smith** [comment]
Closed in https://github.com/zotero/translators/pull/1324
