### ISSUE TITLE
Gale translator broken

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1330]
[Edit: started as "PowerSearch" unhandled, but not even the GVRL(Gale Virtual Reference Library) works anymore]

http://go.galegroup.com/ps/

Gale PowerSearch search results (multiple and single) both fail gracefully with the Galegroup.js translator. Translation doesn't fail, but the process ends without detection. Not sure if it's a bug or just needs to be updated. (Or whether I should try to handle it myself or wait for the whole translator to be fixed, if needed.)

**Comment by adam3smith** [comment]
yeah, Gale is more broadly broken. It's a tricky one

**Comment by owcz** [comment]
@adam3smith what is the preferred method to pull the RIS from this overlay? Would need to set endnote-select first and then capture the export. Haven't done this part of the scrape before
![image](https://user-images.githubusercontent.com/778011/38778384-e547903c-4086-11e8-8d2b-391742ac5741.png)

**Comment by adam3smith** [comment]
You'll have to "listen" to the actual http calls made when clicking the button (under the Network tab) and then emulate these. I'd guess these are `POST` calls here, so you need to figure out both the URL the call gets made to and -- and that's the tricky part -- the `POST` message. 

To make this more tricky (and this is why this has been lingering for so long), Gale uses different page formats for different databases, so this doesn't work the same across their resources.

**Comment by owcz** [comment]
I've hit a wall. @adam3smith Any chance you could get this back up for the basic GVRL database (existing translator doesn't even work for that one, likely with interface changes screenshot above)? I would be happy to look into the other database cases once there's a working prototype

**Comment by zuphilip** [comment]
@owcz This should be fixed in https://github.com/zotero/translators/commit/d77ae04299d6854043ff91da3da49913cbb2f496. Can you confirm that?

**Comment by owcz** [comment]
@zuphilip Yes, most of Gale PowerSearch citations appear to be working! E.g., Academic OneFile, Gale Literature Resource Center) Thanks! 

No HTML or PDF attachments though.

and fwiw, there are some unaddressed edge cases for the future, e.g., Biography in Context multiples, and NewsVault as a whole, but those can be separate tickets
