### ISSUE TITLE
The Guardian translator: handle The Observer

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1347]
>https://github.com/zotero/translators/blob/master/The%20Guardian.js
Author @adam3smith 

theguardian.com also hosts content from The Observer, such as https://www.theguardian.com/books/2011/nov/27/christmas-gifts-2011-books-tree

The translator should handle the publication title as "The Observer" in these cases with its different ISSN (0029-7712)

**Comment by zuphilip** [comment]
Okay, I will look into this issue in my next PR.
