### ISSUE TITLE
Return multiple results page for Google Scholar.js author pages

### ISSUE THREAD

**Issue by mvolz** [zotero/translators#1376]
i.e. 

https://scholar.google.com/citations?user=FZBjJ4cAAAAJ

Would be nice to have a "multiple" result returned for that as well.

**Comment by mvolz** [comment]
Hmm, I see in the translator it actually is trying to save those, maybe it's just broken ?

**Comment by mvolz** [comment]
Ah, never mind, that's only for individual citations, not user pages. :)

**Comment by zuphilip** [comment]
Yes, that would be nice, but Google Scholar translator is a little complex. Do you have any specific use case in mind, because you write translation-server?

**Comment by mvolz** [comment]
My use case actually isn't translation-server/citoid related (we don't use the multiple results at all yet). Sorry, misleading headline. At first I thought it was supposed to work and wasn't but then I realised it wasn't designed it. 

I was more thinking, "hey I want to import all of Maryam's articles into wikidata, and where would I start because I don't want to do that manually" and thinking I would start first with the multiple results off the page :). 

I am kind of working on it right now, we'll see if I stick with it to make it to a PR :D.

**Comment by zuphilip** [comment]
Okay, let me know if you have any success on the translator.

(For your use case I created a BibTeX file here: https://gist.github.com/zuphilip/54058e84258c168dc3571ec0ebbaafd0 )

**Comment by owcz** [comment]
> "hey I want to import all of Maryam's articles into wikidata, and where would I start because I don't want to do that manually"

Side note: Is there an importer from Zotero to Wikidata?

**Comment by mvolz** [comment]
@owcz 

There is a Zotero export translator for quick statements (not in the main repo) here: https://github.com/UB-Mannheim/zotkat/blob/master/Wikidata%20QuickStatements.js

And this is where you can import quick statements: https://www.wikidata.org/wiki/Wikidata:Tools/External_tools#QuickStatements

It involves a few steps. It also is somewhat limited because it can't do queries, so it can't add linked fields like the publicationTitle. The alternative route is to use https://tools.wmflabs.org/sourcemd/? ; it can't do batches, but can't do queries.

**Comment by adam3smith** [comment]
fixed in https://github.com/zotero/translators/pull/1438
