### ISSUE TITLE
Zotero connect doesn't save from AMETSOC journals

### ISSUE THREAD

**Issue by gsever** [zotero/translators#1382]
Hello,

This seems to work before updating Zotero. Trying save an article into Zotero folder is stuck with a small "Saving to folder" pop-up.

http://journals.ametsoc.org/doi/abs/10.1175/MWR-D-16-0430.1 

Debug logs are indicating of no translators, though they should be bundled as in the previous versions by default:

(3)(+0000000): Not injecting. No translators found for [tab.url, url]: http://journals.ametsoc.org/doi/abs/10.1175/MWR-D-16-0430.1 , http://journals.ametsoc.org/action/showCitFormats?doi=10.1175/MWR-D-16-0430.1

Thanks.

testing Zotero 5.0.8 and Zotero Connector 5.0.16 on Google Chrome 60.0.3112.90 (Official Build) (64-bit).

**Comment by gsever** [comment]
Just a quick update.. I was able to save the article information using Zotero 5.0.9  and Zotero Connector 5.0.16. Apparently this glitch has been fixed with these updates.

**Comment by adam3smith** [comment]
Thanks for the update. Closing
