### ISSUE TITLE
APA PsycNET broken

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1385]
https://forums.zotero.org/discussion/66653/zotero-connector-for-chrome-broken-for-apa-psycnet

This is pretty unpleasant (and I got blocked as a bot very easily while trying to play with it), but it might be possible:

1) Get the UUID from either the Purchase button (logged out) or the Unique Identifier section (logged in).

2) POST to /api/request/record.exportRISFile, which looks like this:

```json
{"api":"record.exportRISFile","params":{"UIDList":[{"UID":"2017-34398-001","ProductCode":"PA"}],"exportType":"zotero"}}
```

3) POST to /ris/download, which should then contain the RIS prepared by the previous request (based on the session cookie, I guess).

I didn't test this, but that's the sequence of requests the browser is making.

**Comment by zuphilip** [comment]
It looks for me that the postdata has to be sent as a JSON object. How can we do this with `ZU.post` or similar function? When I just try this:
```js
	var risURL = "/api/request/record.exportRISFile";
	var postData = {
		"api": "record.exportRISFile",
		"params": {
			"UIDList":[
				{
					"UID": uid,
					"ProductCode": productCode
					
				}
			],
			"exportType": "zotero"
		}
	};
	ZU.doPost(risURL, postData, function(text) {
		Z.debug(text);
		...
```
then I see the following error message:
```
         string => TypeError: body.substr is not a function
         stack => Zotero.HTTP</this.doPost@chrome://zotero/content/xpcom/http.js:284:19
```

Cf. for 5.0 https://github.com/zotero/zotero/blob/master/chrome/content/zotero/xpcom/http.js#L370

**Comment by dstillman** [comment]
`JSON.stringify(json)` and then pass `{ "Content-Type": "application/json" }` for the headers

**Comment by zuphilip** [comment]
Related https://forums.zotero.org/discussion/71070/inserer-une-reference-a-partir-de-la-banque-psycnet-apa
