### ISSUE TITLE
Project MUSE fails on PDF save

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1389]
Individual pages (https://muse.jhu.edu/article/252466) and thus the multis fail to save the PDF (red X) even when it is accessible by click. Been like this for several months, so likely needs to be reworked.

**Comment by adam3smith** [comment]
works for me in initial tests. What setup are you testing this on? (both software & authentication)

**Comment by owcz** [comment]
Chrome on both Mac/Linux, will recheck Firefox. Authenticated through direct login (no proxy/SSO)

**Comment by adam3smith** [comment]
Zotero 4 or 5?

**Comment by owcz** [comment]
Zotero 4

**Comment by adam3smith** [comment]
Works in Chrome and FF in Zotero 5 for me. Will test 4 at home, but if this is fixed in 5 in general, we probably don't need to bother troubleshooting

**Comment by owcz** [comment]
The original link above is working for me now, under the same conditions. Not sure what the deal was—perhaps on their end?—but it appears resolved.
