### ISSUE TITLE
De Gruyter broken after html change

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1390]
reported: https://forums.zotero.org/discussion/67283/de-gruyter-translator-has-developed-problems/p1
example: https://www.degruyter.com/view/j/stuf.2017.70.issue-1/stuf-2017-0001/stuf-2017-0001.xml?format=INT

Problem is EM that has been moved to the html body.

**Comment by zuphilip** [comment]
> Problem is EM that has been moved to the html body.

We had a similar case recently, but I can't remember... Do you?

I think we just copied then the EM text from the body to the head and then called EM translator...

**Comment by adam3smith** [comment]
Yes, you fixed SAE (and they then fixed the EM on their side)

**Comment by zuphilip** [comment]
It seems that the misplaced `meta` tags are only part of the problem. IMO much worser is that deGruyter is now not offering any RIS for any item, but rather provide only three formatted export formats (MLA, APA, Chicago)! 😠

The test case for a book https://www.degruyter.com/view/product/462324 shows that there is no RIS, no metatag or any other structured data which could increase easily the scraping quality. Also for the special bibliographic database IBZ e.g. https://www.degruyter.com/view/IBZ/55568460-8061-41c8-8479-783eefecc02f , there is no export option, which makes the database IMO not usable anymore. That is IMO really bad from deGruyter!

**Comment by adam3smith** [comment]
No, you just missed it: there's an "Export" button that give you RIS at the bottom of the Cite window. Even looks like it has RIS at a static download link we can construct from the original URL, e.g.
https://www.degruyter.com/dg/cite:exportcitation/ris?t:ac=$002fproduct$002f462324/$N
and
https://www.degruyter.com/dg/cite:exportcitation/ris?t:ac=$002fIBZ$002f55568460-8061-41c8-8479-783eefecc02f/$N

**Comment by zuphilip** [comment]
Ah, yes, you are right. I am working to adjust things for RIS now too...

**Comment by zuphilip** [comment]
(This can be close now.)
