### ISSUE TITLE
Hein Online saves items twice

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1392]
Reported here: https://forums.zotero.org/discussion/66508/zotero-5-4-saves-a-source-twice-if-it-comes-with-a-pdf#latest
Permalink here: http://www.heinonline.org/HOL/Permalink?a=d2FrZWZvcmVzdC5lZHU&u=http%3A%2F%2Fwww.heinonline.org%2FHOL%2FPage%3Fhandle%3Dhein.journals%2Fgwlr76%26start_page%3D375%26collection%3Djournals%26id%3D389

Reported on Z5, replicated on Z4

**Comment by zuphilip** [comment]
(I don't have any access to HeinOnline.)

**Comment by zuphilip** [comment]
Okay, I have access now, but cannot replicate this issue. Therefore, I close this. Feel free to open it again @adam3smith if the issue persist for you.
