### ISSUE TITLE
ResearchGate translator

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1398]
New translator, lots of papers republished by authors here

EM doesn't handle pages such as
https://www.researchgate.net/publication/277464982_Much_in_Little_Revisiting_'lifelong_education'_'recurrent_education'_and_'de-schooling'_in_the_age_of_'lifelong_learning'

**Comment by adam3smith** [comment]
Yeah -- I've been staying away from it because there's so little structured data on the page that it's kind of insulting, but it'd be nice to have.

**Comment by adam3smith** [comment]
I also seem to remember that the site behaves quite differently when you're logged in and when you're not.

**Comment by zuphilip** [comment]
However, to overcome the lock-in effect of RG it might be actually a good target to do. I deleted my ResearchGate profile some time ago. As a not logged-in user I see the option to download the citation including abstract as RIS data, which seems to be simply one GET call. This looks easy to pack into a Zotero translator. Now, I am trying to create a fake account for ResearchGate, but this seems to be quite hard. Does anyone of you have an RG account?

**Comment by adam3smith** [comment]
alas I do, yes.

**Comment by owcz** [comment]
The translator doesn't appear to be saving the PDFs when available, and usually the screenshot is little help (is it even worth capturing?) Wanted to check whether others are having the same experience

**Comment by owcz** [comment]
The translator doesn't appear to be saving the PDFs when available, and usually the screenshot is little help (is it even worth capturing?) Wanted to check whether others are having the same experience

**Comment by zuphilip** [comment]
In your example I see a PDF with 26 pages, the first page is some introduction page by ResearchGate and the remaining pages are the actual paper. Snapshot might be negligible.

**Comment by owcz** [comment]
When I save https://www.researchgate.net/publication/231797128_Kropotkin's_Theory_of_Mutual_Aid_in_Historical_Context (Zotero 4), the dialog shows as having saved a Snapshot (with photo icon) but a PDF named "Snapshot" shows in my library, and it's corrupted (won't open). This is across browsers, but perhaps limited to Zot 4? (Wasn't going to move over until Scaffold and everything was ready)

Same result and reproducible with https://www.researchgate.net/publication/228450982_Plagiarism_really_is_a_crime_a_counterblast_against_anarchists_and_postmodernists_and_others
https://www.researchgate.net/publication/263973987_P_Lo_Cascio_A_Segura_e_A_Pellegrini_a_cura_di_Soldiers_Bombs_and_Rifles_Military_History_of_the_20th_Century_CSP_2013

The Snapshot saves correctly if there is no PDF to download

Can't seem to recall any recent usage in which the PDF downloaded properly without manual intervention—not sure how best to test

**Comment by zuphilip** [comment]
Now, I tried all three examples in Zotero 4.0 in Firefox and they work fine for me. I have a "Snapshot" of the website (which we might delete in the future) and a "Full text PDF":

![researchgate-z4-saves](https://user-images.githubusercontent.com/5199995/31585182-dfff16c0-b1bd-11e7-8f18-9a7f40ae3ba5.jpg)

It seems that you have some other problems. Check that you have the newest RG translator. @adam3smith Is this different when you are logged in?

BTW the current master branch of Scaffold does work within Zotero 5.0, also there is no new release yet.

**Comment by zuphilip** [comment]
@owcz Snapshot for ResearchGate is now delete and replaced with a link to the RG website.
