### ISSUE TITLE
Detect and prefer citation_year in EM

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1408]
Context: https://twitter.com/adam42smith/status/907335652982882305
Example: https://muse.jhu.edu/article/234097

**Comment by zuphilip** [comment]
The `citation_year` is detected in EM but `citation_online_date` is looked first, see https://github.com/zotero/translators/blob/ba0907552c32d5baa30734596feaea7e2c395cfb/Embedded%20Metadata.js#L464-L468 . A date is more accurate than only the year, but it can be that the online data is after the print publication date, e.g. the Muse example.

We could try something like
```js
	//fall back to some other date options
	if(!newItem.date) {
		var onlineDate = getContentText(doc, 'citation_online_date');
		var citationYear = getContentText(doc, 'citation_year');
		if (onlineDate && citationYear) {
			if (citationYear <{before} onlineDate) {//TODO some toDate transform before
				newItem.date = citationYear;
			} else {
				newItem.date = onlineDate;
			}
		} else {
			newItem.date = onlineDate || citationYear;
		}
	}
```
@adam3smith What do you think?

**Comment by adam3smith** [comment]
not sure why I never replied to this, but I think this is  exactly right. Do you want to implement it?
