### ISSUE TITLE
Handle NYPL in InnoPAC

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1412]
Permalink formats such as https://catalog.nypl.org/record=b10797975~S1 aren't handled

Getting errors on long formats too:
https://catalog.nypl.org/search~S1/?searchtype=t&searcharg=The+Pantarch%3A+A+Biography+of+Stephen+Pearl+Andrews&searchscope=1&sortdropdown=-&SORT=DZ&extended=0&SUBMIT=Search&searchlimits=

**Comment by AbeJellinek** [comment]
Working fine now with their new catalog(s).
