### ISSUE TITLE
CNKI wrong capture the item of author

### ISSUE THREAD

**Issue by qiuzhu** [zotero/translators#1419]
when i download the item from CNKI (chinese),and I find very bibtex in the author item contains  comma , for example:
@article{YangDianDongLiShengXiZhouQiJieQiuJieJiWenDingXingKongZhi2015,
  langid = {中文;},
  title = {电动力绳系周期解求解及稳定性控制},
  issn = {1674-5620},
  issue = {02},
  journaltitle = {飞行器测控学报},
  author = {杨, 育伟 and 蔡, 洪},
  urldate = {2017-09-17},
  date = {2015},
  pages = {168--175},
}
@article{YuKongJianDianDongLiShengXiTongLiLunJiShiYanYanJiu2016,
  timestamp = {2017-09-17T09:54:31Z},
  langid = {中文;},
  title = {空间电动力绳系统理论及实验研究},
  issn = {1000-0992},
  issue = {00},
  journaltitle = {力学进展},
  author = {余, 本嵩 and 文, 浩 and 金, 栋平 and 陈, 提},
  urldate = {2017-09-17},
  date = {2016},
  pages = {226--266},

}
author = {杨, 育伟 and 蔡, 洪},  author = {余, 本嵩 and 文, 浩 and 金, 栋平 and 陈, 提},
it seems it seperate the name by comma

**Comment by zuphilip** [comment]
Different authors are splited in BibTeX by `and` and the comma is used to separate lastname, firstname for each author. When I import these BibTeX data then this is exactly what Zotero does, e.g.:

![bibtex-chinese-authors](https://user-images.githubusercontent.com/5199995/31573731-ff7e26dc-b0c1-11e7-9d71-8ce7a56cb10f.jpg)

Is there anything wrong with that @qiuzhu ?

**Comment by qiuzhu** [comment]
yes,I know , but when i search one in Google scholar ,the bibtex is just like this :
`@article{余本嵩2016空间电动力绳系统理论及实验研究,
  title={空间电动力绳系统理论及实验研究},
  author={余本嵩 and 文浩 and 金栋平 and 陈提 and others},
  journal={力学进展},
  number={2016 年 01},
  pages={226--266},
  year={2016},
  publisher={中国科学院力学研究所| 中国力学学会}
}
限制解除 `


this is right, there is no comma between last name, first name, so I use the bst file , the output is right,
from my review ,it is better not add a comma to them  , usually a bst style can handle it

**Comment by zuphilip** [comment]
There is currently no DOI search translator which can handle DOIs from CNKI. That was already noted in a different issue.
