### ISSUE TITLE
ProQuest proxy support

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1425]
PQ uses `search.proquest.com` as the base URL in its translator's detection, but that will ignore base URLs behind proxy such as `search-proquest-com.i.ezproxy.nypl.org`. Is proxy detection handled elsewhere or is this a matter of generalizing the database's URL detect? (Also affects URL ingestion for the citation, as the proxy should be generalized)

**Comment by adam3smith** [comment]
that's handled elsewhere, in Zotero's proxy code (as of Zotero 5.0 -- I think citoid is still on 4?)
