### ISSUE TITLE
Google Scholar: PDF from right-hand column not being saved

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1429]
I'm no longer getting a PDF for the first result on https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=test&btnG=.  Not sure if it's working for other search results, but I'm guessing this changed with the site redesign.

**Comment by zuphilip** [comment]
I started working on this as well as some other recent issues with GS. Hopefully, I have a PR soon...

**Comment by adam3smith** [comment]
I actually have this ready...

**Comment by zuphilip** [comment]
Okay, I stopped and pushed what I have #1438 for further discussion.

**Comment by adam3smith** [comment]
fixed in https://github.com/zotero/translators/pull/1438
