### ISSUE TITLE
Microbiology Society Journals -- One broken article (bad metadata)

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1430]
Broken (site redesign?)
Sample: http://mgen.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000131
Reported: https://forums.zotero.org/discussion/67973/unable-to-save-references-from-microbial-genomics#latest

**Comment by zuphilip** [comment]
No, the translator still works, see the test cases there. But [this specific article](http://mgen.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000131) just has bad metadata, where the title is always missing, e.g. [RefWorks data](http://mgen.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000131.v1/cite/refworks):
```
RT Journal Article
SR Electronic(1)
A1 Hunt, Martin
A1 Mather, Alison E
A1 Sánchez-Busó, Leonor
A1 Page, Andrew J
A1 Parkhill, Julian
A1 Keane, Jacqueline A
A1 Harris, Simon R
YR 
T1 
JF 
UL http://mgen.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000131.v1
```

**Comment by AbeJellinek** [comment]
This article works fine now.
