### ISSUE TITLE
New Yorker translator doesn't handle some magazine pages

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1431]
Translator handles most pages, e.g.,
https://www.newyorker.com/news/news-desk/how-the-nra-manipulates-gun-owners-and-the-media
but the following are kicked to EM
https://www.newyorker.com/magazine/2016/06/27/after-orlando-examining-the-gun-business
https://www.newyorker.com/magazine/2017/06/19/remembering-the-murder-you-didnt-commit
https://www.newyorker.com/magazine/2017/05/22/what-makes-a-parent

Not sure if it's a bug NYer-side or something to fix in translator detection, as other pages in the same format don't have the issue (but I suppose we could start with whether it's reproducible)

https://github.com/zotero/translators/blob/master/The%20New%20Yorker.js
@zuphilip

**Comment by adam3smith** [comment]
Yes, reproducible
