### ISSUE TITLE
IEEE Xplore multiples broken

### ISSUE THREAD

**Issue by prototype35** [zotero/translators#1435]
Issue reported in  #1420 is still occurring (or occurring again) when selecting more than 2 items.
Tested on http://ieeexplore.ieee.org/search/searchresult.jsp?newsearch=true&queryText=testing using  Firefox 56.0 and Zotero Standalone 5.0.22.

**Comment by dstillman** [comment]
This will likely be fixed (and is in my testing) in the next version of the connector, 5.0.25, due to a change in how multiples are handled. Reopen if you're still having trouble after that.

**Comment by prototype35** [comment]
On version 5.0.26 of the connector it now saves the references and the web page but not the PDFs
