### ISSUE TITLE
arXiv paper not found, also affects chrome plugin

### ISSUE THREAD

**Issue by LinxiFan** [zotero/translators#1439]
I'm quite new to Zotero. For some arxiv papers, both the plugin and the desktop work fine, but for others they break. I'm a CS student, so arXiv is my primary reference source. 

Example: https://arxiv.org/pdf/1708.00133.pdf

The chrome plugins reports error: `JavaScript Error: "TypeError: Cannot use 'in' operator to search for 'length' in undefined` 
Then I manually download and add the pdf to my desktop zotero. I click "Retrieve Metadata for PDF", but it reports "no matching references found". 

I'm using the latest Zotero (5.0.22) and chrome plugin as of today. No proxies. 
Thanks for your help!

**Comment by adam3smith** [comment]
and you get that consistently? This is the error we get when the arXiv API is down, but we've had one other person report this consistently. It works for me. 
Do you have any other add-ons installed in chrome? Could you try disabling them?

**Comment by LinxiFan** [comment]
1. The chrome plugin works now! You are right, I think it's arxiv's problem.
2. However, the Zotero desktop program (Mac OS X Sierra) still can't find that particular pdf, if I manually download and right click "Retrieve Metadata for PDF". I just reinstalled and retested a few minutes ago. 
3. It looks like the desktop app fails consistently even for other arxiv pdfs, like this random piece: https://arxiv.org/pdf/1710.01813.pdf

**Comment by adam3smith** [comment]
retrieve metadata works through CrossRef (which doesn't apply here) and google scholar. It can sometimes fail -- more likely on preprints than on published articles, so that's not a bug. It'll just happen occasionally.
