### ISSUE TITLE
Translators for Medium-supported blogs under different domain names

### ISSUE THREAD

**Issue by louy2** [zotero/translators#1446]
Some of them are:

- https://theestablishment.co/
- https://gloss.xyz/
- https://medium.freecodecamp.org/

These websites share the same structure as medium itself, but is not supported by the medium translator due to domain-based matching. Shall they be added case-by-case or is there a better way?

**Comment by dstillman** [comment]
It's not necessary — the Medium translator just passes the page off to Embedded Metadata translator, strips the "– Medium" suffix off the page title (which doesn't exist on the other sites), and changes the item type to Blog Post. So the only difference is the item type, and Blog Post is kind of an anachronism anyway that we should arguably get rid of, but you can change it to that if you care. You'll end up with the same data either way.

**Comment by louy2** [comment]
Thanks for the explanation.
