### ISSUE TITLE
Sciencedirect search results are broken

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1447]
Reported: https://forums.zotero.org/discussion/68218/zoteros-sciencedirect-downloader-does-not-work-now#latest

Example:
http://www.sciencedirect.com/search?qs=&authors=birkenholtz&pub=geoforum&volume=&issue=&page=&origin=home&zone=qSearch

isn't even detected.

**Comment by pedrom34** [comment]
This looks like to be related to the new version of science direct.  
They updated the website something like a month ago.  
You can actually get the results in the old page style:
http://www.sciencedirect.com/science?_ob=ArticleListURL&_method=list&_ArticleListID=-1238954459&_sort=r&_st=4&md5=847ecc3fbc51e0b0e54cfd56ec2aa142&searchtype=a
  
I did my search using this page < http://www.sciencedirect.com/science/search > and I didn't use the fields in the upper search bar.
