### ISSUE TITLE
Microsoft Academic does not detect

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1450]
Reported: https://forums.zotero.org/discussion/68222/translator-for-microsoft-academic-2-0#latest

Looks to me like the site hasn't changed that much, so hopefully should be quick.

**Comment by zuphilip** [comment]
The detection relies heavily on `detectDOMChanges` but we shouldn't use that anymore as @dstillman pointed out. This might become tricky here...

**Comment by dstillman** [comment]
Is that what I said? `detectDOMChanges()` itself isn't a problem when used in `detectWeb()`. You just can no longer rely on JS page updates when using `processDocuments()`.

**Comment by zuphilip** [comment]
Okay, I missed that apparently. Sorry! Then it might be easier to update the translator here...

**Comment by zuphilip** [comment]
Fixed in #1564.
