### ISSUE TITLE
bibtex en-dash

### ISSUE THREAD

**Issue by twsh** [zotero/translators#1465]
The bibtex importer replaces '--' with '-'. Some sites, e.g. PhilPapers, sometimes have records containing en-dashes ('–'/`u+2013`). Is there a reason why the translator regex shouldn't match them both for the replacement?

**Comment by adam3smith** [comment]
Zotero is fine with either en-dash or hyphen in the page field. Any reason we should replace the utf-8 en-dash?

**Comment by twsh** [comment]
Maybe not, in that case.

**Comment by adam3smith** [comment]
OK, closing the  -- I'm happy to revisit if there's a compelling case, but if so this might be better suited for a higher level, since obviously bibtex isn't the only place Zotero would get en-dashes from.
