### ISSUE TITLE
FAZ Translator broken

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1470]
http://www.faz.net/aktuell/feuilleton/worauf-koennen-die-europaeer-stolz-sein-15278563-p2.html

Reported: https://forums.zotero.org/discussion/7433/new-translatros-wished-for-faz-and-nzz#latest

**Comment by zuphilip** [comment]
I am working on this...

**Comment by adam3smith** [comment]
Thanks I know -- I thought I'd be able to assign you, but I think you're not in a category of collaborators I can assign issues to.

**Comment by zuphilip** [comment]
Now you can :-)
