### ISSUE TITLE
OCLC reports website

### ISSUE THREAD

**Issue by katrinleinweber** [zotero/translators#1471]
The OCLC reports website ([example](https://www.oclc.org/research/publications/2017/oclcresearch-defining-rim.html)) does not currently have its own translator. Translating as a website works, but with several pieces of metadata in Zotero missing:
![oclc-reports-lack-zotero-translator](https://user-images.githubusercontent.com/9948149/32600290-71fbf6f8-c53f-11e7-9060-669432f5818a.PNG)

Maybe @campbelg could chime in, because he worked with JavaScript in the  "OCLC developer house" org?

**Comment by adam3smith** [comment]
1. You can import this using right-click on the Save to Zotero icon --> Save to Zotero --> DOI
2. The rest is really up to OCLC -- this seems a rather specialized site to add a dedicated translator and they could just fix this by improving the metatags. Particular, they should populated DC.creator, which already exists in the metaheader, but is empty.

**Comment by adam3smith** [comment]
I'll close this -- let us know if you need anything else from the Zotero end.
