### ISSUE TITLE
Publication year missing

### ISSUE THREAD

**Issue by kettner** [zotero/translators#1476]
Could it be that the publication date field is missing in the CrossRef translator? See for example: https://en.wikipedia.org/api/rest_v1/data/citation/zotero/10.1130%2Fg38665.1
Only access date of URL is provided, not publication date. Not 100% sure though this is the right translator for the journal (Geology)? If right translator, could this be fixed?
Thanks, Albert.

**Comment by adam3smith** [comment]
Zotero imports the publication date for all sources of this article:
https://pubs.geoscienceworld.org/geology/article/45/4/311-314/195361
http://geology.geoscienceworld.org/content/45/4/311
and via DOI: 10.1130/g38665.1

How exactly is that data generated? 
(generally we'd prefer if you tested translator issues in Zotero proper before reporting -- we're all very excited translators are getting used in Wikipedia/Citoid, but the two are not the same thing and we don't have the capacity to troubleshoot Citoid here).

**Comment by kettner** [comment]
Thanks for the prompt response,
Yes, data is generated using Citoid service of mediawiki, by providing DOI of publication. Sorry if I contacted the wrong group, I thought it was a translator problem, but could very well be a Citoid implementation problem as well.
Thanks,
Albert.

**Comment by adam3smith** [comment]
My recollection is that Citoid actually does not use Zotero for DOI import. So yes, I'd report this for Citoid. Zotero imports 04/2017 as the publication date from CrossRef via DOI.

**Comment by dstillman** [comment]
> My recollection is that Citoid actually does not use Zotero for DOI import.

Yes, it wouldn't have been able to. We [recently added](https://github.com/zotero/translation-server/commit/79481f510db781d43d135c3601b63f9f6c739f30) a `/search` endpoint to translation-server (currently only on `master`, not the Docker Hub version) that makes this possible.
