### ISSUE TITLE
Problems with neuron, Zotero stops

### ISSUE THREAD

**Issue by shiliang-hust** [zotero/translators#1498]
When trying to save any articles of Neuron (http://www.sciencedirect.com/journal/neuron), zotero stops and so does the debugger. Can anybody reproduce it? 

I'm using Zotero 5.0.32 on archlinux and firefox 57.0.2

**Comment by zuphilip** [comment]
Individual article from Neuron works for me. What url did you try exactly?

**Comment by adam3smith** [comment]
I think this is better suited for the Zotero forums -- it's not a general issue and the forms are a better place for generic troubleshooting. Post to forums.zotero.org following these: https://www.zotero.org/support/troubleshooting_translator_issues
