### ISSUE TITLE
Feature: EUR-Lex Translator

### ISSUE THREAD

**Issue by rriemann** [zotero/translators#1499]
It would be nice to be able to extract a proper Zotero (biblatex) entry from http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31995L0046 with Zotero.

I am doing volunteer work to show markdown editing to policy makers in Brussels. So far, people are overwhelmed by all kind of citations (in footnotes) and maybe biblatex, markdown and zotero can help here. (This would be a nice opensource set to replace commercial word processors.)

**Comment by rriemann** [comment]
Existing Discussion from 2015: https://forums.zotero.org/discussion/46419/working-with-civil-law-jurisdictions-italy-france-spain-germany-etc

**Comment by zuphilip** [comment]
Technically it looks like there is a huge amount of information in the `meta` tags of this website:

![eur-lex-metadata](https://user-images.githubusercontent.com/5199995/34174913-e21c105a-e4fa-11e7-82b1-e97264dd5148.png)

However, we would need some help in how to order these into the Zotero fields and which itemType to use.

What Zotero itemType is your example? How would you enter the bibliographic information for your example into Zotero (what information goes into which fields)?

**Comment by rriemann** [comment]
Indeed, we have meta data in many languages. I have to ask which is the expected format. Here for english:

```
<meta about="http://data.europa.eu/eli/dir/1995/46/oj" property="eli:is_realized_by"
      resource="http://data.europa.eu/eli/dir/1995/46/oj/eng"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng" property="eli:realizes"
      resource="http://data.europa.eu/eli/dir/1995/46/oj"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng" property="eli:language"
      resource="http://publications.europa.eu/resource/authority/language/ENG"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng" property="eli:title"
      content="Directive 95/46/EC of the European Parliament and of the Council of 24 October 1995 on the protection of individuals with regard to the processing of personal data and on the free movement of such data"
      lang="en"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/html" typeof="eli:Format"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng"
      property="eli:is_embodied_by"
      resource="http://data.europa.eu/eli/dir/1995/46/oj/eng/html"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/html"
      property="eli:embodies"
      resource="http://data.europa.eu/eli/dir/1995/46/oj/eng"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/html" property="eli:format"
      resource="http://www.iana.org/assignments/media-types/text/html"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/html"
      property="eli:publisher_agent"
      resource="http://publications.europa.eu/resource/authority/corporate-body/PUBL"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/pdfa1b" typeof="eli:Format"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng"
      property="eli:is_embodied_by"
      resource="http://data.europa.eu/eli/dir/1995/46/oj/eng/pdfa1b"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/pdfa1b"
      property="eli:embodies"
      resource="http://data.europa.eu/eli/dir/1995/46/oj/eng"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/pdfa1b"
      property="eli:format"
      resource="pdfa1b"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/pdfa1b"
      property="eli:publisher_agent"
      resource="http://publications.europa.eu/resource/authority/corporate-body/PUBL"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/print" typeof="eli:Format"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng"
      property="eli:is_embodied_by"
      resource="http://data.europa.eu/eli/dir/1995/46/oj/eng/print"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/print"
      property="eli:embodies"
      resource="http://data.europa.eu/eli/dir/1995/46/oj/eng"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/print"
      property="eli:format"
      resource="print"/>
<meta about="http://data.europa.eu/eli/dir/1995/46/oj/eng/print"
      property="eli:publisher_agent"
      resource="http://publications.europa.eu/resource/authority/corporate-body/PUBL"/>
```

**Comment by rriemann** [comment]
So this is the ELI document meta data exchange format, specified here:
http://eur-lex.europa.eu/eli-register/about.html

I guess that there are other websites that implement this. So maybe the translator should not be for eur-lex but for ELI.

**Comment by zuphilip** [comment]
I started to work here a little and my current result looks like this:
```js
"itemType": "bill",
"title": "Directive 95/46/EC of the European Parliament and of the Council of 24 October 1995 on the protection of individuals with regard to the processing of personal data and on the free movement of such data",
"creators": [],
"date": "1995-11-23",
"billNumber": "31995L0046",
"code": "281",
"codeVolume": "OJ L",
"language": "en",
"legislativeBody": "EP, CONSIL",
"url": "http://data.europa.eu/eli/dir/1995/46/oj/eng",
"attachments": [],
"tags": [],
"notes": [],
"seeAlso": []
```

How does this look like for you? Is the itemType `bill` here okay?

Moreover, we would need a mapping for all possible itemTypes ([list of them](http://publications.europa.eu/mdr/resource/authority/resource-type/html/resourcetypes-eng.html)) and some more examples. Can you help us here?

**Comment by rriemann** [comment]
I am not a lawyer, but just a person with tech training in a lawyer-dominated environment. I asked few colleagues and they do not know precise rules. They suggested to look into the contributor guidelines of EU law journals.

![era](https://user-images.githubusercontent.com/111932/34251698-3939037e-e641-11e7-9414-69b3923b88a9.png)

---

![rules](https://user-images.githubusercontent.com/111932/34251884-d239665e-e641-11e7-8047-b98594a8dd24.png)
Source: House Style Guide linked here http://www.sweetandmaxwell.co.uk/catalogue/productdetails.aspx?recordid=427&productid=6968

---

The ultimate guide is probably this one:
https://news.law.fordham.edu/filj/wp-content/uploads/sites/6/2016/02/2015-2016-EU-Guide.pdf

On page 24, you find:

![rules2](https://user-images.githubusercontent.com/111932/34252276-46849294-e643-11e7-96a4-4c556e146fa1.png)


Source: http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291468-0386/homepage/ForAuthors.html

**Comment by rriemann** [comment]
I have found another interesting source.

The university of Oxford has a documentation on citing laws from whatever country.
https://www.law.ox.ac.uk/research-subject-groups/publications/oscola

They also provide files to integrate with latex or **Zotero**.

The latex guide has a lot of information and I think now that for the use within EU institutions, the zotero translator should focus on compatibility with the existing oscola resources for zotero and latex.
http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex-contrib/oscola/oscola.pdf

So ideally, the translator allows to create bibfiles for the oscola biblatex style.

**Comment by zuphilip** [comment]
Okay, I continued to work on a translator and it works fine for me. The tests cover directives and regulations. Any testing and feedback would  be welcome. Here is the pull request: https://github.com/zotero/translators/pull/1502

_Citation styles in law_: Yeah, there is OSCOLA and other styles which are implemented in CSL and can be used with Zotero, cf. https://www.zotero.org/styles/?fields=law

**Comment by rriemann** [comment]
I am totally new to Zotero. I read about `chrome://zotero/content/tools/testTranslators/testTranslators.html, but as I am using the standalone Zotero version, I do not know how I can use it. :(

**Comment by rriemann** [comment]
I run Scaffold and copied the individual parts from the pull request to the inputs of Scaffold in lack of an import from the file in the pull request.

I run the standalone version of Zotero on Linux from the extracted tar archive. Where are the web translator files stored?

**Comment by zuphilip** [comment]
The translators are a subfolder in the [Zotero data directory](https://www.zotero.org/support/zotero_data), i.e. on Linux usually `~/Zotero/translators`. After copying a file there, you might then have to restart Zotero and/or your browser.

**Comment by rriemann** [comment]
So I moved using the Zotero preferences my data to ~/Zotero. I checked that there is the file `~/Zotero/translators/EUR-Lex.js` in place which is now found by the tool Scaffold. I restarted my browser Firefox nightly and still do not get the offer to use this translator: :(

![screenshot_20171222_135247](https://user-images.githubusercontent.com/111932/34298711-65867b30-e71f-11e7-83de-1066d264b237.png)

**Comment by dstillman** [comment]
It will get updates from Zotero every 24 hours if Zotero is open. You can click Update Translators in the Connector preferences to do that immediately. (A future version will make that instantaneous.)

**Comment by rriemann** [comment]
@dstillman, can you download the file https://github.com/zuphilip/translators/blob/79aaf9687b66205a4fb0ef487403802d0529da1a/EUR-Lex.js and check if firefox offers after having updated translators to use it for the link http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2016.119.01.0001.01.ENG&toc=OJ:L:2016:119:TOC ?

I updated the translators but it does not have any effect.

**Comment by adam3smith** [comment]
doesn't work for me either and it seems like the translator isn't loading into memory. Can't figure out why atm.

**Comment by dstillman** [comment]
Works for me. @rriemann, make sure you're saving the raw file, not the HTML page.

**Comment by rriemann** [comment]
OK, I got it working now when installing it without the scaffold tool. :)

**Comment by adam3smith** [comment]
I think we may well be hitting the limits of what Zotero can accomplish with legal citations. E.g. a lot of these fields don't exist for Zotero, others don't make sense as general rule exports into BibLaTex. There's a dedicated fork for legal references of Zotero that tries to address this, but it's massively complex as the correct formatting of legal citation depends on the jurisdiction of the document, i.e. US regulations are cited different from EU one, which in turn are different from UK ones, etc. 
Zotero isn't going to get even close to that in the medium run.

**Comment by rriemann** [comment]
I added the following in the extra field for full support of oscola:

```
bibtex:gdpr

bibtex{
  journaltitle: "OJ",
  series: "L",
  issue: 119,
  number: "2016/119",
  type: "regulation",
  pagination: "article",
  keywords: "eu"  
}
```

Result with biblatex:

>  Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the Protection of Natural Persons with Regard to the Processing of Personal Data and on the Free Movement of Such Data, and Repealing Directive 95/46/EC (General Data Protection Regulation) [2016] OJ L119/1.

**Comment by floriandierickx** [comment]
Hey all, as a reference to this issue: an idea for an update to the translator here: https://github.com/zotero/translators/pull/1502#issuecomment-733934885

**Comment by barthoekstra** [comment]
Hi all, I struggled with this too, but thankfully @floriandierickx's solution still worked well.

It seems the EUR-lex translator currently still is (partially) broken. I don't need to cite EUR-Lex much if at all, so it doesn't matter much for me personally, but figured it's worth pointing out here.
