### ISSUE TITLE
Hathi Trust -- extend translator for excerpts

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1506]
such as http://babel.hathitrust.org/cgi/pt?id=njp.32101082376805;view=1up;seq=274;size=175

See https://forums.zotero.org/discussion/56668/hathitrust-translator-icon-not-working#latest
They have COinS, but it's lousy and often breaks. We should instead get the RIS from the main catalog page. I don't think that should be prohibitively hard.

**Comment by AbeJellinek** [comment]
Fixed by #2512.
