### ISSUE TITLE
BibTeX: Fix string definition handling and add concatenation support

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1519]
I suspect string definition handling has been broken since ff884aa1780ae86687afc78faa29439e5642b09d. String definitions are properly read and substituted, but a `rawValue` isn't passed to `processField()`, which expects one for name fields:

https://github.com/zotero/translators/blob/18f8d6a2f3d7727c2acfd42f021f0adbd2abd9df/BibTeX.js?utf8=%E2%9C%93#L880-L888

This [causes an import to hang](https://forums.zotero.org/discussion/comment/297735/#Comment_297735) with `rawValue is undefined`.

This part could be fixed with `value = rawValue = strings[value]`.

However, it looks like we also don't support [concatenation using `#`](http://artis.imag.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html#stringdef), and since that's likely to be used with string definitions, we should fix that at the same time.

Sample entry:

```
@string{TEST = "Test"}

@book(StringDefinitionTest,
author = TEST # { and Test2},
)
```

(I don't know when I'll be able to get to this, so it'd be great if someone else could look at this.)

**Comment by zuphilip** [comment]
Fixed in #2020.
