### ISSUE TITLE
Importing from a suscriber URL in LeMonde.fr translator

### ISSUE THREAD

**Issue by laspic** [zotero/translators#1520]
When importing a paper reference from the French website LeMonde.fr :
- the translator is available if using the common URL : http://www.lemonde.fr/... ;
![capture d ecran_2018-01-12_09-24-10](https://user-images.githubusercontent.com/3339204/34865981-1f3f2048-f77b-11e7-83a2-ded763c4280d.png)

- the translator is absent if using the suscriber URL : http://abonnes.lemonde.fr/...
![capture d ecran_2018-01-12_09-24-39](https://user-images.githubusercontent.com/3339204/34865984-210ec298-f77b-11e7-9a20-829c61153d86.png)

**Comment by zuphilip** [comment]
See #1521 for a try to fix this. But I am not a subscriber of Le Monde and can therefore not test this.
