### ISSUE TITLE
[PICA] Sudoc multiple translation failure

### ISSUE THREAD

**Issue by adomasven** [zotero/translators#1529]
Reported here https://forums.zotero.org/discussion/comment/297799/#Comment_297799

> I can see the issue with saving from the search results. Seems like if you load http://www.sudoc.abes.fr/xslt/DB=2.1/SET=9/TTL=1/CMD?ACT=SRCHA&IKT=1016&SRT=RLV&TRM=test then it works fine, however by default the library serves the results at http://www.sudoc.abes.fr//DB=2.1/SET=9/TTL=1/CMD?ACT=SRCHA&IKT=1016&SRT=RLV&TRM=test (note the missing xslt just after domain name), which makes all the subsequent URLs also follow that signature, which ends up serving documents in PICA XML format instead of plain HTML. Seems like there is some JS in the PICA catalogue that tries to rewrite the URL, but fails with newer versions of browsers (Zotero is based on Firefox ESR). Even with a modern browser this likely wouldn't have been a problem before the switch to XHR processDocuments. On the other hand e.g. goettingen catalogue works fine. Translator folk will need to look at this.

**Comment by zuphilip** [comment]
What I see here, is that the `newUrl` which is used as a prefix for building the individual urls for multiples, is correct in Scaffold `http://www.sudoc.abes.fr/xslt//DB=2.1/SET=1/TTL=1/` but in browser this is `http://www.sudoc.abes.fr//DB=2.1/SET=7/TTL=1/`. See https://github.com/zotero/translators/blob/535df2d3a68c429aa67e579a799dc91e45d5588b/Library%20Catalog%20(PICA).js#L585

We can just set the correct `newUrl` fixed for SUDOC after this line. I will try this...

**Comment by symac** [comment]
Commented on pull request, just a little fix added to the previous one, now seems to work fine.

**Comment by zuphilip** [comment]
Okay, I merged the PR now as a hotfix. 🔥 

Your Zotero Connector should auto-update within 24 hours, or you can update manually by clicking Update Translators in the Advanced pane of the Zotero Connector preferences.

Any further problems let us know & thanks for reporting.
