### ISSUE TITLE
[Improvement] Translator for USENIX

### ISSUE THREAD

**Issue by yxliang01** [zotero/translators#1531]
Would be good if we can have a translator for [USENIX](https://www.usenix.org/).

Thanks

**Comment by zuphilip** [comment]
What is USENIX? Example URLs?

**Comment by yxliang01** [comment]
@zuphilip 
The official website is https://www.usenix.org/ . 
Example links:
(KLEE: Unassisted and Automatic Generation of High-Coverage Tests for Complex Systems Programs)[https://www.usenix.org/conference/osdi-08/klee-unassisted-and-automatic-generation-high-coverage-tests-complex-systems]
This example contains video, audio and the paper. Would be great if the translator can identify all these. However, this doesn't contain abstract and authors' names. 

(SpyProxy: Execution-based Detection of Malicious Web Content)[https://www.usenix.org/conference/16th-usenix-security-symposium/spyproxy-execution-based-detection-malicious-web-content]

Thanks!

**Comment by zuphilip** [comment]
There is AFAIS no bibliographic metadata on that website (no BibTeX, not in the visible HTML content, not in the meta tags). Thus, I don't see any chance to scrape here reasonable information from USENIX.

I would rather point you then to DBLP to search again for the bibliographic info and you can use Zotero there, e.g. http://dblp.uni-trier.de/rec/bibtex/conf/osdi/CadarDE08.

**Comment by yxliang01** [comment]
Right. How about a translator to extract the title, paper, video and audio? And then, later on can gather other information from DBLP and merge these two records.

Thanks!

**Comment by zuphilip** [comment]
Sorry, but these is not worth the trouble and effort.

Start with reasonable data e.g. at DBLP and then add any attachments you want.

**Comment by 0x161e-swei** [comment]
In fact, in recent conferences of USENIX, the paper pages do have BibTex available.

Example:
https://www.usenix.org/conference/usenixsecurity17/technical-sessions/presentation/kohlbrenner
