### ISSUE TITLE
Goodreads translator request

### ISSUE THREAD

**Issue by mvolz** [zotero/translators#1539]
Goodreads has fairly good book metadata, i.e. https://www.goodreads.com/book/show/18467746-the-norm-chronicles

**Comment by zuphilip** [comment]
Okay. I don't see any export format or rich meta data on their website. Thus, a direct web scraper would be needed here. Some information are part of a string which would need to split into several parts, e.g.
```
Hardcover, Second Edition, 1132 pages
Published December 20th 2002 by Prentice Hall (first published December 13th 1994) 
```

**Comment by dstillman** [comment]
There's a `books:isbn` meta property. Shouldn't we just look for that and do a regular ISBN lookup? I don't think scraping the Goodreads metadata makes much sense.

**Comment by snie2012** [comment]
Any updates on the feature?
