### ISSUE TITLE
ScienceDirect Advanced Search Results don't Detect

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1556]
Example:
https://www.sciencedirect.com/science?_ob=ArticleListURL&_method=list&_ArticleListID=-1251673855&_sort=d&_st=1&md5=2798717aec748242ecfe9606e28ba6b1&searchtype=a

Reported: https://forums.zotero.org/discussion/70388/science-direct-expert-search-results-not-recognized#latest

**Comment by AbeJellinek** [comment]
Works now.
