### ISSUE TITLE
Support for multiple search result pages in Koha

### ISSUE THREAD

**Issue by Marcool04** [zotero/translators#1565]
Hi all,
I am currently working on an assignment in a research library where the database of available works is handled through Koha. The specific situation is that we want to compare what we have in our library, and what is available "out in the world" on a specific subject, in order to come up with a kind of "wanted" list.
I am using Zotero to centralize, de-duplicate, organize and manage the references that I'm collecting from several sources: Web Of Knowledge, Google Scholar searches, Publish or Perish exports, CrossRef searches, you name it!
I am also trying to find the most efficient way to get the references for the works we already have from our library catalog into Zotero. This I can do quite efficiently, when I have performed a search in Koha, by using the "multi" import translator function, my problem is that this is limited to importing from a single page of results, and that Koha itself has no option to display all results on one single page (I'm looking a several dozen pages of results here).
(Ok, sorry, this issue is getting long…)
What I would like to get some input on is this: 
**Do you think there is a sufficient use case for—and is it technically possible—to extend a Zotero translator such as the one used for Koha so it can import results from multiple pages of search results?**
I am not asking somebody to code that, that would sort of be part of my job in this case, but I'm just wondering if it is the right "way to go", or if your opinion would be to look at other options.
Thanks in advance for any input,
All the best.
Mark.

**Comment by zuphilip** [comment]
The technical basis of the Zotero translators is JavaScript and therefore it is technically possible to go through several pages of search results and trigger the scraping on all of them. But you have to do this for your local copy of the translator, as this is not in the main focus of Zotero.

However, I wonder whether you don't have the data in a more direct way. The library catalogue is just the frontend for the users, but the library itself should have some database with their data and can usually produce easily the data in some structured formats like MARC or MODS, which Zotero then can import easily.

**Comment by Marcool04** [comment]
Thanks for your reply @zuphilip. Yes I had noticed that the translators were written in Javascript, I was wondering if there was some kind of "sandboxing" which would prevent an extension such as Zotero and its translators from acting on pages other than the current one (I'm not well versed in the workings of Firefox/etc extensions).
I do indeed have access to the underlying database that Koha uses, which is in fact simply a MySQL table, with MARC formatted XML in it (among other data structures). I can export this, and Koha even provides a sort of SQL query builder to assist, but the search interface has some powerful features I was hoping to be able to leverage (most notably: it will search specific fields in the MARC from the MySQL tables, whereas if I want to do that in SQL I have to wrangle the scary [MySQL XML functions](https://dev.mysql.com/doc/refman/5.7/en/xml-functions.html) ).
Nevertheless, I expect my time will be best spend crafting a single, well thought out SQL query rather than hacking the translator to be able to use the search interface.
Once again, thank you, your input is much appreciated.
Regards,
Mark.

**Comment by zuphilip** [comment]
No, you can open every website from a Zotero translator by using e.g. `ZU.doGet` function.

Just checked and the Koha translator is actually using also the MARCXML data:
https://github.com/zotero/translators/blob/de6a09c518ca89578af6f40745b4df485d903989/Library%20Catalog%20(Koha).js#L113-L118

Thus the data quality should stay equally good and it is up to you if you want to go directly to the database are you adapt the existing workflow with the Koha translator.

**Comment by Marcool04** [comment]
Indeed, on close inspection, it would seem possible to extend the translator that is already in place for Koha to scrape several pages of results. The key would be to get the links, then call detectWeb() on each one to build an array of links to perform the scrape on. I'm still not clear on the context in which this is to be performed though. detectWeb() and all other functions in the translator take a "doc" argument, which I figure is the document object for the page that the user is viewing. Do how can I use those functions on another document? Or am I misunderstanding something here…

As a totally of topic (for this repository anyhow, but not to my predicament) side note, for anybody interested: we have actually discovered that Koha does have an export feature that would fit our needs, documented [here](https://koha-community.org/manual/17.11/en/html/03_tools.html?highlight=export#export-bibliographic-records), but in the case of our specific implementation, seems to have been deactivated by the developers (it simply doesn't show up in the tools where it should, and the documentation leaves no hint as the how this might be fixed).

**Comment by zuphilip** [comment]
I think you are looking for `ZU.processDocuments`. Try to start with something like this (not tested):
```js
function doWeb(doc, url) {
	if (detectWeb(doc, url) == "multiple") {
		var resultPages = ZU.xpath(doc, '//*[contains(@class, "pagination")]/ul/li/a');
		for (let i=0; i<resultPages.length; i++) {
			ZU.processDocuments(resultPages[i].href, function(newDoc) {
				scrapeAll(newDoc, resultPages[i].href);
			}
		}
	} else {
		scrape(marcURL(url));
	}
}

function scrapeAll(doc, url) {
	var allResults = getSearchResults(doc);
		var articles = [];
		for (var i in items) {
			articles.push(marcURL(i));
		}
		scrape(articles);
	});
}
```

**Comment by adam3smith** [comment]
This isn't something we'd put into Zotero itself -- I hope the above exchange was helpful. Closing this issue
