### ISSUE TITLE
Failed to download pdf attachment from thecvf.com

### ISSUE THREAD

**Issue by zepinglee** [zotero/translators#1569]
I'm trying to save an item (a CVPR paper) from http://openaccess.thecvf.com/content_cvpr_2017/html/Qi_PointNet_Deep_Learning_CVPR_2017_paper.html and I confirm the direct access of the pdf file. But the zotero connector failed to download the pdf attachment.

Does anyone know which translator is called when I'm accessing thecvf.com?

**Comment by zuphilip** [comment]
By hovering over the Zotero symbol you see that "Embedded Metadata" translator is used and you can also see more options by a right click on that symbol.

The problem with your example is that they provide an url for the pdf in their meta information, but it is not the correct one:

![meta-pdf](https://user-images.githubusercontent.com/5199995/36887405-6553af4e-1df1-11e8-902d-d21163cfe306.png)

Opening this url http://openaccess.thecvf.com/openaccess/content_cvpr_2017/papers/Qi_PointNet_Deep_Learning_CVPR_2017_paper.pdf leads to 404 error (the url part `openaccess/` should be deleted). Contact them and ask them to correct it.

**Comment by zepinglee** [comment]
@zuphilip Thanks a lot!
