### ISSUE TITLE
Google Scholar: Prevent duplicate PDFs

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1575]
https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=HYBRID+WAR%3A+NATURE+AND+STRUCTURE+OF+THE+PHENOMENON&btnG=

Imports the PDF on the side and then takes a snapshot of the linked page, which is the same PDF. We shouldn't do this. Options:
1.) Don't take a snapshot
2.) Don't take a snapshot where it's identical to the PDF

I'd be inclined to say let's get rid of the GS Snapshot entirely, but I'm open to either option

**Comment by zuphilip** [comment]
I would vote for 2.) because there are also cases where you don't have access to a PDF version and thereby to have a snapshot of the article page can give you more information, e.g. also the abstract, which will be considered during search everything in Zotero.

**Comment by fredericky123** [comment]
I would vote for 1.) I really do not need snapshot and every time the automatic snapshot annoys me.
Or we can have a option button to customize by ourselves. 
Thanks a ton!

**Comment by sdspieg** [comment]
The customizing option sounds the most appealing to me too. But yes, I'd also pick the second option, if possible

**Comment by zuphilip** [comment]
Related https://forums.zotero.org/discussion/comment/304211#Comment_304211

**Comment by zuphilip** [comment]
Another related post: https://forums.zotero.org/discussion/71376/how-can-i-insert-items-from-google-scholar-using-save-to-zotero-without-snapshot

**Comment by fredericky123** [comment]
how about the recent progress? @adam3smith

**Comment by AbeJellinek** [comment]
Fixed by 217d9dae691472bd27ab42138375c94de7e88335.
