### ISSUE TITLE
Add support for Peeters Online Journals

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1582]
* All journals: http://poj.peeters-leuven.be/content.php
* Journal page for "Ethical Perspectives": http://poj.peeters-leuven.be/content.php?url=journal&journal_code=EP
* Issue page: http://poj.peeters-leuven.be/content.php?url=issue&journal_code=EP&issue=4&vol=24
* Article page: http://poj.peeters-leuven.be/content.php?url=article&id=3269043&journal_code=EP

No metadata, no export format but there is a DOI (mEDRA). However, content negotiation with mEDRA did not work for me here and I could only find access to the metadata through their webinterface, e.g. https://www.medra.org/servlet/view?lang=en&doi=10.2143/EP.24.4.3269042 . -> Thus, I guess it is okay to not consider that further and make a pure web scraper here with the information shown on the website.

**Comment by zuphilip** [comment]
Another relevant journal is "Lumen Vitae": http://poj.peeters-leuven.be/content.php?url=journal&journal_code=LV

**Comment by zuphilip** [comment]
@socheres works on this

**Comment by socheres** [comment]
other peeters theological journals
http://ld.zdb-services.de/resource/2147927-6
http://ld.zdb-services.de/resource/2148229-9
http://ld.zdb-services.de/resource/2226043-2
http://ld.zdb-services.de/resource/2210133-0
http://ld.zdb-services.de/resource/2145018-3
http://ld.zdb-services.de/resource/2854158-3
http://ld.zdb-services.de/resource/2755689-X
http://ld.zdb-services.de/resource/2161415-5
http://ld.zdb-services.de/resource/2148260-3
http://ld.zdb-services.de/resource/2690210-2
http://ld.zdb-services.de/resource/2239608-1
http://ld.zdb-services.de/resource/2194032-0
http://ld.zdb-services.de/resource/2910281-9

**Comment by adam3smith** [comment]
Closed in https://github.com/zotero/translators/pull/1606
