### ISSUE TITLE
WSJ: Remove timestamp in Date field

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1586]
https://forums.zotero.org/discussion/70789/reformat-date

**Comment by zuphilip** [comment]
The example https://www.wsj.com/articles/george-costanzas-investment-tips-1520800111 results with `2018-03-11T20:28:00.000Z` for me. This seems correct and I am not sure what to do here...

There are much more cases where we have also a time in the date field. Should they all be deleted?

**Comment by dstillman** [comment]
Oh, no, sorry. Maybe the "T00:00:00+0000" was just meant as an example. Asking for clarification.

**Comment by owcz** [comment]
This was resolved in the thread. The user was asking why Z captures the time data if we never plan to use it.
