### ISSUE TITLE
Directory of Open Access Journals

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1590]
Single: https://doaj.org/article/0006d8f8ca3e4af1b3ec14a07e88bb12
Multiple: https://doaj.org/search?source=%7B%22query%22%3A%20%7B%22query_string%22%3A%20%7B%22query%22%3A%20%22testing%22%2C%20%22default_operator%22%3A%20%22AND%22%7D%7D%7D#.Wqf4budG1aS

Pages have embedded metadata, so should be easy. Might be worthwhile trying to get the PDFs where they're directly linked as in the example above, but obviously not a must.

**Comment by zuphilip** [comment]
Related forum post is here: https://forums.zotero.org/discussion/70508/translator-request-doaj
