### ISSUE TITLE
customize url to achieve pdf from Google Scholar

### ISSUE THREAD

**Issue by fredericky123** [zotero/translators#1598]
How can we customize the url, for example, Sci-Hub, to achieve pdf automatically in the Google Scholar translator?
Thanks a lot!

**Comment by dstillman** [comment]
Please post feature requests and bug reports to the <a href="https://forums.zotero.org">Zotero Forums</a>.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/59199/sci-hub-as-backfall/p1

**Comment by fredericky123** [comment]
Alright, thanks. Actually, I have notice the post before, I want to use Sci-Hub as default search engine because sometimes the pdf from Google is a working paper.
