### ISSUE TITLE
Nature Publishing Group: detects PDF pages and fails to save

### ISSUE THREAD

**Issue by adomasven** [zotero/translators#1599]
Reported here https://forums.zotero.org/discussion/70939/unable-to-download-pdf-with-chrome-connector

**Comment by zuphilip** [comment]
I don't have access to this journal and therefore the failed pdf save is expected (also the detection of pdf in the first place is not correct). But it seems that the problem in the forum was different. Was there anything in these logs @adomasven ?

**Comment by adomasven** [comment]
The user reported 2 issues here (although they thought it was the same one). One was to do with proxies and one with the translator detecting on PDF pages.

So this url (http://www.nature.com.[proxy]/articles/s41593-018-0104-6.pdf) both matches the target regexp and finds something valid to return "article" from `detectWeb()`

**Comment by zuphilip** [comment]
I guess it is much better not to try to scrape on PDFs here for nature publishing group with the translator, because by saving the pdf we can now also automatically detect the metadata. Do you agree?

We could exclude pdfs from detection by something like
```js
function detectWeb(doc, url) {
   if (url.endsWith(".pdf")) {
      return false;
   }
   ...
```

Would this solve the issue here?

**Comment by adomasven** [comment]
Well, the scraping with the translator doesn't even work in the first place, it just throws an error. The fix proposed should work.

**Comment by zuphilip** [comment]
See #1605

**Comment by zuphilip** [comment]
Merged. @adomasven Can we close the issue here or is there more to do?

**Comment by adomasven** [comment]
Seems to work well. Thanks!
