### ISSUE TITLE
The Intercept translator doesn't snapshot the page

### ISSUE THREAD

**Issue by louy2** [zotero/translators#1603]
The Intercept translator for some reason doesn't snapshot the page. Tested on https://theintercept.com/2018/03/20/puerto-rico-hurricane-maria-recovery/

**Comment by owcz** [comment]
This is by design, as the Snapshot function didn't work with the site's contents:
https://github.com/zotero/translators/pull/1365/files#diff-247fad8e81d45fc7e76ba7149becbf74R61

**Comment by owcz** [comment]
@zuphilip If it works for you, go for it! I only disabled that line because the same was done on my other translators whose snapshots also failed
