### ISSUE TITLE
Wiley translator is failing sometimes

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1608]
E.g. https://onlinelibrary.wiley.com/doi/abs/10.1002/ece3.1637 see https://forums.zotero.org/discussion/comment/304591#Comment_304591

**Comment by AEgit** [comment]
I can confirm that Wiley publications are currently not working/imported properly, e.g.:
https://onlinelibrary.wiley.com/doi/full/10.1111/afe.12283

The Wiley translator is failing and Zotero is falling back to the "Atypon Journals" translator.

**Comment by Rekyt** [comment]
My workaround for the moment is to click on "Tools" then "Export Citations" and then I manage to get the Translator working.

**Comment by AEgit** [comment]
Hmm, as far as I can tell, this workaround does not solve the issue of the "Wiley translator" not working. You get the citation (but that was already the case before with the "Atypon Journals" translator) but it is not based on the "Wiley translator" which causes issues (certain fields are missing from the import and the PDF is also not automatically downloaded).

**Comment by zuphilip** [comment]
Fixed with 34e3eba9f94e9df70cb768be320b7fe167c5a91f.

**Comment by AEgit** [comment]
Cheers - I guess this patch still needs to make it into the master build (?).

**Comment by zuphilip** [comment]
@AEgit No, it was merged here 3 days ago and the deployment of the updated translators is independent of the updates for Zotero itself. Your Zotero Connector should auto-update within 24 hours, or you can update manually by clicking Update Translators in the Advanced pane of the Zotero Connector preferences.

**Comment by AEgit** [comment]
Ah yes, now, indeed, it appears to work. I tried it a couple of days ago and then the patch didn't seem to be applied. Thank you very much!
