### ISSUE TITLE
Idref translator not working in Firefox, ok in Scaffold

### ISSUE THREAD

**Issue by symac** [zotero/translators#1610]
This has been discussed in the pull request that created the translator : https://github.com/zotero/translators/pull/1545
The issue is that detectweb is working fine when tested from scaffold, but with the Firefox connector, the icon does not show up (well it appears sometimes but not always). @adam3smith confirmed on the PR comment, I am adding this issue so that we don't forget it and maybe someone will have more idea about it.

**Comment by symac** [comment]
@adam3smith this issue is still pending and I don't have any clue on the best way to fix this. Do you have any idea if something currently being worked on in Zotero might be leading to a solution or if something could be done on idref.fr site ? I'm in contact with them so if you have any clue, I can forward to them.

Thanks, 
Sylvain

**Comment by Francois-Mistral** [comment]
Hello @adam3smith,
would you have any idea to fix this issue : it's so close to work, that it's a shame !
Your help would be really appreciate.
Best regards
François

> 
> @adam3smith this issue is still pending and I don't have any clue on the best way to fix this. Do you have any idea if something currently being worked on in Zotero might be leading to a solution or if something could be done on idref.fr site ? I'm in contact with them so if you have any clue, I can forward to them.
> 
> Thanks,
> Sylvain

**Comment by symac** [comment]
Coming back to this issue it appears that it is because of the getSearchResults that is called from detectWeb. In fact when using scaffold, this function is fired when the developer is clicking on the eye icon, and at this time, usually, the asynchronous loading of the result lists is finished so it is working fine.
But when Firefox runs detectWeb, the result list on [an idref record](https://www.idref.fr/199676100) is still loading and getSearchResults returns false.

This detect issue seems to be fixed by replacing detectWeb by replacing:

```javascript
function detectWeb(doc, url) { 
	if (ZU.xpathText(doc, '//div[@class="detail_bloc_biblio"]') && getSearchResults(doc, true)) {
		return "multiple";	
	}
}
```

by:

```javascript
function detectWeb(doc, url) { 
	if (ZU.xpathText(doc, '//div[@class="detail_bloc_biblio"]')) {
		return "multiple";	
	}
}
```

The only remaining issue is if the user clicks on the folder icon before the result list is fully loaded. I am not sure it will often happen in real life but I'd like to be able to find a proper solution to fix it. The best one I have found so far is to add at the beginning of the doWeb function the following code:

```javascript
	searchResultsReady = getSearchResults(doc, true);
	if (!searchResultsReady) {
		var timeout = Date.now() + 5000;
		while (Date.now() < timeout){}
	}
```

It will add a delay of 5 seconds in case the user is clicking on the icon too early before the result list is loaded. It's far from perfect but it should fix most problematic cases.

I will leave that there for a while in case anybody has better advice to fix this, then I will propose a PR based on these ideas.

**Comment by adam3smith** [comment]
Haven't looked at this for a long time, but is there a reason `ZU.monitorDOMChanges` wouldn't be an option? That's much better than a timed delay, which can be annoying _and_ unreliable.

**Comment by symac** [comment]
@adam3smith I have read somewhere that ZU.monitorDOMChanges was available only for detectWeb and our current issue is with doWeb. DetectWeb can return multiple without waiting for the full list to be loaded, so we need a way to wait within doWeb in case user clicks quickly, but I have not found (yet?) a better solution than the while.

**Comment by symac** [comment]
The current proposed solution is available at 2aafdfb63e9f0c06f128787c360a9c7136aabc33 . As you will see, I have not been able yet to find a proper way to wait until the reference list is loaded. I have asked on [zotero-dev](https://groups.google.com/forum/#!topic/zotero-dev/vdWxs-1N_WA) in case someone has a good idea.

**Comment by symac** [comment]
@adam3smith : Following our discussion I have updated my fix to use the ```monitorDOMChanges```  in the detectWeb function. It takes a bit more time for the icon to load but at least we don't hang the user's browser. 

Please let me know if you've got any suggestion on the fix, I plan to open a PR next week if I haven't heard from you.

**Comment by zuphilip** [comment]
Thanks to @symac this is now fixed. The fix will be deployed within 24h to all Zotero users.
