### ISSUE TITLE
Highwire 2.0 wrongly detects multiples

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1615]
http://n.neurology.org/content/90/13/e1143.full
Reported here: https://forums.zotero.org/discussion/71180/neurology-org-translator#latest

**Comment by GuyAglionby** [comment]
The Neurology paper linked doesn't seem to have this issue anymore, but I'm still seeing a related problem with another HighWire journal here: https://www.pnas.org/content/114/13/3521. It's not quite the same -- the forum post describes the detected multiples as articles that the current one cites, while my issue is that the translator detects 'multiple' and only picks up only the letter in response to the article. If such letters aren't present, the translator works fine ([e.g.](https://www.pnas.org/content/116/52/26435))

**Comment by adam3smith** [comment]
I'm still seeing this issue for Neurolog and we also just got another report: https://forums.zotero.org/discussion/81301/zotero-connector-failing-on-neurology-journal-website

**Comment by AbeJellinek** [comment]
I can't reproduce this on any of the linked pages.

**Comment by adam3smith** [comment]
Not sure if this was due to the July 9 fix or otherwise fixed itself, but I cannot reproduce this anymore, so let's call it fixed.
