### ISSUE TITLE
newspapers.com no longer working

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1617]
@pbinkley, not sure if you're still relying on the newspapers.com translator, but there was a [report](https://forums.zotero.org/discussion/71358/saving-from-newspapers-com-giving-an-error) in the Zotero Forums that it's no longer working, probably due to a site change.

**Comment by zuphilip** [comment]
There is already a PR #1596 for updating this translator which I will merge now...

**Comment by dstillman** [comment]
Sorry, missed that.

Dupe of https://github.com/zotero/translators/pull/1596
