### ISSUE TITLE
The Globe and Mail - site updated, needs complete rewrite

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#162]

**Comment by sonali0901** [comment]
This issue was created in 2012, last visited in 2014.
The existing translator was updated in 2015.
The doWeb and detectWeb for the above example is still failing.
Can someone check it and let me know if this issue is still open?
I would like to work on it.

**Comment by adam3smith** [comment]
If the translator doesn't work currently, by all means, yes, please do work on it. Doesn't matter whether this ticket as originally created still applies; as long as Zotero doesn't work on the Globe and Mail, that's certainly worth fixing.
