### ISSUE TITLE
Some authors in amazon are imported as search,result

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1620]
https://www.amazon.co.uk/Semiotics-Basics-Daniel-Chandler/dp/1138232939/ref=sr_1_1?s=books&ie=UTF8&qid=1523547459&sr=1-1&keywords=semiotics

https://www.amazon.co.uk/Semiotics-Basics-Daniel-Chandler/dp/1138232939/ref=sr_1_1?s=books&ie=UTF8&qid=1523547459&sr=1-1&keywords=semiotics

Reported here:
https://forums.zotero.org/discussion/71424/chrome-connector-on-amazon-search-results-as-author#latest

**Comment by dstillman** [comment]
Duplicate of https://github.com/zotero/translators/issues/1527

PR available in https://github.com/zotero/translators/pull/1602
