### ISSUE TITLE
HeinOnline: Wrong output is saved after switching between chapters

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1639]
1. Search for "test" and click on the first result
2. Save the item
3. Click on another chapter on the left-hand side
4. Save again

The translator makes a new request for the second chapter's RIS, but the same RIS data is returned and the same info is saved twice. These two requests return the same data:

https://heinonline-org.[proxy]/HOL/CitationFile?handle=hein.hoil/polscevic0001&div=5&id=92&base=js

https://heinonline-org.[proxy]/HOL/CitationFile?handle=hein.hoil/polscevic0001&div=14&id=92&base=js

I don't know if this is a bug with their site or if the parameters here are no longer correct. I don't see a way to get RIS from the webpage in order to test that easily.

(Note that saving a second time won't be possible in 5.0.36 and later of the Zotero Connector until HeinOnline fixes their site, since they're [not updating the URL correctly](https://forums.zotero.org/discussion/comment/307383/#Comment_307383).)

**Comment by fbennett** [comment]
(In the URLs you quote above, div= is just a counter that increments with each transaction in the session, and doesn't seem to affect the delivered RIS.  The critical value is id=, which identifies the location in the ToC. That is available in the page on an element with id pageSelect.)

**Comment by zuphilip** [comment]
This seems to be fixed and therefore I close this. If the problem persist for you, then feel free to open this issue again or start with a new one.
