### ISSUE TITLE
Globe and Mail Citations

### ISSUE THREAD

**Issue by mparrault** [zotero/translators#1658]
I don't know if this is an issue with Zotero or somewhere else on the stack, but citations for the Globe and Mail don't populate properly in the Visual Editor in Wikipedia.  For instance, for the test case article "https://www.theglobeandmail.com/news/toronto/doug-ford-says-hes-not-yet-sure-about-his-political-future/article21428180/" all that is returned is the article title and access date (see screenshot below).
![screenshot 2018-05-13 08 42 00](https://user-images.githubusercontent.com/39238548/39967478-bbacc2ba-5689-11e8-95cf-b853cfc699fd.png)
The issue would appear to be with The Globe and Mail.js.

**Comment by dstillman** [comment]
Current output from translation-server:

```json
[
  {
    "key": "L8KLK7H4",
    "itemType": "newspaperArticle",
    "creators": [],
    "tags": [
      {
        "tag": "Rob Ford, John Tory, Jim Flaherty, Ontario Progressive Conservative, Christine Elliott, Doug Ford, leadership",
        "type": 1
      }
    ],
    "url": "https://www.theglobeandmail.com/news/toronto/doug-ford-says-hes-not-yet-sure-about-his-political-future/article21428180/",
    "title": "Doug Ford to decide provincial Tory leadership run in 'a couple weeks'",
    "abstractNote": "He says he will decide soon about whether to run for Ontario Tory leadership and does not rule out another attempt at the Toronto mayoralty",
    "libraryCatalog": "The Globe and Mail",
    "accessDate": "2018-05-13T16:53:44Z"
  }
]
```
This seems to have regressed since the test case (which also didn't include Publication to begin with).

**Comment by zuphilip** [comment]
The translator evaluate the microdata, which is not anymore in that page. Instead I see some JSON-LD data, which could be taken for saving the metadata.
