### ISSUE TITLE
Most newspapers.com variables no longer map

### ISSUE THREAD

**Issue by skylerbunny** [zotero/translators#1665]
I suspect the testing done for newspapers.com clippings, if it's running at all, isn't doing an exhaustive check of what it's supposed to be. In any event, it looks like 'what it grabs' is out of date, because the code refers to fields that have changed names or are no longer there, and most fields the code seems to expect it should autofill don't.

If I attempt to clip one of the test cases in the code using the current VisualEditor on Wikipedia, what I get is this in the autofill for citation fields:

URL: https://www.newspapers.com/clip/18535448
Source title: Clipping from The Sunday Leader - Newspapers.com
Name of publication: Newspapers.com
URL Access Date: 2018-05-26
Language: en

Ideally it would be good if it got _at least_ this (never minding the 'You COULD get the proper title and author if it's formatted in the title correctly' thing, because that relies on the person clipping it to know you have to do that):
URL: https://www.newspapers.com/clip/18535448
Source title: Clipping from The Sunday Leader
Name of publication: The Sunday Leader
URL Access Date: 2018-05-26
Source date: 1887-06-17
Language: en
Page/Pages: 5
Via: Newspapers.com
Location of Publication: Wilkes-Barre, Pennsylvania
Edition: Main Edition

If and when this is fixed, if periodic tests run, they probably want to raise flags if one or more fields drop or change.

**Comment by adam3smith** [comment]
This works with Zotero (as in: the item imports as in the text), so something going wrong on the citoid end. Might just be that they haven't updated the translator after the latest fix; I don't think that happens automatically.

> If and when this is fixed, if periodic tests run, they probably want to raise flags if one or more fields drop or change.

That is the case already.
