### ISSUE TITLE
https://www.newspapers.com/image/* links probably want to be denied

### ISSUE THREAD

**Issue by skylerbunny** [zotero/translators#1666]
I just discovered this while trying to dig for just how citation autocompletions work (and realized it's here, thus the previous bug filed for autofill field failures):

https://en.wikipedia.org/wiki/Wikipedia:Newspapers.com

"Both Newspapers.com and The Wikipedia Library would prefer that articles citing Newspapers.com link to clippings. Clippings allow Newspapers.com subscriber-editors to identify particular articles, extract them from the original full sheet newspaper and share them through unique URLs. Thus readers who click on a Newspapers.com Clipping link will be able to access that particular article, and the full page of the paper _if they come from the clipping_, without needing to subscribe to Newspapers.com. Clippings can be deleted by the user who created the clipping, but otherwise remain permanently open access, even when user accounts expire. For more information about how to use clippings..."

This probably means that there should be a citation parsing check that, if a user attempts to automatically cite a URL beginning with https://www.newspapers.com/image, that the request should be _denied_, and explanatory text, 'Please create a clipping of the article you wish to cite on newspapers.com, then paste the URL for the clipping here'. (Maybe adding 'See `<url>` for why.') _Clippings_ begin with https://www.newspapers.com/clip , so it would always bypass that check, as it should.

I've been doing linking to newspapers.com page images for years using zotaro's autofill, and had no idea it wasn't ideal, nor why, and that there is a better way.

**Comment by adam3smith** [comment]
Zotero is an independent project. It's main purpose is being a standalone reference manager. It just happens to run as the backbone of Wikipedia's visual editor's citation function.

Any functionality that's specific to Wikipedia (such as this) shouldn't be reported here.
