### ISSUE TITLE
Missing Year (Wiley)

### ISSUE THREAD

**Issue by CodaP** [zotero/translators#1674]
Wiley translator not parsing year, because BibTex does not contain year.
(RIS does though)

(@zuphilip, looks like you changed from RIS to BibTex in  #1624)

Examples:
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2003GB002079
https://rmets.onlinelibrary.wiley.com/doi/abs/10.1002/joc.3370050202
https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2007JD008809
https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2012JD017915

**Comment by adam3smith** [comment]
We're aware of this and it's been reported to Wiley -- we'll monitor and put in a stop-gap fix if need be, but it's really their error to fix.

**Comment by CodaP** [comment]
Ok, I've reported to Wiley Online Library

**Comment by adam3smith** [comment]
From Wiley:
"Thank you for your recent communication regarding for some days now the bibtex (Tools --> Export Citation --> BibTeX) is missing publication date and year, even though they're present in other formats.

Please be advised that this is a known issue which we are currently working to resolve. 
"

**Comment by zuphilip** [comment]
AFAIS only in some journals from Wiley is the year missing in the BibTeX. In most cases the year is present in the BibTeX. Let us hope Wiley can solve the issue soon.

**Comment by florisvdh** [comment]
As far as I can see, this issue is still present (after clicking the Zotero connector in the browser). I did not find a Wiley journal where the problem does not occur.

**Comment by zuphilip** [comment]
The date is AFAIS now saved in Zotero for all of the examples above. However, the information is not yet part of the BibTeX format. I rather guess that it is taken now from some embedded metadata.

**Comment by florisvdh** [comment]
Indeed, this now works! BTW I asked the people at Wiley about this problem on 27 July. On 20 August they responded 'We are currently working on having this fixed.'. So it appears that they did the job well.
