### ISSUE TITLE
Both the volume and issue are save in issue in CNKI

### ISSUE THREAD

**Issue by redleafnew** [zotero/translators#1686]
Both the volume and issue are save in issue field as 03 vo 48 in CNKI, and the volume field is empty when I import citation in www.cnki.net or http://epub.cnki.net/kns/default.htm such as this site: http://www.cnki.net/KCMS/detail/detail.aspx?QueryID=7&CurRec=1&filename=NYJX201703043&dbname=CJFDLAST2017&dbcode=CJFQ&pr=&urlid=&yx=&v=MzA1NDc0SDliTXJJOUJaNFI4ZVgxTHV4WVM3RGgxVDNxVHJXTTFGckNVUkxLZllPWnJGaTdoVXIvS0t6VEJkckc=
![_20180704075131](https://user-images.githubusercontent.com/22135631/42249667-18af21bc-7f5f-11e8-8064-fa5669a9d7a8.png)

**Comment by zuphilip** [comment]
Fixed in #1740.
