### ISSUE TITLE
EBSCOhost issue with RIS T2 field

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1700]
Not sure if this RIS issue is on our end or EBSCOhost's

Here is the RIS from an article: 
```
TY  - JOUR
T1  - Ruts and peaks.
T2  - Venice's biennial exhibition
JO  - Time
JF  - Time
J1  - Time
PY  - 1952/07/28/
Y1  - 1952/07/28/
VL  - 60
M3  - Article
SP  - 48
EP  - 49
SN  - 0040781X
KW  - Biennale di Venezia (1952)
N1  - Accession Number: 514000886; Physical Description:Illustration; Subject: Biennale di Venezia (1952); Number of Pages: 2p; Record Type: Article; Language: Undetermined
UR  - http://search.ebscohost.com/login.aspx?direct=true&db=air&AN=514000886&site=ehost-live
DP  - EBSCOhost
DB  - air
ER  - 
```

The article was published in _Time_, but Zotero imports the publication title as "Venice's biennial exhibition" ([T2](https://en.wikipedia.org/wiki/RIS_(file_format)#Tags)), which EBSCOhost lists as the article's "alternative title" (subtitle?)

Is this something we should patch or just bad data to write EBSCOhost about?

**Comment by adam3smith** [comment]
It's strictly speaking incorrect RIS but I think it's not that
unreasonable, we can work around it in the EBSCO translator

**Comment by owcz** [comment]
Shouldn't the RIS translator prefer J0/JF/J1 as the journal publication title before T2?

**Comment by adam3smith** [comment]
No, those are made up fields. The fields from the RIS specs are extracted here: https://github.com/aurimasv/translators/wiki/RIS-Tag-Map
