### ISSUE TITLE
New ACL Anthology

### ISSUE THREAD

**Issue by nschneid** [zotero/translators#1702]
http://aclanthology.info/ a.k.a. http://aclanthology.coli.uni-saarland.de/ has replaced http://www.aclweb.org/anthology/, which will no longer index new publications.

The Embedded Metadata translator partially works for the new site, but it would be better to have a translator based on BibTeX, e.g. to distinguish conference and journal papers.

@GuyAglionby, thanks for #1577—would it be straightforward to adapt the ACLWeb translator to the new anthology?

**Comment by GuyAglionby** [comment]
Hey there. I suspect the new translator will be pretty straightforward to write. A lot of the complexity in the other translator handles cases where BibTeX is not available (e.g. [here](http://www.aclweb.org/anthology/Q/Q14/)), but this doesn't appear to be an issue on the new website (e.g. [corresponding](https://aclanthology.coli.uni-saarland.de/events/tacl-2014)). As such I'd probably just start from scratch -- shouldn't take long. Happy to do this but will have to be late next week. Thanks!

**Comment by Evpok** [comment]
<http://aclweb.org/anthology> is now claiming it is the latest version of ACL anthology and the exporter is not doing well there (e.g. failing to pick up the venue). Are there any plans to support this version?

**Comment by nschneid** [comment]
In light of https://github.com/acl-org/acl-anthology/issues/170#issuecomment-475883559, https://github.com/zotero/translators/blob/master/ACLWeb.js needs to be removed and https://github.com/zotero/translators/blob/master/ACLAnthology.js updated to work with the newest version of the site.

We are also waiting for #1797 to be merged.

**Comment by mjpost** [comment]
Thanks for working on this! If there are things the Anthology can do to facilitate integration please let us know. 

I’ll add that it might look like there’s a lot of churn with Anthology formats, but the recent static rewrite is the third version of the website (under http://www.aclweb.org/anthology) and should be stable for many years to come.

**Comment by Evpok** [comment]
Side note (and I'll open a separate feature request if suitable) : it would also be nice to be able to download the supplementary materials (appendix, posters, slides…). Is it possible from the translator side or should it be done in a full-fledged add-on?

**Comment by mjpost** [comment]
What would you need for this to happen? Additional fields in the BibTeX? Or a BibLaTeX file?

**Comment by nschneid** [comment]
I think the translator could retrieve these without modification to the Anthology .bib files, but @GuyAglionby would know better.

**Comment by Evpok** [comment]
@mjpost No, it would not really make sense to put this in the BibTeX, since technically these are separate documents (at least the slides and posters) that would require a separate bibliographic entry, i twould make more sense to get them in the translator and as far as I can see, the current structure of the anthology page is already enough for that :-)

**Comment by GuyAglionby** [comment]
Should be straightforward to grab the supplementary materials as @nschneid mentions. Looks like the kind of thing that would come under the `translators.attachSupplementary` hidden property ([here](https://www.zotero.org/support/preferences/hidden_preferences#translator_preferences), cc @adam3smith ?).

Only had a brief look so far but it looks straightforward to integrate with the new Anthology, so shouldn't require any changes but many thanks for the offer @mjpost.

**Comment by nschneid** [comment]
Also, the current translator is not recognizing `\aa` in https://www.aclweb.org/anthology/E17-2069.bib

**Comment by nschneid** [comment]
The new bib format has curly braces protecting capital letters in titles, e.g. https://aclweb.org/anthology/papers/E/E17/E17-3006.bib

Is it possible to have the importer sentence-case titles, respecting the fixed capital letters? Just in the title field, not the booktitle.

**Comment by adam3smith** [comment]
Technically possible, yes, but I think it may well require a custom function.

**Comment by GuyAglionby** [comment]
#1937 fixes the issue with the ring diacritic. I'm happy to sentence-case the titles if that seems reasonable @adam3smith -- I'm not sure what standard is here. (@nschneid -- is this related to the discussion on the Anthology issue tracker out of curiosity?)

**Comment by nschneid** [comment]
https://github.com/acl-org/acl-anthology/issues/123 has the gory details.
