### ISSUE TITLE
TEI.js > Generate IDs: xml invalid for @xml:id and <imprint/>

### ISSUE THREAD

**Issue by oriflamms** [zotero/translators#1704]
In exporting a library into TEI format, I get three different errors: 

1) `value of attribute "xml:id" is invalid; must be an XML name without colons`
corresponding to the presence of apostrophes  (either " ' " or  " ’ ")  in author names such as "Gerard O’Daly"
I would suggest to deal specifically with those two signs into lines 122, 123 (xmlid = xmlid.replace)

2) `element "imprint" incomplete; expected element "biblScope", "catRef", "classCode", "date", "distributor", "pubPlace",  "publisher" or "time`
corresponding to the exported
`<imprint><!--  no publisher, publication date or place given  --></imprint>`
Obviously an incentive to search for the information, but not always feasible. 
I would suggest to export empty elements
`<pubPlace/><publisher/><date/>`

3) `element "note" not allowed yet; expected element "biblScope", "catRef", "classCode", "date", "distributor", "pubPlace", "publisher" or "time"`
in monographs that have no place nor date, but a URL
The suggested solution for point 2 solves also this one.

**Comment by adam3smith** [comment]
sorry, what tool exactly is throwing those errors?

**Comment by oriflamms** [comment]
My xml editor is Oxygen

**Comment by adam3smith** [comment]
that all sounds right. If you'd be willing ot turn this into a pull request, that'd be very helfpul. It'd probably take some time for me to get around to doing this myself.

**Comment by oriflamms** [comment]
Thanks for your incentive. Done.
However, I could not fix the fact that authors in single mode are not exported. I've tried with 
`if (item.creators[i].fieldMode == true) { // fieldMode true, assume corporate author
surname = teiDoc.createElementNS(ns.tei, "name");
surname.appendChild(teiDoc.createTextNode(item.creators[i].firstName));
curCreator.appendChild(surname);
}`
and also lastName, but this is not working and I haven't found a solution. Do you want me to open another issue? If you give me a hint, I'll test it and do another pull request.

**Comment by adam3smith** [comment]
Thanks for working on this. I didn't actually know this myself, but items with `fieldMode == true` are returned by Zotero as `{ "name": "Singlefield" "creatorType": "author" }` (I found this out by putting `		Z.debug(item.creators[i])` into the loop for the authors), i.e. `if (item.creators[i].name)` should work.

**Comment by adam3smith** [comment]
and feel free to wrap this into the same pull request if you don't mind.

**Comment by oriflamms** [comment]
Great! Thank you for your help. Works perfectly.

**Comment by adam3smith** [comment]
Closed a while back in https://github.com/zotero/translators/pull/1705
