### ISSUE TITLE
Sydney Morning Herald - site changed; requires rewrite

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#171]
We should probably write a translator for Fairfax Media, since there are several news sites that use this content delivery suite.

See http://www.fairfax.com.au/network-map.aspx for a list of sites

**Comment by zuphilip** [comment]
The Sydney Morning Herald was replaced a more generic translator for fairfax, see #1159 and https://github.com/zotero/translators/commit/7bf7f5cc288152e8e8fbaa8e122e1d225a192cc9.
