### ISSUE TITLE
CI: Change to ESLint

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1718]
We are using currently JSHint but could move to ESLint. This would allow us to check some more code styling things like [keyword-spacing](https://eslint.org/docs/rules/keyword-spacing), see also https://github.com/zotero/translators/pull/1711#discussion_r211100521

**Comment by dstillman** [comment]
Definitely. We haven't up eslint for zotero/zotero yet, but it's planned, and we use it for a number of other repos.

(And an incredibly strong agree on keyword-spacing.)
