### ISSUE TITLE
MARCXML import breaks when a subfield is empty

### ISSUE THREAD

**Issue by bencomp** [zotero/translators#1722]
I see this error in the console when I look at a Code4Lib Journal article:

```
10:41:44.868 TypeError: sf is null at moz-extension://c83442f6-3b5a-c342-995b-817efcb1fc4d/inject/translate_inject.js line 63 > eval:67 zotero.js:297:4
```
Using the debug log I found that the Code4Lib Journal translator was broken (see #1721) and that Zotero tries to use the MARCXML translator on the unAPI MARCXML output. [This output](https://journal.code4lib.org/wp-content/plugins/unapi/server.php?id=https://journal.code4lib.org/?p=13671&format=marcxml) contains an empty (string in a) subfield: `<marc:subfield code="a"></marc:subfield>`, which I guess is the reason `sf is null` in:

https://github.com/zotero/translators/blob/2d3e4bdbaa217b31eee10591e84d6afb0cd2efb2/MARCXML.js#L64-L67

All other subfields contain text.

I don't know for sure if this is an error on the Code4Lib Journal side – empty tags don't add value, but I don't know if they are forbidden. Perhaps the translator should be aware of and resistent to empty subfield elements?

**Comment by adam3smith** [comment]
yup, thanks, I have a fix for this,  coming shortly

**Comment by adam3smith** [comment]
closed via https://github.com/zotero/translators/commit/e234d966ccf6c39063f605739507c7bd2ea3e0d5
