### ISSUE TITLE
mistakes in cnki.js

### ISSUE THREAD

**Issue by fredericky123** [zotero/translators#1727]
when I save items from cnki, it will be like this:
![image](https://user-images.githubusercontent.com/13982749/44772200-ca7adf00-ab9f-11e8-9d17-691f9a10936f.png)
however, it should be **Volume:16 Issue:03**
The mistakes exists for all items saved from cnki
http://www.cnki.net/

**Comment by zuphilip** [comment]
Fixed in #1740.
