### ISSUE TITLE
PDF download missing for Nature Scientific Data

### ISSUE THREAD

**Issue by quazgar** [zotero/translators#1763]
When trying to save this (pretty famous) OpenAccess article on Nature Scientific Data, only a snapshot for the web page is saved (as item type `web page`), not the PDF version of the article: https://www.nature.com/articles/sdata201618

Downloading articles from other sites, e.g. Phys. Rev. E, works for me.

This is Zotero Connector 5.0.41 (Firefox) with Standalone 5.0.55 on Kubuntu 18.04 LTS.

**Comment by quazgar** [comment]
Or is this expected behaviour as per #1599?
@adomasven @zuphilip

**Comment by quazgar** [comment]
Screenshot to document the missing *Save* options:

![screenshot_20181011_134439](https://user-images.githubusercontent.com/302587/46802036-7f3a1b80-cd5c-11e8-8f9d-d5bff70e0761.png)

**Comment by adam3smith** [comment]
No, that's not right, thanks for reporting

**Comment by zuphilip** [comment]
Fixed in #1766 by @adam3smith.
