### ISSUE TITLE
Incomplete data from Crossref with Phys. Rev. articles

### ISSUE THREAD

**Issue by amilsted** [zotero/translators#1771]
Hi! I originally noticed this problem when importing references from arXiv.org. Where an arXiv article has a journal reference, Zotero pulls in the journal citation data via Crossref using a DOI lookup. Unfortunately, in the case of **Physical Review** journals (and perhaps others?), a critical piece of data - the **article id** - is ignored, leaving the citation data **incomplete**. The same problem occurs when importing directly from Crossref.

Here is an example:
Journal website: https://journals.aps.org/prd/abstract/10.1103/PhysRevD.98.014505 (complete citation)
arXiv: https://arxiv.org/abs/1604.01979 **(incomplete data)**
Crossref: https://search.crossref.org/?q=10.1103%2FPhysRevD.98.014505# **(incomplete data)**

A complete citation includes the following fields:
Publication: Physical Review D
Volume: 98
Issue: 1 (not required)
Article-ID: 014505 **<-- This is missing in the data pulled from Crossref!**
DOI: 10.1103/PhysRevD.98.014505
etc.

The Article-ID, which is usually stored in the "Pages" field in Zotero, is supplied in the "article-number" field in the Crossref metadata http://api.crossref.org/works/10.1103/PhysRevD.98.014505

**Comment by AbeJellinek** [comment]
Working now.
