### ISSUE TITLE
MDPI duplicates authors

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1773]
Reported here: https://forums.zotero.org/discussion/74354/enregistrement-depuis-la-plateforme-de-lediteur-mdpi-tous-les-auteurs-apparaissent-2x#latest

Example: https://www.mdpi.com/1420-3049/23/10/2454

authors are both in `citation_author` and in `citation_authors` -- need to decide if we'll just fix this in the MDPI translator (easy) or if this is worth addressing in EM (a bit harder)
@zuphilip do you have a view on this?

**Comment by zuphilip** [comment]
In the case that there are values for `citation_author` AND `citation_authors`, then it should be fine to just take one of this. The field `citation_author` seems to be more common. Thus, I would choose that one over the other.

Codewise I would suggest to change [the lines](https://github.com/zotero/translators/blob/fbb118b09b461e79ad01b77d5f86f627c7d28559/Embedded%20Metadata.js#L387-L388):
```js
	var authorNodes = getContent(doc, 'citation_author')
		.concat(getContent(doc, 'citation_authors'));
```
into

```js
	var authorNodes = getContent(doc, 'citation_author');
	if (authorNodes.length == 0) {
		authorNodes = getContent(doc, 'citation_authors');
	}
```

@adam3smith Do you agree?

**Comment by adam3smith** [comment]
Yes, thanks. Not just more common, but citation_author is more reliable (we don't have to rely on a comma split to identify individual authors and it can be use in lastname, firstname form). Can you put this into EM?

**Comment by zuphilip** [comment]
Oh, for MDPI only the `citation_authors` contain the initials. But we keep to generally prefer `citation_author` and only switch possibly for MDPI?
