### ISSUE TITLE
EEBO (Proquest) import fails

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1781]
Example: http://gateway.proquest.com/openurl?ctx_ver=Z39.88-2003&res_id=xri:eebo&rft_id=xri:eebo:citation:99847279

Reported: https://forums.zotero.org/discussion/74500/zotero-connector-not-working-for-eebo-entry#latest

**Comment by AbeJellinek** [comment]
EEBO is now handled by the main ProQuest translator and this issue no longer occurs.
