### ISSUE TITLE
Behaviour on github.com

### ISSUE THREAD

**Issue by caemor** [zotero/translators#1788]
The behaviour of the zotero connector while using it on any file on github seems a bit strange.
It's not saving the correct url where you are but instead just links the project.

So if you want to save some github.com/userB/projectA/draft/paper.md it always saves github.com/userB/projectA instead. Is there a way to circument that behaviour or does one need to manually add all links not going to linking to the root of the project?

**Comment by dstillman** [comment]
Can you provide a real example URL where this occurs, as well as a <a href="https://www.zotero.org/support/debug_output#debug_output_logging">Debug ID</a> from the Zotero Connector for a save that does this?

For me, the GitHub translator is failing and the connector is falling back to the Embedded Metadata translator, which just saves the current page normally.

**Comment by caemor** [comment]
e.g. https://github.com/mimblewimble/grin/blob/master/doc/intro.md

I can give you the debug id tomorrow when I'm back at work.

**Comment by dstillman** [comment]
Ah, sorry, I was trying on non-file pages, which fail as I mention above and fall back to EM. For file pages I'm seeing the behavior you describe.

From a quick look it doesn't seem like the translator ever had support for anything other than the project itself, so the quickest fix here, at least for now, is to just modify `target` to disable it for everything other than the project root and let EM handle other pages.

/cc @mfenner, the original author of the translator

**Comment by caemor** [comment]
That would be great. Thanks for your fast respone :-)

**Comment by katrinleinweber** [comment]
Hi @caemor :-) The beviour described above is still present. Has there been a decision to keep it that way, or was there another reason to close this? Thanks for infos!

**Comment by caemor** [comment]
I just looked through my old open issues and this one looked finished/done when I glanced over it but it seems like I was wrong :-D

**Comment by zuphilip** [comment]
I created a PR for this now.
