### ISSUE TITLE
Zotero Item Selector unchecked selections

### ISSUE THREAD

**Issue by akinhwan** [zotero/translators#1804]
As observed on Mozilla Firefox Quantum 60.4.0esr (64-bit)

When a user makes selections on the Search Results Page, then clicks on Zotero Extension to save, the Zotero Item Selector dialog window should show/remember what the user has selected on the page.

Please see https://github.com/zotero/translators/blob/master/PubMed.js#L176
Correct me if I'm wrong but either this was never the intended functionality, or it may have broken at some point. May not be a big issue, users could also just get used to the fact that they have to make their selections within the "Zotero Item Selector", which in that case I'm not sure what Line 176 is doing, because commenting it out doesn't break the getSearchResults function nor any tests.

![pubmed_search_results_multiple_unchecked](https://user-images.githubusercontent.com/10124722/50458476-6390eb00-0931-11e9-96ca-c0eeada31446.PNG)

**Comment by dstillman** [comment]
Thanks — fixed. The site structure changed, so the checkboxes weren't being found.

Your Zotero Connector should auto-update within 24 hours, or you can update manually by clicking Update Translators in the Advanced pane of the Zotero Connector preferences.

**Comment by akinhwan** [comment]
thanks dan I saw your code, my [Pull Request ](https://github.com/zotero/translators/pull/1801 )is still open however, so there is a[ merge conflict ](https://github.com/zotero/translators/pull/1801/conflicts) with your contribution.

**Comment by adam3smith** [comment]
I'll rebase that, don't worry about it.
