### ISSUE TITLE
Handling Dynamic (AJAX) Pages

### ISSUE THREAD

**Issue by TradeItEasy** [zotero/translators#1806]
I am currently looking into the new Espacenet Beta which loads patents from a previously loaded list of results. Espacenet updates the URL bar once you select a patent search result from the list and dynamically updates the site's content but Zotero does not recheck upon a URL change (at least in Chrome and Opera).

So is there any example/exisiting Translator that handles AJAX Pages where I could have a look at how to handle this properly?

**Comment by adam3smith** [comment]
Look at `Z.monitorDOMChanges` e.g. herehttps://github.com/zotero/translators/blob/master/Google%20Patents.js#L57

**Comment by TradeItEasy** [comment]
Ok, thanks for the hint! I will look into it...
