### ISSUE TITLE
NYT: Disable snapshots

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1807]
Saving a NYT page as "Webpage, Complete" from both Firefox and Chrome results in a broken page for me, and Zotero (which uses an earlier version of the Firefox saving code) is getting the same. If others are seeing the same, we should disable snapshots for now (unless we can figure out how to modify the local HTML file to get the snapshot to work).

Discovered from https://forums.zotero.org/discussion/comment/324175/#Comment_324175, though there are other problems there.

**Comment by adam3smith** [comment]
Seeing the same. 
The Snapshot comes automatically from the EM translator in this case. I think the easiest approach is to wipe th attachments at the beginning of translation so that the archive PDFs still get added.
