### ISSUE TITLE
ACM Digital Library Next version

### ISSUE THREAD

**Issue by javidcf** [zotero/translators#1811]
ACM is testing a beta of the new website for their digital library, hosted under https://dlnext.acm.org. See for example: [The status of the P versus NP problem](https://dlnext.acm.org/doi/10.1145/1562164.1562186).

It seems still incomplete, PDF links redirect you to the old version and I'm not sure if the new pages have all the information yet. However, I'm filing the issue to have it present in the backlog and, with any luck, maybe have the translator implemented before it gets out of beta.

**Comment by GuyAglionby** [comment]
The new version comes out of beta on 1 January, I'll see if I can get something together before then (unless anyone else has already made a start!).

**Comment by zuphilip** [comment]
I don't think anybody has started on this and therefore it would be perfect if you @GuyAglionby can work on this!

**Comment by anjiro** [comment]
Helpful for whomever works on this: you can get a dump of the metadata for a paper with just the DOI, which is in the URL for the paper itself:

https://dl.acm.org/action/exportCiteProcCitation?dois=10.1145/1562164.1562186&targetFile=custom-bibtex&format=bibTex

**Comment by GuyAglionby** [comment]
Thanks @anjiro!

**Comment by zuphilip** [comment]
For the reference: https://forums.zotero.org/discussion/80692/acm-dl-has-changed-zotero-connector-download-pdf-failed#latest

**Comment by zuphilip** [comment]
Fixed now thanks to @GuyAglionby !
