### ISSUE TITLE
BibTeX not working!

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1816]
Sorry, but something in the last hour caused that BibTeX export is not working anymore correctly. Can we immediately reset that? This is very urgent for me!

**Comment by zuphilip** [comment]
Error message is `extraFields is null` on line 1175

**Comment by zuphilip** [comment]
Ping @adam3smith

**Comment by zuphilip** [comment]
Seems to be #1814 I will revert that now...

**Comment by adam3smith** [comment]
Sorry about that, yes, definitely.

**Comment by zuphilip** [comment]
(We have an exam and using LaTeX + BibTeX + Zotero...)

**Comment by zuphilip** [comment]
If anyone wants to do a proper fix now, then please feel free to go on now again.

**Comment by adam3smith** [comment]
Closed via https://github.com/zotero/translators/commit/4a582614227c54e12893fd07a5fc5d65b4f71d28
