### ISSUE TITLE
Springer Link translator no longer working

### ISSUE THREAD

**Issue by kaymes** [zotero/translators#1822]
Since a few days (at least), the translator for Springer Link is no longer working. When I try to import a paper using the Zotero Connector, no reference appears in Zotero.

An example of a url that fails to import is https://link.springer.com/article/10.1023/B:DAMI.0000026904.74892.89

**Comment by adam3smith** [comment]
Works for me both with and without proxy. 
Please run through https://www.zotero.org/support/troubleshooting_translator_issues 
and post to the Zotero forums to follow up.

**Comment by kaymes** [comment]
@adam3smith Thanks for testing and sorry for bothering you. After you confirmed that it should work, I did some more digging and it turned out that it seems to be related to a new way of how Firefox blocks third-party cookies. With less aggressive blocking it works.

**Comment by adam3smith** [comment]
No bother at all. For future reference, we do bug triage on the Zotero forums and use the github tracker only for confirmed issues, so your first post should almost always be to the forums and not here.

**Comment by kaymes** [comment]
Thanks for letting me know, I didn't know this.
