### ISSUE TITLE
ProQuest: Clean URL

### ISSUE THREAD

**Issue by adunning** [zotero/translators#1899]
If I import an item from ProQuest, Zotero records a long, institutionally specific URL such as <https://search.proquest.com/pqdtglobal/docview/303056135/21BB9DC89DAC4F8EPQ/1?accountid=14771>. To have a stable URL that works from anywhere, however, all one needs is `https://search.proquest.com/docview/` plus the identifier, in this case <https://search.proquest.com/docview/303056135/>. It would be great if the translator could take care of this automatically.

**Comment by AbeJellinek** [comment]
We [do remove](https://github.com/zotero/translators/blob/480e65446eb5855184c71c3594a5193ac44b695a/ProQuest.js#L423) the `accountid` from the URL. IMO it's better to remove known unnecessary data from ProQuest's URL and risk returning an overly complex URL than to build our own with only known necessary data and risk returning a URL that doesn't work.
