### ISSUE TITLE
Check only modified files in CI

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1900]
Unless and until we go through all translators to fix linter errors ([which I'm in no rush to do](https://github.com/zotero/translators/pull/1838#issuecomment-469978240)), we're never going to have passing tests. It would be more useful (and it would certainly be quicker) to run ESLint only against the files modified in the commit range, so that we can rely on the checks on GitHub without having to check the output.

https://github.com/zotero/translators/pull/1895 probably needs to land first.

/cc @retorquere

**Comment by retorquere** [comment]
This is possible. It'd build on work in #1895 though, and I'm in no hurry to do cross-branch work given recent experience.

**Comment by retorquere** [comment]
I don't think it'd require any changes when #1895 is done; adding a script line like

```
"travis": "teslint `git diff --name-only $TRAVIS_COMMIT_RANGE | grep -v '\\/' | grep '\.js$'`",
```

and then calling `npm run travis` should do it.

**Comment by retorquere** [comment]
or just

```
npm run lint -- `git diff --name-only $TRAVIS_COMMIT_RANGE | grep -v '\\/' | grep '\.js$'`
```

in `.travis.yml` rather than `npm test`.
