### ISSUE TITLE
Linting: camelcase shows error no ns declarations

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1924]
See https://travis-ci.org/zotero/translators/builds/514447594#L477

The linting error is thrown for the arXiv translator on 

```
var ns = {
		oai_dc: 'http://www.openarchives.org/OAI/2.0/oai_dc/',
		dc: 'http://purl.org/dc/elements/1.1/',
		xsi: 'http://www.w3.org/2001/XMLSchema-instance',
		n: 'http://www.openarchives.org/OAI/2.0/' // Default
};
```
obviously that's not right. Not sure how to avoid this.

**Comment by dstillman** [comment]
Untested, but adding `/* eslint camelcase: ["error", { allow: ["oa_dc"] }] */` above that line should work.

**Comment by adam3smith** [comment]
Yes, that works, thanks!
