### ISSUE TITLE
Amazon: s=gateway in URL prevents detection

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1936]
Works:

https://www.amazon.com/Studies-Saiva-Siddhanta-Classic-Reprint-Nallasvami/dp/1333821387/ref=sr_1_1?keywords=saiva+siddhanta

Doesn't work:

https://www.amazon.com/Studies-Saiva-Siddhanta-Classic-Reprint-Nallasvami/dp/1333821387/ref=sr_1_1?keywords=saiva+siddhanta&s=gateway

Reported here: https://forums.zotero.org/discussion/77110/items-not-saved-properly-from-amazon-after-the-recent-update

Another report: https://forums.zotero.org/discussion/78461/i-cannot-add-titles-from-amazon

**Comment by zuphilip** [comment]
The parameter `s=gateway` will cause that the metadata in the website changes to
```
<input type="hidden" id="storeID" name="storeID" value="gateway">
```
and this value for `storeID` is usually the thing we analyze for detection, cf. https://github.com/zotero/translators/blob/ea64eab1c0d108699415913e97d20f32750adced/Amazon.js#L26 

This approach worked well so far also for different localization of Amazon.

I don't know how to fix the detection here.

**Comment by dstillman** [comment]
I can look into a better solution, but as a temporary fix, what about just requesting the URL without s=gateway and processing it normally?

**Comment by zuphilip** [comment]
I have found another solution without additional url call, see #1984.
