### ISSUE TITLE
Make Hyrax Institutional Repo "parsable" for the Zotero Connector

### ISSUE THREAD

**Issue by silviaegt** [zotero/translators#1939]
Hi there! 

Would love to know if there is a way to make our [institutional repository](https://github.com/ColmexBDCV/hyrax) "parsable" for the Zotero connector?
Our repo is similar to [this one](https://curate.nd.edu), and neither [lists](https://ir.library.oregonstate.edu/catalog?locale=en&q=mexico&search_field=all_fields) nor [singular items' metadata](https://ir.library.oregonstate.edu/concern/honors_college_theses/5h73pz07h?locale=en) is being parsed correctly
cc @adomasven @simonster

**Comment by dstillman** [comment]
https://www.zotero.org/support/dev/exposing_metadata

If you have further questions, please post to <a href="http://groups.google.com/group/zotero-dev">zotero-dev</a>.
