### ISSUE TITLE
EM/Bloomberg pulls author twice

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1947]
https://www.bloomberg.com/graphics/2018-tesla-burns-cash/

```html
<a class="dvz-t-hide" href="https://twitter.com/danahull" alt="@danahull" target="_blank" rel="noopener">Dana Hull</a>
<span class="dvz-t-show-inline" hidden="">Dana Hull</span>
```
Bloomberg translator uses EM, which pulls authors in the format "Dana HullDana Hull" since it reads the hidden text as well. EM should ignore the hidden text, no?

**Comment by AbeJellinek** [comment]
Seems to be fixed now.
