### ISSUE TITLE
Twitter translator: archive copy of tweet (and thread)

### ISSUE THREAD

**Issue by Guillawme** [zotero/translators#1948]
Hello there,

For regular webpages such as blog posts, Zotero can archive a copy of the page ("Save Webpage with Snapshot").

Would it be possible to add this functionality to the Twitter translator? This would be especially useful if we could navigate to the first tweet of a thread in the browser and then archive the entire thread in one click of the Zotero button. By entire thread I mean only the series of linked tweets by the author of the first tweet, not necessarily all the answers from other people (which is less relevant and changes as time passes anyway).

Many academics in my field use Twitter and post very relevant things, often as a thread of several tweets, but very few of them take the time to set up a conventional blog to make all their writings easily findable. I would love to be able to achive the full text of all this "grey literature", not only links to it (links might break as people clean up their twitter profiles, and offline access is always useful no matter what).

Thank you.

**Comment by shervinsafavi** [comment]
I also think it an extremely useful feature. I was wondering if there is any update regarding that?

**Comment by AbeJellinek** [comment]
As of https://github.com/zotero/translators/commit/f88f0348de6bb65f4e0cbfc5396731736a4370c4, this is now working fine.
