### ISSUE TITLE
Capitalization of abbreviation starting with a number for biblatex export.

### ISSUE THREAD

**Issue by knusch** [zotero/translators#1949]
Auto capitilization of capitalized words for biblatex export (i.e. insserting curly braces around the word), does not appear to work when the capitalized word starts with a number. My example was an article named 
3D intensity and phase imaging from light field measurements in an LED array microscope, 
which turns up in the .bib file as 
{3D intensity and phase imaging from light field measurements in an {LED} array microscope},
with no braces around the '3D' part. 

I have tested other abbreviations starting with a number, and it appears to behave the same in all my tests.

**Comment by zuphilip** [comment]
The extra spaces for preserving the uppercase letters in such cases comes from:
```js
var protectCaps = new ZU.XRegExp("\\b\\p{Letter}+\\p{Uppercase_Letter}\\p{Letter}*", 'g');
if (field != "pages") {
	value = ZU.XRegExp.replace(value, protectCaps, "{$0}");
}
```
which does not yet handle the cases with numbers as the `3D`. Moreover, in chemistry there are more examples like for example `MgO-FeO-Al2O3-SiO2-H<sub>2</sub>O`. We could extend this with the numbers by using instead
```js
var protectCaps = new ZU.XRegExp("\\b[\\p{Letter}\\d]+\\p{Uppercase_Letter}[\\p{Letter}\\d]*", 'g');
```
However, this would still leave the H<sub>2</sub>O case unchanged. But I am not sure, what is the desired output for this case anyway?

**Comment by zuphilip** [comment]
But this should be then combined with the issue #1667.
