### ISSUE TITLE
Add clinicaltrials.gov

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1952]
Multiple requests over the year, including here: https://forums.zotero.org/discussion/77721/add-reference-from-clinical-trials-org#latest

https://clinicaltrials.gov/ct2/resources/download#DisplaySingle 
has API-type information for getting to the XML

**Comment by rdvelazquez** [comment]
FYI - @ressy and I are going to take a look at implementing this in the next few days.

**Comment by rdvelazquez** [comment]
Another discussion about this: https://forums.zotero.org/discussion/74933/import-from-clinical-trials-registry
