### ISSUE TITLE
ACS: no PDF saved

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1966]
E.g. https://pubs.acs.org/doi/10.1021/acsomega.9b00642

See https://forums.zotero.org/discussion/77774/zotero-no-longer-imports-pdfs-from-acs-websites#latest and https://forums.zotero.org/discussion/comment/334360#Comment_334360

**Comment by zuphilip** [comment]
https://forums.zotero.org/discussion/77532/zotero-connector-not-downloading-pdf-from-pubs-acs-org#latest

**Comment by zuphilip** [comment]
The main problem should be solved with the already merged commit as a hotfix. However, there might be more issues with High Resolution PDF vs. PDF Plus with Links and possibly supplementary files.

**Comment by zuphilip** [comment]
The High Resolution PDF and PDF Plus seems to be gone, cf. https://twitter.com/MartinBraendle/status/1159415486448394240 but the supplementary files are still present. Thus, we can now simplify some code for the attachments.

But it seems that the PDF download is broken again: https://forums.zotero.org/discussion/79229/acs-journals-pdf-import-not-working#latest

**Comment by zuphilip** [comment]
@dstillman With the newest changes the hidden preference `translators.ACS.highResPDF` has now no function anymore. Is there anything one has to do for such a deprecated hidden Zotero preference? https://www.zotero.org/support/preferences/hidden_preferences

**Comment by AbeJellinek** [comment]
There's only one type of PDF available on the site now, PDF downloads work, and most people have probably forgotten about the old hidden pref, so I'm going to close this.
