### ISSUE TITLE
Twitter: broken after redesign

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1982]
I don't think this has rolled out for everyone yet (and many people are temporarily rolling back to the less-awful previous version), so we should support both versions if possible.

**Comment by zuphilip** [comment]
How is "rolling back" in Twitter working?

**Comment by dstillman** [comment]
Various temporary solutions: https://www.theverge.com/2019/7/26/8930770/how-to-old-twitter-web-interface-design-desktop-ui

**Comment by tfiers** [comment]
Fixed in #2054

**Comment by zuphilip** [comment]
Could we try the one trick with the useragent also for extraction of data, i.e. something like
```js
ZU.doGet(url, function (text) {
   var doc = DOMParser.parseFromString(text);
   scrape(url, doc);
}, null,  { "User-Agent": "Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko" });
```
? Do you think this would work?

**Comment by dstillman** [comment]
Fixed by https://github.com/zotero/translators/pull/2200
