### ISSUE TITLE
Researchgate papers shouldn't have their header

### ISSUE THREAD

**Issue by mirh** [zotero/translators#1994]
I know there \*is\* a way to straight away download articles without the very ugly cover page "brought to you by researchgate". 
I mean, I stumbled upon them plenty of times, even though I could never figure out the exact trick (are they checking the referer? some GET variable, or cookie?)

If that's not possible, eventually, would it be feasible to have the first page of pdfs get cut/split away?

**Comment by AbeJellinek** [comment]
Translators unfortunately don't have any way to modify downloaded PDFs. If you can find a request param that gets rid of the cover page, please submit a PR!

**Comment by mirh** [comment]
https://github.com/mrdro1/Biblio-Meter/blob/master/internet_resources/researchgate_old.py
https://github.com/kevinyu0506/researchgate-crawler/blob/master/src/spider.py
Who knows..
