### ISSUE TITLE
Springer books misses some fields

### ISSUE THREAD

**Issue by mirh** [zotero/translators#1996]
- [ ] Palgrave Macmillan
* see [here](https://www.palgrave.com/gp/book/9781137363152): basically everything is missing
(thrown here because.. I seem to understand they should just be another skin for springer?)
- [ ] Springer books
 * see [here](https://www.springer.com/gp/book/9783540627715): eBook ISBN, DOI and Edition Number
 * and [here](https://link.springer.com/chapter/10.1007/978-3-642-80098-6_36): DOI/URL (it's especially problematic when you have online and printed info [mixing](https://link.springer.com/article/10.1007/s11229-017-1532-7)). 
   * I don't know then if that middle-dot-separated copyright information (that finally manages to separate publisher from place and date) couldn't be further parsed.

**Comment by zuphilip** [comment]
1. It seems that we can cover Palgrave books also with the Springer Books translator. :+1: 
2. The ISBN of the Softcover version is already saved :heavy_check_mark: ; DOI is missing, but we can add this to the extra field for book :+1:  ; we don't save `1` for the first edition as you also don't use this in citations :negative_squared_cross_mark: 
3. That is Springer Link translator and your cases are a book chapter and a journal article! Yes, the DOI und URL should be added in the first link :+1: ; I don't understand your second example with mixing info :question: don't understand the middle dot thing :question:

**Comment by mirh** [comment]
I'm talking about `© Springer-Verlag Berlin · Heidelberg 1996`
I'm not sure if that "separate the holder from the place and date with a dot" is anything remotely standard (which could be parsed then) or something random.

**Comment by zuphilip** [comment]
So you are talking about correctly separating the publisher and place. Which example?

**Comment by zuphilip** [comment]
nvm. I found it and a more stable fix for it.
