### ISSUE TITLE
translators/Time.com.js: Missing date

### ISSUE THREAD

**Issue by JAGulin** [zotero/translators#1997]
The swampland and business test cases in translators/Time.com.js are missing date field even if there is a date available. Of course the reason I mention this is because the dates should be included for better usability, and when the test case has it, the translator can support it.

For the test case url
http://swampland.time.com/2012/03/04/obama-courts-aipac-before-netanyahu-meeting/?iid=sl-main-lede
There is the visible date:
<span class="entry-date">March 04, 2012</span>
But also several instances available in other formats:
date: '2012-03-04 15:33:11 -0400',
"contentPublishedDate":"2012-03-04T15:33:11+00:00"
setContentCreated", "2012-03-04T15:33:11+00:00"]);
s_time.prop26 = '2012-03-04';
And, not the least, a tell tale part of the URL itself: /2012/03/04/

Currently the [test cases are failing](https://zotero-translator-tests.s3.amazonaws.com/testTranslators.html#date=2019-08-29&browser=v&version=translation-server.SOURCE.cc27bf6) so should fix that first. 
Some are "Detection failed" with no further info.
The "attachments" getting "mimeType": "text/html" where nothing was expected, I suppose can be updated in the test case. It also fails for "Embedded Metadata" test, but I don't see any [patch where this changed](https://github.com/zotero/translators/commits/master/Embedded%20Metadata.js). 

Is there a maintainer that could look into this Translator?

**Comment by zuphilip** [comment]
I tried to update the translator for Time, see the PR linked here.

Some test cases failing in Scaffold due to accepting something before proceed to the content and dynamic loading of the content.
