### ISSUE TITLE
Embedded Metadata: Value from <time> element is added to creator from parsed byline

### ISSUE THREAD

**Issue by poikilos** [zotero/translators#2001]
https://www.sciencemag.org/news/2019/06/closest-known-ancestor-today-s-native-americans-found-siberia produces:
![image](https://user-images.githubusercontent.com/7557867/64303695-3cc29400-cf57-11e9-88f8-637b45689e2d.png)

This may point to a larger issue.

**Comment by dstillman** [comment]
@poikilos: This is just the Embedded Metadata translator, so it's using metadata from the page. In this case, there's not much in a standardized form, so the translator tries to extract the author name from the page.

For others:

```html
<p class="byline byline--article">
--
  | By <a href="/author/michael-price">Michael Price</a><time>Jun. 5, 2019 , 1:00 PM</time></p>
```
I doubt this is at all common, but we could theoretically exclude content within a `<time>` element from the byline text.
