### ISSUE TITLE
Vanderbilt OJS 

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#2002]
It seems that currently the OJS instance of U Vanderbilt is not giving much meta data and therefore the OJS translator cannot extract much data for Zotero, e.g. http://ejournals.library.vanderbilt.edu/ojs/index.php/ameriquests/article/view/220 . I have written them but not yet heard back. This test case is OJS is therefore not yet updated (because I have still hope that the will fix this).

_Originally posted by @zuphilip in https://github.com/zotero/translators/pull/1991#issuecomment-526908264_

**Comment by AbeJellinek** [comment]
Seems to be fixed on their end.
