### ISSUE TITLE
Wiley PDF not always saved

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#2004]
There is no PDF saved for the Open Access article here from Wiley: https://besjournals.onlinelibrary.wiley.com/doi/10.1002/pan3.10038 cf. https://forums.zotero.org/discussion/78966/no-pdf-downloading-on-wiley . The same is true for other examples I tested.

I can replicate this issue on my Windows machine. It seems that the translator correctly tries to use the URL https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1002/pan3.10038  as the `pdfUrl`. However, in the end the connector fails with a red x.

This URL works in the browser for me without any problem, but when I trying to curl for it I see:
```
$ curl -I https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1002/pan3.10038
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0HTTP/2 302
server: AtyponWS/7.1
cache-control: private
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
strict-transport-security: max-age=16070400
x-frame-options: SAMEORIGIN
p3p: CP="NOI DSP ADM OUR IND OTC"
location: https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1002/pan3.10038?cookieSet=1
set-cookie: I2KBRCK=1; domain=.onlinelibrary.wiley.com; path=/; secure; expires=Mon, 07-Sep-2020 18:13:16 GMT
content-type: text/html; charset=utf-8
date: Sun, 08 Sep 2019 18:13:16 GMT
```

@dstillman Is this maybe the problem? How could we overcome this?

**Comment by zuphilip** [comment]
@dstillman Is there any way to see the header of a requested URL within Zotero? AFAIS I cannot use `ZU.doGet` for that...

**Comment by dstillman** [comment]
I'm looking into this.

**Comment by dstillman** [comment]
Another report: https://forums.zotero.org/discussion/79230/pdf-not-downloading

**Comment by dstillman** [comment]
So at least for me, the `/doi/pdf/` URL retrieved from `citation_pdf_url` isn't a PDF — it's an HTML page with an `<object>` tag, and I can retrieve a working PDF URL by just using this instead of all the iframe stuff:

```javascript
ZU.doGet(pdfUrl, function(text) {
	if (text) {
		var m = text.match(/<object[^>]*data="([^"]+)" type="application\/pdf"[^>]*>/i);
		if (m) {
			m[1] = ZU.unescapeHTML(m[1]);
			Z.debug('PDF URL: ' + m[1]);
			pdfUrl = m[1];
		}
		else {
			Z.debug('Could not determine PDF URL');
		}
	}
```

(This is hacky, but we'll be able to replace it with `DOMParser` soon.)
