### ISSUE TITLE
Primo 2018 not working for "Collections"

### ISSUE THREAD

**Issue by symac** [zotero/translators#2012]
Primo is offering an option [called Collections](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Back_Office_Guide/060Configuring_Primo%E2%80%99s_Front_End/050Collection_Discovery) that can be seen on [Liège university catalog](https://explore.lib.uliege.be/discovery/collectionDiscovery?vid=32ULG_INST:ULIEGE&collectionId=81129164700002321&lang=fr) for example.

Zotero does not support saving from these collections right now, sometimes the "Save web page" option is given, other times, "Primo 2018" is loaded, but crashes.

I have been able to improve ```detectWeb``` by adding the following lines to it:

```javascript
rows = doc.querySelectorAll(".collection-element");
if (rows.length==1) return "book";
if (rows.length>1) return "multiple";
```

But I struggle with ```getSearchResults```. I am able to find the rows by adding the following line : 
```javascript
if (rows.length===0) rows = doc.querySelectorAll(".collection-element");
```

Within the for loop, I can find the titles using:
```javascript
let title = rows[i].parentNode.textContent;
```

But I have not been able to catch the url as it does not appear in HTML but is based on the event in Angular.

This seems to be needed to fix the issue. Any idea someone?

ping @zuphilip who has been working on the current version of the script.

**Comment by zuphilip** [comment]
The Primo 2018 translator is based on the fact that the URLs to the structured PNX are found on the website by looking at the CSS path `.urlToXmlPnx[data-url]`. For the usual discovery system this is also the case for multiple items, e.g. https://explore.lib.uliege.be/discovery/search?query=any,contains,zotero&tab=ULIEGE&search_scope=ULIEGE&vid=32ULG_INST:ULIEGE&lang=fr&offset=0 .

However, this new collection feature of Primo is working quite differently. There are not URLs to the PNX data but there is not even an indication about the ID in Primo. Everything is somehow triggered by the Angular framework.

Therefore, this is not something we can easily fix here on our side. You (or someone else) could try to reach out to ExLibris and ask whether they can add the links to the PNX data in the collections as well, i.e. this could then look like this
```html
<prm-gallery-item ng-repeat="item in $ctrl.itemsList" [item]="item" [index]="::1 + $index" [total-items]="::$ctrl.totalItems">
   <span ng-if="(!$ctrl.isFullViewOverlayOpen || $ctrl.isFullView)" class="urlToXmlPnx" title="https://explore.lib.uliege.be/primaws/rest/pub/pnxs/xml/L/alma9919542688302321?vid=32ULG_INST:ULIEGE&amp;lang=en&amp;adaptor=Local Search Engine&amp;inst=32ULG_INST&amp;showPnx=true&amp;jwtAsParam=eyJraWQiOiJwcmltYVByaXZhdGVLZXktMzJVTEdfSU5TVCIsImFsZyI6IkVTMjU2In0.eyJpc3MiOiJQcmltYSIsImp0aSI6IiIsImV4cCI6MTU3MTU3NDkxNywiaWF0IjoxNTcxNDg4NTE3LCJ1c2VyTmFtZSI6ImFub255bW91cy0xMDE5XzEyMzUxNyIsImRpc3BsYXlOYW1lIjpudWxsLCJ1c2VyIjoiYW5vbnltb3VzLTEwMTlfMTIzNTE3IiwidXNlckdyb3VwIjoiR1VFU1QiLCJpbnN0aXR1dGlvbiI6IjMyVUxHX0lOU1QiLCJ1c2VySXAiOiIyMTcuMjI1LjE0Mi4xNDQiLCJhdXRoZW50aWNhdGlvblByb2ZpbGUiOiIiLCJhdXRoZW50aWNhdGlvblN5c3RlbSI6IiIsImxhbmd1YWdlIjoiZW4iLCJzYW1sU2Vzc2lvbkluZGV4IjoiIiwic2FtbE5hbWVJZCI6IiIsIm9uQ2FtcHVzIjoiZmFsc2UiLCJzaWduZWRJbiI6bnVsbCwidmlld0lkIjoiMzJVTEdfSU5TVDpVTElFR0UifQ.lNZtrWluAe9uFQUw0VoUX7_Qef5Q_Tyfnm1X6LqUGJD6pCTJ_EqunbSZA2xXt0e3gmHmCR4uKrNWfRMRnUgJHQ" aria-hidden="true" data-url="https://explore.lib.uliege.be/primaws/rest/pub/pnxs/xml/L/alma9919542688302321?vid=32ULG_INST:ULIEGE&amp;lang=en&amp;adaptor=Local Search Engine&amp;inst=32ULG_INST&amp;showPnx=true&amp;jwtAsParam=eyJraWQiOiJwcmltYVByaXZhdGVLZXktMzJVTEdfSU5TVCIsImFsZyI6IkVTMjU2In0.eyJpc3MiOiJQcmltYSIsImp0aSI6IiIsImV4cCI6MTU3MTU3NDkxNywiaWF0IjoxNTcxNDg4NTE3LCJ1c2VyTmFtZSI6ImFub255bW91cy0xMDE5XzEyMzUxNyIsImRpc3BsYXlOYW1lIjpudWxsLCJ1c2VyIjoiYW5vbnltb3VzLTEwMTlfMTIzNTE3IiwidXNlckdyb3VwIjoiR1VFU1QiLCJpbnN0aXR1dGlvbiI6IjMyVUxHX0lOU1QiLCJ1c2VySXAiOiIyMTcuMjI1LjE0Mi4xNDQiLCJhdXRoZW50aWNhdGlvblByb2ZpbGUiOiIiLCJhdXRoZW50aWNhdGlvblN5c3RlbSI6IiIsImxhbmd1YWdlIjoiZW4iLCJzYW1sU2Vzc2lvbkluZGV4IjoiIiwic2FtbE5hbWVJZCI6IiIsIm9uQ2FtcHVzIjoiZmFsc2UiLCJzaWduZWRJbiI6bnVsbCwidmlld0lkIjoiMzJVTEdfSU5TVDpVTElFR0UifQ.lNZtrWluAe9uFQUw0VoUX7_Qef5Q_Tyfnm1X6LqUGJD6pCTJ_EqunbSZA2xXt0e3gmHmCR4uKrNWfRMRnUgJHQ" style=""></span>
   ...
```

**Comment by symac** [comment]
Thanks @zuphilip I have opened a bug with Ex-Libris, hope they will fix it quickly.

**Comment by symac** [comment]
Here is the update I got from Ex-Libris on the case I had opened with them:

> I am happy to update you that this issue from Primo's side is tentatively planned to be fixed on the Primo August 2020 Release.

Wait & see.

**Comment by symac** [comment]
Update from ExLibris today on this case 

> it has been decided to update the expected release of this issue to Primo February 2021

So wait (a bit more) & see.

**Comment by symac** [comment]
Two updates on this : 

- 25th October 2020 : "has been pushed to Primo May 2021 release"
- 1st December 2020 : "has been pushed to Primo November 2021 Release"

See you next semester for a new update :)

**Comment by symac** [comment]
Update from February 2nd, please don't laugh...

> This is to update you that the tentative fix date has been pushed to Primo February 2022 Release.

**Comment by AbeJellinek** [comment]
I think we can fix this on our end by calling their API. I'll give it a try.

**Comment by AbeJellinek** [comment]
OK, never mind. Their API doesn't return PNX data for this "Collections" feature. This'll have to be fixed on their end after all.

**Comment by nilinatan** [comment]
Hi 

I know that you have been waited for  a while,  and laugh a bit :)
As February 2022 is in the corner you can test against our Primo QA environment and check if Zotero manages to export Collection's items : we have added the .urlToXmlPnx for each collection item 
https://primo-qa.hosted.exlibrisgroup.com/primo-explore/collectionDiscovery?vid=CTWCC&collectionId=81233249970003766 

All the best 
Nili Natan
Product Manager of Discovery & Delivery
nili.natan@exlibrisgroup.com

**Comment by symac** [comment]
@zuphilip @AbeJellinek there has been some progress on their side, the url is now there as you can see on our live Primo : https://babordplus.hosted.exlibrisgroup.com/primo-explore/collectionDiscovery?vid=33PUDB_UBM_VU1&collectionId=81180009920004674

The issue is that when visiting this page using Firefox, the Primo 2018 translator is not fired (an issue with the asynchronous loading of results?). Anyway, when I visit this page using the translator editor and load the Primo 2018 translator, I can save the results (there is an small issue with the resource-type being added to the beginning of the title but at least results are seen).

**Comment by symac** [comment]
@AbeJellinek @adam3smith I am coming back to this issue and see that an update has been deployed in July to monitor the changes on the page but I still get issues with this translator. When visiting [this collection page from my library](https://babordplus.hosted.exlibrisgroup.com/primo-explore/collectionDiscovery?vid=33PUDB_UBM_VU1&collectionId=81180009920004674) on my catalog I rarely get the Primo 2018 from Firefox or Chrome (a bit more often from Chrome maybe). It's the same for the [Liege example](https://explore.lib.uliege.be/discovery/collectionDiscovery?vid=32ULG_INST:ULIEGE&collectionId=81129164700002321&lang=fr) available in the tests. 

Is this always working for you or do you this this random behavior?

**Comment by symac** [comment]
I just got an update from the provider that tell me that they won't fix anything on their side:

```
After thorough examination and prioritization, we have decided that a fix for this issue will not be part of our current development work plan.
We understand the inconvenience this decision may cause. The decision was taken after examining the severity and scope of the problem compared to other pipelined issues and any possible implications involved in implementing the necessary change.
```

**Comment by sanjeetmann1** [comment]
FYI - I came across this conversation while searching for information about a different problem with the Primo 2018 translator and was able to successfully import [an item from the collection linked above](https://explore.lib.uliege.be/discovery/collectionDiscovery?vid=32ULG_INST:ULIEGE&collectionId=81129164700002321&lang=fr).

Sanjeet Mann
CSU San Bernardino
