### ISSUE TITLE
Translator for CEUR-WS workshop papers

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#2015]
See also old post in the forum requesting a translator for CEUR-WS https://forums.zotero.org/discussion/32885/translator-request-ceur-ws-org . Currently, they only have the PDFs, e.g. http://ceur-ws.org/Vol-2460/paper2.pdf and workshop pages listing all the papers presented there, e.g. http://ceur-ws.org/Vol-2460/. However, they wanted to do some reconstruction of the pages and maybe also have some new landing page. @clange Let us know when the new structure is fixed or you want to optimize something for the reference extraction like here for Zotero.

**Comment by VladimirAlexiev** [comment]
https://dblp.org/db/series/ceurws/ has bibliography for many but not all CEUR proceedings.

I need this very much for the LDAC workshops, eg http://ceur-ws.org/Vol-2636/ is the CEUR proceedings of LDAC 2020. https://dblp.org/db/series/ceurws/ceurws2600-2699.html is missing that one.

Maybe this can help: https://www.researchgate.net/publication/306231689_CEUR-WS-LOD_Conversion_of_CEUR-WS_Workshops_to_Linked_Data . It's at https://github.com/ceurws/lod but last updated 2016, and I don't see the extraction tools.

**Comment by VladimirAlexiev** [comment]
Hi @AbeJellinek ! Thanks a lot of this! 

I tested it on http://ceur-ws.org/Vol-2636/ and here's the first result:
```
@inproceedings{chavez-feria_obxml_2020,
	address = {Dublin, Ireland, June},
	series = {{CEUR} {Workshop} {Proceedings}},
	title = {From {obXML} to the {OP} ontology: developing a semantic model for occupancy proﬁle},
	volume = {2636},
	shorttitle = {From {obXML} to the {OP} ontology},
	language = {en},
	booktitle = {Proceedings of the 8th {Linked} {Data} in {Architecture} and {Construction} {Workshop}},
// conference name = Linked Data in Architecture and Construction
	publisher = {CEUR},
	author = {Chavez-Feria, Serge and Giannakis, Giorgos and García-Castro, Raul and Poveda-Villalón, María},
	editor = {Poveda-Villalón, María and Roxin, Ana and McGlinn, Kris and Pauwels, Pieter},
	month = jul,
	year = {2020},
// date = 2020-07-09
	note = {ISSN: 1613-0073},
	pages = {9--22},
}
```

Suggestions for improvement:
- add paper's `url = http://ceur-ws.org/Vol-2636/01paper.pdf`
- fix address to "Dublin, Ireland" (`CEURLOCTIME=Dublin, Ireland, June 17-19, 2020 (virtually hosted)` is location and date, so some parsing will be needed)
- if you find date in `CEURLOCTIME` then use that (in this case date should be `June 17-19, 2020`). Otherwise use  `CEURVERSION` (which is `2020-07-09`, the date published)
- skip "Preface" as that's not an academic contribution

Thanks again!

**Comment by VladimirAlexiev** [comment]
Tested on http://ceur-ws.org/Vol-1117/
- get date from `Valetta, Malta, September 26, 2013.` (not `2014-01-23`)
- authors are missing because this CEUR uses an older markup:
```html
<span class="CEURAUTHORS">Achille Felicetti, Tiziana Scarselli, M. L. Mancinelli, Franco Niccolucci</span>
```
  - the new markup is better structured (but there are plenty of older proceedings using the older markup):
```html
<li id="01paper"><a href="01paper.pdf">
<span class="CEURTITLE">From obXML to the OP ontology: developing a semantic model for occupancy proﬁle</span></a>
<span class="CEURPAGES">9-22</span> <br>
<span class="CEURAUTHOR">Serge Chavez-Feria</span>, 
<span class="CEURAUTHOR">Giorgos Giannakis</span>, 
<span class="CEURAUTHOR">Raul García-Castro</span>, 
<span class="CEURAUTHOR">María Poveda-Villalón</span>
</li>
```

**Comment by VladimirAlexiev** [comment]
@AbeJellinek Thanks a lot! I'll test it as soon as it's released in Zotero.

> We don't tend to set the URL to a direct PDF link

Agreed, this link allows the user to find the bibliographic entry.

> CEURVERSION is in an HTML comment, they should not do that

Agreed, it doesn't appear in the list of fields in the instructions: http://ceur-ws.org/Vol-XXX/index.html. BTW, have you looked at the fields and do you think anything else needs to be mapped?
- CEURLANG: the main language of the proceedings (eng, deu, fra, spa, rus, ita, por, ...) according to ISO 639-2/T (http://en.wikipedia.org/wiki/List_of_ISO_639-2_codes)
- CEURVOLNR: the volume number of the proceedings **set by us**
- CEURPUBYEAR: the year in which the proceedings volume was created (see also YYYY)
- CEURURN: the URN of the volume **set by us**
- CEURVOLACRONYM: the acronym of the workshop plus YYYY (year of the workshop) the acronym may contain '-'; between acronym and year is either a blank or a '-'. The year is exactly 4 digits, e.g. 2012
- CEURVOLTITLE: the title of the proceedings
- CEURFULLTITLE: the long title of the proceedings
- CEURCOLOCATED: the acronym and year of the conference where this workshop was co-located with; use "NONE" if the workshop was not co-located with a conference
- CEURLOCTIME: the place and time when the workshop took place
- CEURVOLEDITOR: full name of an editor of the proceedings
- CEURTOC: indicator for the start of the table of contents
- CEURSESSION (optional): separator for a section within the table of contents
- CEURTITLE: title of a paper within the table of contents
- CEURPAGES (optional): numerical range of pages of a paper, e.g. 10-20
- CEURAUTHOR: one author of a paper (use full names, do not include affiliations); multiple authors should be separated by commas
- CEURPUBDATE: the precise date of publication at CEUR-WS.org **set by us**
- CEURSUBMITTEDPAPERS: the total number of papers submitted for peer review to this volume
- CEURACCEPTEDPAPERS: the total number of accepted peer-reviewed papers (excl. invited papers, keynotes etc)
- CEURACCEPTEDREGULARPAPERS: the number of regular-size accepted peer-reviewed papers (optional)
- CEURACCEPTEDSHORTPAPERS: the number of short accepted peer-reviewed papers  (optional)

**Comment by WolfgangFahl** [comment]
CEUR-WS has now a volume browser and links all proceedings to wikidata see http://ceur-ws-browser.bitplan.com/volume/3153 for a recent example  that is linked to wikidata, k10plus and dblp. We intend to improve the synchronization to wikidata so that in the end you should be able to pickup the detail data from there.

**Comment by VladimirAlexiev** [comment]
Hi @WolfgangFahl nice to hear from you!
But I'm looking for paper-level bibliographic metadata.

Eg http://ceur-ws.org/Vol-11/ is present as https://www.wikidata.org/wiki/Q113500245, 
but its paper "Semi-structured Data with Constraints and Incomplete Information" is not in Wikidata.

**Comment by WolfgangFahl** [comment]
@VladimirAlexiev  we are working on this - Lars Willighagen already did a nice job for some of the entries see https://scholia.toolforge.org/event-series/Q56846035
