### ISSUE TITLE
CNKI translator proxy error

### ISSUE THREAD

**Issue by l0o0** [zotero/translators#2022]
I user proxy to access CNKI. The website will redirect to https://kns-cnki-net-s.vpn2.njau.edu.cn/kns/brief/default_result.aspx, "kns-cnki-net-s.vpn2.njau.edu.cn" is the proxy URL suffix. Without a proxy, the URL is https://kns.cnki.net/kns/brief/default_result.aspx. I have change the target in CNKI.js translator from "^https?://([^/]+\\.)?cnki\\.net" to "^https?://kns". The target works fine, I can see "Save to Zotero (CNKI) " when I open the CNKI URL in Firefox. But an error appears "An error occurred saving with CNKI. Attempting to save using Save as Webpage instead.". In error report I found a message "[JavaScript Error: "HTTP POST http://epub.cnki.net.s.vpn2.njau.edu.cn/kns/ViewPage/viewsave.aspx?TablePre=SCDB failed with status code 404"]".

The post URL is added a proxy suffix. I don't know why the correct URL wrote in CNKI.js is changed after proxy? 

The correct URL in CNKI.js is "http://epub.cnki.net/kns/ViewPage/viewsave.aspx?TablePre=SCDB".  I have tested CNKI.js in Zotero Scaffold. It works fine in scaffold.

**Comment by l0o0** [comment]
I have tried to disable proxy in Zotero connector preference. The error still exists.

**Comment by zuphilip** [comment]
Please use the Zotero forum for general questions and reports: https://forums.zotero.org/

**Comment by l0o0** [comment]
I have already posted in zotero forum. There is no reply.
