### ISSUE TITLE
Multiple DBLP breakages

### ISSUE THREAD

**Issue by GuyAglionby** [zotero/translators#2024]
Three issues here:

* Author pages are detected as 'multiple', but the items that are extracted are all named `null` (e.g. [here](https://dblp.dagstuhl.de/pers/hd/k/Knuth:Donald_E=.html)) (edit: but not in all cases, see [here](https://dblp1.uni-trier.de/pers/hd/d/Das:Rajarshi))
* Paper information is extracted incorrectly (e.g. [here](https://dblp.org/rec/html/conf/iclr/DasMYTM19))
* Search pages are not detected (e.g. [here](https://dblp1.uni-trier.de/search?q=zotero))

**Comment by zuphilip** [comment]
First of all, there seem to be some new or not yet recognized urls:
- https://dblp1.uni-trier.de/ (maybe other numbers are allowed as well?)
- https://dblp.org/rec/html/conf/iclr/DasMYTM19 (at the moment only `rec/bibtex` is recognized)

However, I guess that a little more than these changes are needed. One has to check for multiples whether the Xpath are still working as expected. Moreover, I suggest to redirect the `html` page to the `bibtex` page which we already support.
