### ISSUE TITLE
eLibrary.ru: No longer saving creators

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2030]
Probably missing other things as well

https://forums.zotero.org/discussion/79602/elibrary-ru-authors-name

@i3v, any interest in updating this [again](https://github.com/zotero/translators/pull/1965)?

**Comment by zuphilip** [comment]
I can fix that. Just give me a minute...

**Comment by advoropaev** [comment]
It doesn't save pages now. 
https://elibrary.ru/item.asp?id=37254879
