### ISSUE TITLE
Engineering Village Multiples Broken

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2034]
https://www.engineeringvillage.com/search/quick.url?SEARCHID=f0052e5809644d5e8cdb9e5a1de542e5&COUNT=1&usageOrigin=&usageZone= (session link)

Reported: https://forums.zotero.org/discussion/67514/engineering-village-inspec#latest

**Comment by zuphilip** [comment]
I don't have access to this database and therefore cannot work on this translator.
