### ISSUE TITLE
Emerald Journals

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2036]
They changed their site -- it think we used to cover this with one of the default translators, but doesn't look like that's currently working. EM imports nicely but without PDF

https://www.emerald.com/insight/content/doi/10.1108/IJRDM-08-2017-0180/full/html

**Comment by adam3smith** [comment]
Announcement: https://www.emeraldgrouppublishing.com/about/news/?id=8571 They've switched away from the Atypon platform we did support

**Comment by zuphilip** [comment]
Okay. I also see the old things in our code:
```bash
$ grep -i emerald *.js
Atypon Journals.js:                                     } else if (url.includes('www.emeraldinsight.com')) {
Atypon Journals.js:                                             //for Emerald, improve author's lastname and firstname
Atypon Journals.js:                             //for Emerald, get rid of the "null" that they add at the end of every title:
Atypon Journals.js:                             if (url.includes("www.emeraldinsight.com")){
Atypon Journals.js:             "url": "http://www.emeraldinsight.com/toc/sajgbr/2/2",
Atypon Journals.js:             "url": "http://www.emeraldinsight.com/doi/full/10.1108/SAJGBR-10-2012-0120",
Atypon Journals.js:                             "libraryCatalog": "emeraldinsight.com (Atypon)",
Atypon Journals.js:                             "url": "http://www.emeraldinsight.com/doi/full/10.1108/SAJGBR-10-2012-0120",
Baidu Scholar.js:                               "url": "http://www.emeraldinsight.com/doi/full/10.1108/07419051111154758",
```
(I already filtered out a false positive result in `Rock, Paper, Shotgun.js:` from the result above.)

We should clean up this code then also as Emerald is not using Atypon anymore, but first I will continue the review for your new translator.

**Comment by zuphilip** [comment]
Reopening, because cleaning up Atypon translator is still a todo.
