### ISSUE TITLE
Hein Online Volume no longer imports

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2038]
The RIS maps volume to VO instead of VL. We can just switch the tag out.

**Comment by zuphilip** [comment]
I guess this comes from https://forums.zotero.org/discussion/79705/problem-with-heinonline-translator-volume-no-longer-transfer-to-zotero

**Comment by zuphilip** [comment]
Oh,  I started to work on this. @adam3smith Did you already start or should I continue my fix for it?

**Comment by zuphilip** [comment]
Sorry, I just finished my solution in #2040. Hope that is okay for you.
