### ISSUE TITLE
Web translator for Language Science Press

### ISSUE THREAD

**Issue by Anaphory** [zotero/translators#2042]
For language science press books, such as http://langsci-press.org/catalog/book/233, there seems to be no appropriate Zotero translator.

**Comment by zuphilip** [comment]
Language Science Press is running on OMP software. I know from OJS that there are several plugins one can activate to offer bibliographic metadata in several formats (e.g. HighWire metatags, DC, BibTeX, RIS). There are some meta tags in the `head`, but they look strange:
```
<meta name="generator" content="Language Science Press 1.2.0.0">
<meta name="DC.Identifier.DOI" content="10.5281/zenodo.3247415">
<meta name="citation_doi" content="10.5281/zenodo.3247415">
<meta name="DC.Identifier.DOI" content="">
<meta name="citation_doi" content="">
<meta name="DC.Identifier.DOI" content="">
<meta name="citation_doi" content="">
<meta name="DC.Identifier.DOI" content="">
<meta name="citation_doi" content="">
<meta name="DC.Identifier.DOI" content="">
<meta name="citation_doi" content="">
<meta name="DC.Identifier.DOI" content="">
<meta name="citation_doi" content="">
```
More tags in the `body` seem to be useful but I haven't seen BibTeX or RIS data. CC @Glottotopia

**Comment by Glottotopia** [comment]
@CFanselow can maybe give some more information
