### ISSUE TITLE
Date Decided not saving in CanLii

### ISSUE THREAD

**Issue by leachandrew** [zotero/translators#2063]
When saving case to Zotero from Chrome using canlii, the decision date does not add to the record.  

Reproducible example:

Use this link: https://www.canlii.org/en/ca/scc/doc/1998/1998canlii793/1998canlii793.html

save to Zotero. 

<img width="739" alt="zotero_qc_seccession" src="https://user-images.githubusercontent.com/30224429/69368137-c3356a80-0c56-11ea-8db8-20c7c68bc1e8.PNG">

The library entry does not capture the decision date from the site.

**Comment by zuphilip** [comment]
Fixed in #2068.
