### ISSUE TITLE
Emerald Insight fails on book chapter

### ISSUE THREAD

**Issue by owcz** [zotero/translators#2087]
Breaks on [this book chapter](https://www.emerald.com/insight/content/doi/10.1108/S0163-786X(2012)0000033008/full/html) but appears to be fine on others

**Comment by zuphilip** [comment]
@dstillman I tried to test this in the browser and clicked on update translators in the connector, but somehow my Emerald Insight translator stays the same. Does this work for you?

**Comment by zuphilip** [comment]
Okay, when I update translators first in Zotero and then afterwards again in the connector and then reload the website it works now. But is this the way it should be? Wasn't it different before?
