### ISSUE TITLE
JSTOR dropping `https://` from URLs

### ISSUE THREAD

**Issue by owcz** [zotero/translators#2088]
Recently JSTOR has been dropping `https://` from URLs
Haven't looked into whether it's their end or the translator's but either way the translator should handle, yes?

**Comment by dstillman** [comment]
Could you clarify what you mean by "dropping `https://` from URLs"?

**Comment by owcz** [comment]
When using the JSTOR translator, the imported URL field no longer includes `https://` (i.e., they start with `www.`)

**Comment by dstillman** [comment]
Someone will need to look at this, but in the meantime in the latest Zotero beta I've fixed the bug that caused it to open URLs without the scheme in an internal viewer instead of launching them as external webpages.

**Comment by placardo** [comment]
Apparently it was dropped in the RIS data used to import items, probably in mid-november 2019. Should it be added back in the scraper? Once the bug is fixed this shouldn't pose any problem

**Comment by dstillman** [comment]
> `UR  - www.jstor.org/stable/27592221`

Yes, we should add it back conditionally so that when they fix it we don't include it twice.

@adam3smith, do you know of anyone at JSTOR to report the RIS problem to?
