### ISSUE TITLE
IEEE xplore PDF downloads broken via proxy

### ISSUE THREAD

**Issue by VorpalBlade** [zotero/translators#2104]
Using the connector in Firefox, IEEE xplore PDF downloads work fine at the university, but not from home via the university proxy support in Zotero. I can still manually click the link on the IEEE website and open the PDF just fine. After a few seconds, a red X is displayed in front of the PDF in the little progress drop down. I'm fairly sure this used to work a few weeks ago.

Some additional observations:
* Open access PDFs from IEEE do work, it is just the locked ones that don't.
* The PDF downloads work fine with other publishers over proxy (such as SAGE).

Regarding log messages:
* Zotero report ID (from clicking the button in the preferences): 1845380927
* In the logs I have a lot of duplicates of the message `[JavaScript Error: "Frame not found, or missing host permission" {file: "undefined"}]`. However, there are so many duplicates of this I cannot tell when/if they are correlated with clicking the button.
* There are no new messages in the normal Javascript developer console after clicking the "save to zotero button".

Software versions:
* Firefox 71.0
* Zotero 5.0.80
* Zotero Connector 5.0.60
* OS: Ubuntu 18.04

**Comment by zuphilip** [comment]
@VorpalBlade Please ask this question in the Zotero forum https://forums.zotero.org/ and have a look at https://www.zotero.org/support/kb/proxy_troubleshooting .
