### ISSUE TITLE
Trove failure

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2106]
https://forums.zotero.org/discussion/78599/downloading-from-trove

> GET http://trove-proxy.herokuapp.com/pdf/73543424 500 (INTERNAL SERVER ERROR)

**Comment by zuphilip** [comment]
Okay, the PDF generation needs Python 2 but heroku now (?) uses Python 3. I tried a quickly fix for this in https://github.com/wragge/trove-proxy/pull/2 tested in https://arcane-ravine-97394.herokuapp.com/ .

Anyways, it is bad that the remaining code is depending on this part and cannot complete without it. I will try to fix that now.

**Comment by dstillman** [comment]
It looks like the proxy is fixed? I went to test #2108 but it successfully used the proxy.

**Comment by dstillman** [comment]
It also looks like HTTPS works for the proxy. @wragge, any reason we can't switch to that instead?

**Comment by wragge** [comment]
Sorry, I've been moving house/states and been off the air for a while. I'm not sure what the problem was as the proxy seems to be fine. It's on hobby dynos (ie I pay $ to keep it going), so it's not dependent on free hours. Yes, https is fine.

I will update to Python 3 however.
