### ISSUE TITLE
eLife - campaign links break translator

### ISSUE THREAD

**Issue by jolson1129** [zotero/translators#2133]
When using Chrome [Version 80.0.3987.122 (Official Build) (64-bit)], and Zotero 5.0.82, I can't import papers from eLife. The save to Zotero button works, I get a saving to [some collection], but then nothing appears below and nothing is saved. I believe the translator needs to be updated.

**Comment by adam3smith** [comment]
Works for me e.g. on https://elifesciences.org/articles/54740 
Let's take this to the Zotero forums please: https://www.zotero.org/support/troubleshooting_translator_issues

**Comment by jolson1129** [comment]
Hi Sebastian,

Thanks for the quick response!

Your link worked for me as well.

What about these? They do not for me.
https://elifesciences.org/articles/50962?utm_source=content_alert&utm_medium=email&utm_content=fulltext&utm_campaign=24-February-20-elife-alert

https://elifesciences.org/articles/54170?utm_source=content_alert&utm_medium=email&utm_content=fulltext&utm_campaign=24-February-20-elife-alert

https://elifesciences.org/articles/52466?utm_source=content_alert&utm_medium=email&utm_content=fulltext&utm_campaign=24-February-20-elife-alert


******************************************
Jacob M Olson PhD
Postdoctoral Fellow - Jadhav Lab
Brandeis University
jmolson.net
******************************************

**Comment by adam3smith** [comment]
Thanks -- the content alert URLs break the translator. For now, you can simply remove everything from the ? and reload the page and it'll work. We'll fix this, obviously.

**Comment by jolson1129** [comment]
Thanks for the update.
