### ISSUE TITLE
Add volume number to TEI

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2146]
Reguested with details here: https://forums.zotero.org/discussion/81909/export-to-tei-doesnt-export-of-volumes#latest

> This value must be inside an "extent" tag,
> inside the "monog" tag.

Help very welcome @FranziskaHorn @adunning (since both of you have worked on this before & I don't know anything about TEI)

**Comment by nivaca** [comment]
Just fixed the issue and created a pull request: #2148

**Comment by AbeJellinek** [comment]
Fixed by #2148
