### ISSUE TITLE
PubMed: Search results not working in New PubMed

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2151]
Not sure if the site changed again since launch, but the [new translator](https://github.com/zotero/translators/issues/1800) doesn't seem to be working for search results. Reported [here](https://forums.zotero.org/discussion/81940/connector-not-working-with-clipboard-in-new-pubmed) and [here](https://forums.zotero.org/discussion/82139/problem-exporting-new-pubmed-citations-to-zotero).

@akinhwan, any idea?

**Comment by akinhwan** [comment]
@dstillman hey thanks for bringing this to our attention. let me get back to you guys!

**Comment by katrinaHakon** [comment]
I got this reply when I contacted Pubmed  /NLM about the issue with exporting citation from the new interface this week:
Thank you for writing to the help desk.  Unfortunately, I am not able to troubleshoot issues with third-party software like Zotero.  I recommend that you reach out to the vendor directly to report the problem with the plugin.  In a situation like this, if there is an issue with the metadata from PubMed, the vendor will contact us and provide specific technical details that will help us investigate.

Kind regards, 
Marie xxx
U.S. National Library of Medicine
.................................
In the new interface a problem accurs when you try to export citations from a result-list using the zotero add-on button in the web-browser.
Zotero then only "reads" the top part of the page and does not detect the list of citations in the result-list for export.
You then will have to open the citations one by one to be able to export to zotero.
This was not a problem in the old interface.
Could you please look in to this?

**Comment by dstillman** [comment]
@akinhwan: Any update on this?
