### ISSUE TITLE
ACM: Journal article saved as `document`

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2162]
Reported here: https://forums.zotero.org/discussion/82523/acm-article-saves-as-document

On https://dl.acm.org/doi/10.1145/3230742, Zotero detects a journal article but saves a `document` item, and because of that various fields are missing.

If I'm reading things right, the [new ACM translator](https://github.com/zotero/translators/pull/2101) by @GuyAglionby makes a request to ACM's `exportCiteProcCitation` endpoint, which returns JSON with a custom, invalid CSL style for BibTeX output along with some invalid CSL-JSON data. The translator lowercases their invalid uppercase types, but then just runs it through `itemFromCSLJSON()`. Unfortunately, that's not sufficient, since they're not actually serving CSL-JSON that accurately describes the item — their concern seems to just be outputting correct BibTeX or Refer, so `type="ARTICLE ARTICLE_JOURNAL ARTICLE_MAGAZINE ARTICLE_NEWSPAPER"` all simply output `@article` in the BibTeX. (I'm not sure if they're using a custom CSL processor or just something that happens to be forgiving with invalid types and other validation errors.) In this case, the type is `ARTICLE`, but the (lowercased) `article` CSL type is `document` in Zotero, not `journalArticle` like it is from the BibTeX `@article`.

I haven't looked to see what other problems there might be in the CSL-JSON, but I'd guess that it'd be safer to simply use their BibTeX output instead and make some of the same tweaks to that.

@GuyAglionby, any reason we're not doing that?

**Comment by bwiernik** [comment]
Does someone have a contact at ACM that we could see if they can fix their CSL-JSON?

**Comment by GuyAglionby** [comment]
The `exportCiteProcCitation` endpoint is how their frontend gets the data to subsequently format as BibTex etc. The translation from CSL-JSON is done on the client side using the provided CSL style, so I think it would be difficult to grab the BibTeX directly.

I guess a stopgap would be to manually create a mapping from their style to something that `itemFromCSLJSON()` will understand and then apply it to the CSL-JSON, but it's a bodge. I'm not sure if something changed recently on either the ACM or Zotero side, as it was definitely working before.

**Comment by dstillman** [comment]
Fixed. Looks like it was a change — some tests were failing because of it. After treating `ARTICLE` as `ARTICLE_JOURNAL`, all tests are passing.
