### ISSUE TITLE
EndNote XML: ISSN exported as ISBN

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2171]
https://github.com/zotero/translators/blob/ad2bb1ee582b6b75b32792b609ad969d75a04828/Endnote%20XML.js#L434-L439

I assume this is a trivial fix, but I'm not sure exactly how this translator works.

**Comment by dstillman** [comment]
Unless this is intentional? I'm not sure why that would be, but I'm also not sure what's going on with patent number and report number here.

**Comment by adam3smith** [comment]
This is in fact intentional, yes. ISBN is the only relevant field in the .dtd file (https://support.clarivate.com/Endnote/s/article/EndNote-XML-Document-Type-Definition?language=en_US) and Endnote does export the ISSN to ISBN see e.g. https://gist.github.com/low-decarie/3831049
