### ISSUE TITLE
NYTimes.com snapshots

### ISSUE THREAD

**Issue by dhicks** [zotero/translators#2184]
Last January snapshots were disabled in the NYTimes.com translator because the snapshots were broken (#1807). That issue proposed using archive PDFs instead.  But after that issue was closed it was noted that archive PDFs were also broken.  Currently both code chunks in [NYTimes.com.js](https://github.com/zotero/translators/blob/master/NYTimes.com.js) are disabled, so neither snapshots nor PDFs are collected.  

I have a workaround for my purposes — dragging and dropping from Firefox to the Zotero record forces a snapshot, which doesn't render correctly in a browser can be indexed for fulltext search (using my external search software, at least).  So this isn't a high priority for me.  But I thought it would be useful to have an issue pointing out that the problem isn't actually resolved.

**Comment by dstillman** [comment]
Thanks. We're hoping to rework snapshots soon to make them better handle sites with problematic JS-based rendering, and we'll reenable NYT snapshots at that time.
