### ISSUE TITLE
[PICA] sudoc broken

### ISSUE THREAD

**Issue by symac** [zotero/translators#2202]
Two years ago there had been an issue with http://www.sudoc.abes.fr/ that was not working properly ( #1529 ). @zuphilip had provided a quick fix by rewriting the base url.

The issue is with multiple results page. It works fine on a single record page, but for multiple, the list of available records is displayed, but trying to get one crashes.

But it appears that, following an update on their website, it is broken again. There is an extra cbs/ path in the url. I have tried to fix it by replacing the previous fix : 

```
newUrl = newUrl.replace(/sudoc\.abes\.fr\/cbs\/\/?DB=/, 'sudoc.abes.fr/cbs/xslt/DB=');
```

But it does not appear to work, if anybody has an idea on how to fix it.

**Comment by kerphi** [comment]
@symac I have maybe an idea to fix it. I'm not very sharp with zotero translators but it seams the [Library Catalog (PICA).js](https://github.com/zotero/translators/blob/master/Library%20Catalog%20(PICA).js) is not catching anymore the new sudoc URLS (including the cbs/ path)

I'm not sure but maybe, the head target regexp should be adapted:
```json
"target": "^https?://[^/]+(/[^/]+)?//?DB=\\d",
```
Cause this regexp seams not to be able to catch the new URL, ex:
```
http://www.sudoc.abes.fr/cbs/xslt//DB=2.1/SET=1/TTL=1/SHW?FRST=2
```

I'll try to make a PR but I'm not sure to be able to have a local zotero dev environment for doing it.

**Comment by kerphi** [comment]
Hello @adam3smith, I'm not sure how to develop/test/fix zotero translators.
So I just made a video showing what I see when applying my little patch (see https://github.com/abes-esr/zotero-translators/commit/42eb42f7a39d3d77fffa885b6ade928018e8d325) because for me, it fixes a problem (maybe different from the "multiple" one but I guess it's related):
![](https://github.com/kerphi/github-sandbox/raw/myfeature1/zoom_1.gif)

**Comment by symac** [comment]
@kerphi in fact it does not really solve the problem, because the problem never occurred within Scaffold. Even with the current translator unchanged it should work. I assume it is because scaffold browser does not execute javascript and redirects exactly like Firefox. There might be some redirects or XML/Xslt that are correctly handled by scaffold but are not working properly with Firefox, making things harder to debug.

**Comment by adam3smith** [comment]
There are two different issues here: 
- multiples, which the referenced PR doesn't fix and
- different URLs used by Firefox and Chrome, which I believe it does fix

**Comment by symac** [comment]
Thanks @adam3smith for investigating this issue. It seems you are right, PR #2209 is fixing a probleme I had not noticed on Chrome so it might be worth using it. It appears there are CI issues, is it possible to merge the PR like that or do you want a clean file?

Regarding the issue with multiple, still no idea on my side :(

**Comment by kerphi** [comment]
@adam3smith we looked at the "multiples problem" with @symac and it should be also fixed now in the same PR.

Could the PR be merged at this time or fixing the CI issues (lint) is mandatory before merging this PR?

**Comment by symac** [comment]
I will try to lint the file today

**Comment by adam3smith** [comment]
Thanks -- if it turns out to be too difficult (the translator is pretty big and a bit messy) we can merge without, but having it lint would also improve future maintenability

**Comment by symac** [comment]
@adam3smith I have now linted the file and everything should be fine but Travis is [still complaining](https://travis-ci.org/github/zotero/translators/builds/742056575). But it seems to happen after the Lint part and this is beyond my knowledge. Any idea on how to fix it? 

There might be some rebase to do too, but I am not confident enough with my git knowledge to do it without breaking anything :)

Thanks,
Sylvain

**Comment by adam3smith** [comment]
Yes, Travis now also tries to run the automated tests using Selenium and Chromedriver and the build for that is failing. Nothing to do with the translator, so don't worry about it.

**Comment by kerphi** [comment]
Thank you @adam3smith 
A last question: since you merged the PR will it be automatically deployed to the zotero users just now or do we need to wait an other step?

**Comment by dstillman** [comment]
Yes, it's deployed automatically. Your Zotero Connector should auto-update within 24 hours, or you can update manually by clicking Update Translators in the Advanced pane of the Zotero Connector preferences.
