### ISSUE TITLE
Washington Post translator no longer correctly detecting newspaper articles

### ISSUE THREAD

**Issue by kaldari** [zotero/translators#2206]
Except in the cases of blog posts and very old articles (which use the /wp-dyn/ URL scheme), Zotero is not detecting most Washington Post articles as newspaper articles. It is detecting them as simple web pages instead.

**Comment by kaldari** [comment]
I created a pull request to fix the bug: https://github.com/zotero/translators/pull/2207

**Comment by dstillman** [comment]
Fixed in #2207
