### ISSUE TITLE
Collabora embedded metadata yields odd results

### ISSUE THREAD

**Issue by bwiernik** [zotero/translators#2218]
The Collabora journal website has some odd uses of metadata tags (e.g., DC.Coverage) that yield some junk data on import, such as placing "Article: Credible confidence: a pragmatic view on the frequentist vs Bayesian debate" in Abstract and "No empirical data used" in Loc. in Archive for this article: https://www.collabra.org/articles/10.1525/collabra.149/#n2

**Comment by AbeJellinek** [comment]
Seems to be working fine now.
