### ISSUE TITLE
Add test requiring click and redirection to the valid page?

### ISSUE THREAD

**Issue by rkoyama1623** [zotero/translators#2222]
Hi, I am writing translators for J-PlatPat which is the official patent search engine in Japan.
https://github.com/rkoyama1623/translators/tree/j-platpat

I have a problem adding the test for that site (Functional implementation is over).
Basically, page transitions are made with javascript in this site, so you have to click the link on the unique URL to get to the literature information.

Example:
1. Click the unique URL(https://www.j-platpat.inpit.go.jp/c1800/PU/JP-2628404/ED768DCF32293F182EF3D91179E8AA9F74092A02D8A40B59246F7661093DF888/15/en)
2. Click the link named `JP,2628404,B`.
3. You can get the literature information. but the url is `https://www.j-platpat.inpit.go.jp/p0200`, which is not unique.
    You can get unique url by clicking `url` button.

So, my question is how to emulate the click on the link and redirection to the valid page in test code?
I'm sorry for the site's poor API.

I know the `ZU.doGet` function, but I cannot get the HTML source with it.
```javascript
	if (url.indexOf('/PU') != -1) {
		newPageUrl = 'https://www.j-platpat.inpit.go.jp/p0200';
		ZU.doGet(newPageUrl, function (html) {
		var dp = new DOMParser();
		var doc = dp.parseFromString(html, 'text/html');
		Zotero.debug(doc.querySelector('body').innerText); # Only Loading...
        }
```
Thank you,

**Comment by dstillman** [comment]
There's no way to replicate clicks in tests. They depend on proper URLs.

**Comment by rkoyama1623** [comment]
I see, thank you.
