### ISSUE TITLE
[Feature request] More categories for arxiv translator

### ISSUE THREAD

**Issue by xju2** [zotero/translators#2228]
Hi there,

I am from the physics community and always use bibtex to organize my references. In our fields the arxiv pre-print files are very important and we cite them as follows. Take https://arxiv.org/abs/1803.03324 as an example: 

@article{li2018learning,
    title= "{Learning Deep Generative Models of Graphs}",
    author= "{Yujia Li and Oriol Vinyals and Chris Dyer and Razvan Pascanu and Peter Battaglia}",
    year= "{2018}",
    eprint= "{1803.03324}",
    archivePrefix= "{arXiv}",
    primaryClass= "{cs.LG}"
}

I am asking to add categories "eprint", "archivePrefix" and "primaryClass" into the arxiv translator along with the existing "author", "title" and et.al. 

Thanks
Xiangyang

**Comment by adam3smith** [comment]
I don't quite understand -- this is imported as `arXiv:1803.03324 [cs, stat]` which covers all of this except the LG

**Comment by xju2** [comment]
With current Zotero version 5.0.89, the exported bibtex is the following:
```
@article{liLearningDeepGenerative2018,
	title = {Learning {Deep} {Generative} {Models} of {Graphs}},
	url = {http://arxiv.org/abs/1803.03324},
	language = {en},
	urldate = {2020-04-27},
	journal = {arXiv:1803.03324 [cs, stat]},
	author = {Li, Yujia and Vinyals, Oriol and Dyer, Chris and Pascanu, Razvan and Battaglia, Peter},
	month = mar,
	year = {2018},
	note = {arXiv: 1803.03324}
}
```
It would be improper in academic because arxiv is not a journal nor a publication. Papers in arxiv are public, which do not make them publications. It would be nice to make such exporting to bibtex *automatically* be the way I quote before should it not create too many troubles/changes.

**Comment by adam3smith** [comment]
Currently that's not possible. Once we have a dedicated item type for pre-prints, we could consider this, but I'm quite skeptical of the eprints et al. bibtex fields, which I don't think are particularly standard/standardized, so they'll be ignored in the vast majority of .bst styles.
