### ISSUE TITLE
IOS Press Translator Missing

### ISSUE THREAD

**Issue by MirkoLenz** [zotero/translators#2237]
It is not possible for me to import papers that are published by IOS Press, for example <http://ebooks.iospress.nl/publication/55356>. As far as I can tell, there is currently no translator for this site available. When trying to import this paper, the Zotero Connector reports an unknown error.

What I do not understand is that it is also not possible to directly import the paper using the DOI directly in Zotero (in this case, 10.3233/FAIA200490). Zotero just says that there was an error. Is this to be expected if there is no translator for a site? I thought that it should still be possible to import a document using its DOI based on its information in CrossRef?

Thank you in advance!

**Comment by AbeJellinek** [comment]
I think this issue was on your end. It works fine now.
