### ISSUE TITLE
ACM Digital Library: remove formatting in titles

### ISSUE THREAD

**Issue by anjiro** [zotero/translators#2238]
HTML formatting should be stripped from titles: importing https://dl.acm.org/doi/abs/10.1145/1858171.1858205 gives a title of `Bosu: <i>a physical programmable design tool for transformability with soft mechanics</i>`

**Comment by adam3smith** [comment]
That's tricky -- HTML is used for rich text formatting (italics, sub/superscripts) and we'd want to keep that sort of information. It's unclear to me why the italics are in that title.

**Comment by dstillman** [comment]
Yeah, this is correct behavior given the title presented on the site. Rich text is used in bibliographic output, and a future version of Zotero will render it properly within the app.
