### ISSUE TITLE
NASA NTRS Translator Not Working

### ISSUE THREAD

**Issue by polmes** [zotero/translators#2240]
The Zotero Translator for the Chrome extension no longer works on NTRS (NASA Technical Reports Server) since they updated the site.
Example: https://ntrs.nasa.gov/citations/19680021973 (it will only allow you to take a snapshot of the site, but not the full text or the citation)

**Comment by jhaiduce** [comment]
Doesn't work in the Firefox extension either.

**Comment by AbeJellinek** [comment]
Working on this! Thanks for reporting and sorry it's taken a while to get to.

**Comment by AbeJellinek** [comment]
Alright, revamped the translator to support the new site. Please give it a try and let me know if you encounter any issues.
