### ISSUE TITLE
Run linting in feature branches?

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2299]
I don't know if this is a question or a feature request, but when I run `npm run --lint -- FILENAME` in any branch other than master, the script throws an error. Since I typically commit from feature branches (and most other people should as well), that's a hassle. 
Is there a trick I'm missing that allows running them off master? If not, how hard would it be to make that possible?

**Comment by AbeJellinek** [comment]
The command should be `npm run lint -- FILENAME` (`lint`, not `--lint`), but otherwise I can't reproduce this on my end. Is it still not working for you?
