### ISSUE TITLE
Innopac translator fails when MARC link isn't found

### ISSUE THREAD

**Issue by owcz** [zotero/translators#2311]
Instead of resorting to some other fallback/lookup, the Innopac translator fails on the following two links. Scaffold shows, in response: "Error: MARC link not found"
* https://catalog.nypl.org/record=b13383222
* https://catalog.nypl.org/record=b16299882~S1

Note that the translator is still working with other entries in the same catalog. These are just two tested examples of where the translator resorts to Embedded Metadata instead of, e.g., IBSN lookup

**Comment by AbeJellinek** [comment]
I've tested a bunch of InnoPAC installs, and only NYPL's legacy catalog seems to have this issue. Even the two links you provided now redirect to the new research catalog (which we have a separate translator for). Do you know of another site where this comes up?

**Comment by owcz** [comment]
Nope, just this one, so sounds like it's resolved! Thanks!

**Comment by AbeJellinek** [comment]
No problem! Thanks for reporting the issue. I guess NYPL was just doing something odd.
