### ISSUE TITLE
bug in BibTeX import: tilde in URL field translated to space

### ISSUE THREAD

**Issue by dfkotz** [zotero/translators#2313]
This issue results from a [forum post](https://forums.zotero.org/discussion/comment/371129#Comment_371129), in which @adam3smith suggested I create this issue.

I recently joined Zotero and created a [profile library](https://www.zotero.org/dfkotz/library).

To do so, I used Zotero desktop (5.0.93 for MacOS) to import a BibTeX file containing all my papers; each entry includes a "URL" field with a link to my web page for that paper. All of those web pages live at a URL like this: `https://www.cs.dartmouth.edu/~kotz/research/papers.html`

Unfortunately, Zotero translated the tilde character to a space character. This is incorrect behavior (tilde is a valid and common character within URLs) and is therefore a bug. 

I tried wrapping the URL field in an extra layer of {braces} (by analogy to a protective syntax often used in Title and Booktitle fields) but it had no effect. 

Attached is an example of one of the entries I imported, exactly as provided during import:
[kotz-example.bib](https://github.com/zotero/translators/files/5730464/kotz-example.bib.txt)
(uploaded as .txt because github doesn't like .bib extension).

**Comment by retorquere** [comment]
The URL field should be parsed in verbatim mode.

**Comment by dfkotz** [comment]
Makes sense to me.

**Comment by dfkotz** [comment]
Any progress on this bug?

**Comment by retorquere** [comment]
BBT will import it correctly if you need to import it now.

**Comment by dfkotz** [comment]
Thank you.  How do I re-import all my bibtex so Zotero will update the existing records?  I have about 400 such entries.

**Comment by retorquere** [comment]
I'm afraid there is no easy way to achieve this. The duplicate-detection feature in Zotero will help, but BBT is not guaranteed to create items of the same types, and when all data is the same but the types differ, Zotero won't see them as potential duplicates (I think?). A javascript-runner script could perhaps do something more directed because you could feed it e.g. titles and authors, but it'd be a bit of work to create that. B

If there's nothing else in your library, or they are all under a single collection, it may be easier to delete them and re-import with BBT or with the standard BibTeX importer once it gets updated; even if the standard Zotero importer is fixed, you will still have the dedup problem.

**Comment by dfkotz** [comment]
Ok, I understand I have two options right now.

1. live with broken links until Zotero fixes its own importer.
2. erase my current library, install BBT plug-in for Zotero, and re-import current and future records via BBT instead of native Zotero.

**Comment by adam3smith** [comment]
Our updated importer (I have a fix ready, just need to finalize the PR) won't help you update existing items either, I'm afraid. So your choices are:
1) live with broken links and gradually fix them by hand and/or with Zutilo (that might be worth looking into: Zutilo can do batch search&replace on filepaths)
2) Erase current library and re-import with BBT or in a couple of days when our fix is live

**Comment by dfkotz** [comment]
Thanks.  I’ll wait for your fix.

**Comment by dfkotz** [comment]
Just updated to 5.0.95.2, which is not described in the [changelog](https://www.zotero.org/support/changelog); in any case, I don't see this issue/bug mentioned in the changelog.   May I assume I'll receive notice when this fix goes live - because this issue will be closed?

**Comment by retorquere** [comment]
Zotero updates independently from the translators.

**Comment by adam3smith** [comment]
Yes. Translator updates are independent of version releases.

**Comment by dfkotz** [comment]
Ok. So how will I know when this translator is updated *within Zotero*?  or how do I nudge that along?

**Comment by dstillman** [comment]
When this is merged

**Comment by adam3smith** [comment]
Just in case this wasn't clear from the above, though: if you're in a rush, there's really no reason for you to wait on the built-in translator to be fixed. The BBT add-on handles this exactly the way a fixed built-in translator will and is widely used and reliable.
