### ISSUE TITLE
BibTeX: Skip preamble

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2318]
Reported here: https://forums.zotero.org/discussion/86830/report-id-800927781-importing-calibre-generated-bibtex-file-failed#latest

Preamble is rare, but looks like valid bibtex. For Zotero purposes, we should just skip an entry that starts with `@preamble{`

**Comment by retorquere** [comment]
`@preamble` is indeed valid bibtex. BBT by and large ignores it, except that it parses out a limited form of `\newcommand` so that things like [\mnras](https://forums.zotero.org/discussion/comment/371238) can be expanded upon import. Very niche case likely.
