### ISSUE TITLE
Translator Request: WorldCat Discovery Modernized interface

### ISSUE THREAD

**Issue by ericbradley** [zotero/translators#2320]
Hello. 

OCLC's WorldCat Discovery is currently developing a "[modernized interface](https://www.oclc.org/en/news/announcements/2020/worldcat-discovery-interface-modernization.html)" that will replace the current interface this summer. The overhaul of the system breaks the existing WorldCat Discovery translator. A example of this new interface is available at [](https://goshen.on.worldcat.org/v2)

**Comment by adam3smith** [comment]
You left out the link to the new interface demo ;)

**Comment by ericbradley** [comment]
My apologies. Here it is:

[](https://goshen.on.worldcat.org/v2)
