### ISSUE TITLE
Twitter translator fails on specific tweets

### ISSUE THREAD

**Issue by rmzelle** [zotero/translators#2323]
https://twitter.com/PatSchloss/status/1346139830615494664 won't save for me with the Twitter translator:

![image](https://user-images.githubusercontent.com/77951/104104074-db5db400-5273-11eb-8d31-b6643f767a3a.png)

Other tweets save fine. Zotero 5.0.94, Firefox 84.0.2 (64-bit).

**Comment by dstillman** [comment]
Fixed, thanks!
