### ISSUE TITLE
CI: driver.get("chrome://system") returns empty page when Chrome is started with --headless

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2330]
https://github.com/zotero/translators/runs/1797219484?check_suite_focus=true

@adomasven: Any idea what's going on here?

At first Chrome wasn't opening under GitHub Actions, so I added `"--no-sandbox", "--disable-dev-shm-using", "--headless"`, which got it to start. But now ChromeDriver is timing out trying to extract the extension id from `chrome://system`, and `driver.getPageSource()` shows `<html><head></head><body></body></html>`. (Same for `chrome://extensions`.) Did you see that at any point while you were setting this up?

https://github.com/zotero/translators/commits/github-actions-test

**Comment by adomasven** [comment]
I didn't. If this isn't working locally, I wouldn't imagine it would work under GitHub Actions. I'm not sure if the translator tests even work headless at all.

**Comment by dstillman** [comment]
I'm not sure it's `--headless` — I don't know why that cause chrome://system specifically to be empty. HTTP URL source shows up fine.

**Comment by dstillman** [comment]
Hmm, it is. Locally without `--headless` that URL works.

**Comment by dstillman** [comment]
So if we can't figure out how to get chrome://system to work headless, and can't extract the extension id any other way, we need to figure out how to get Chrome to run normally on GitHub Actions. xvfb is present, so headless shouldn't be necessary, but it was failing with "DevToolsActivePort file doesn't exist", and these arguments were the most commonly given fix.

I'll keep working on it.

**Comment by dstillman** [comment]
OK, then:

> Most chrome internal pages are not implemented in headless mode. This is a limitation of headless Chrome itself, and is not related to ChromeDriver. If you need a particular internal page available in headless Chrome, please file a feature request at https://crbug.com/.

From https://groups.google.com/g/chromedriver-users/c/UbgIiMycjWs/m/fvk8jadcBQAJ
