### ISSUE TITLE
NASA ADS verbatim citation export

### ISSUE THREAD

**Issue by HNLala** [zotero/translators#2332]
I am using Zotero with Better Bibtex and have requested the following feature at BBT's repo [(issue1773)](https://github.com/retorquere/zotero-better-bibtex/issues/1733#issuecomment-772811213) as well as I am not sure under whose purview this lies.

I noticed a difference in how the exports work based on how I was importing the reference. 

**Case A**:
If I use the Zotero connector and save the reference using the Firefox addon on this page (https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J/abstract), BBT exports the following citation:
```

@article{ji2020_SouthernStellarStream,
  title = {The {{Southern Stellar Stream Spectroscopic Survey}} ({{S5}}): {{Chemical Abundances}} of {{Seven Stellar Streams}}},
  shorttitle = {The {{Southern Stellar Stream Spectroscopic Survey}} ({{S5}})},
  author = {Ji, Alexander P. and Li, Ting S. and Hansen, Terese T. and Casey, Andrew R. and Koposov, Sergey E. and Pace, Andrew B. and Mackey, Dougal and Lewis, Geraint F. and Simpson, Jeffrey D. and {Bland-Hawthorn}, Joss and Cullinane, Lara R. and Da Costa, Gary. S. and Hattori, Kohei and Martell, Sarah L. and Kuehn, Kyler and Erkal, Denis and Shipp, Nora and Wan, Zhen and Zucker, Daniel B.},
  year = {2020},
  month = oct,
  volume = {160},
  pages = {181},
  issn = {0004-6256},
  doi = {10.3847/1538-3881/abacb6},
  url = {http://adsabs.harvard.edu/abs/2020AJ....160..181J},
  urldate = {2021-02-03},
  journal = {The Astronomical Journal}
}

```

On the other hand, if I copy the citation from the clipboard in the format described here taken from the 'Export Citation' setion at ADS (https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J/exportcitation)

**Case B:**
```
@ARTICLE{2020AJ....160..181J,
       author = {{Ji}, Alexander P. and {Li}, Ting S. and {Hansen}, Terese T. and {Casey}, Andrew R. and {Koposov}, Sergey E. and {Pace}, Andrew B. and {Mackey}, Dougal and {Lewis}, Geraint F. and {Simpson}, Jeffrey D. and {Bland-Hawthorn}, Joss and {Cullinane}, Lara R. and {Da Costa}, Gary. S. and {Hattori}, Kohei and {Martell}, Sarah L. and {Kuehn}, Kyler and {Erkal}, Denis and {Shipp}, Nora and {Wan}, Zhen and {Zucker}, Daniel B.},
        title = "{The Southern Stellar Stream Spectroscopic Survey (S$^{5}$): Chemical Abundances of Seven Stellar Streams}",
      journal = {\aj},
     keywords = {Globular star clusters, Stellar abundances, Dwarf galaxies, Milky Way stellar halo, 656, 1577, 416, 1060, Astrophysics - Solar and Stellar Astrophysics, Astrophysics - Astrophysics of Galaxies},
         year = 2020,
        month = oct,
       volume = {160},
       number = {4},
          eid = {181},
        pages = {181},
          doi = {10.3847/1538-3881/abacb6},
archivePrefix = {arXiv},
       eprint = {2008.07568},
 primaryClass = {astro-ph.SR},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```

In this case, BBT pins the incoming citekey automatically (which I just unpin and then it works as expected) but the rest of the keywords are transferred as expected. The BBT export is:

```
@article{2020AJ....160..181J,
  title = {The Southern Stellar Stream Spectroscopic Survey (S{$^5$}): {{Chemical}} Abundances of Seven Stellar Streams},
  author = {Ji, Alexander P. and Li, Ting S. and Hansen, Terese T. and Casey, Andrew R. and Koposov, Sergey E. and Pace, Andrew B. and Mackey, Dougal and Lewis, Geraint F. and Simpson, Jeffrey D. and {Bland-Hawthorn}, Joss and Cullinane, Lara R. and Da Costa, Gary. S. and Hattori, Kohei and Martell, Sarah L. and Kuehn, Kyler and Erkal, Denis and Shipp, Nora and Wan, Zhen and Zucker, Daniel B.},
  year = {2020},
  month = oct,
  volume = {160},
  pages = {181},
  doi = {10.3847/1538-3881/abacb6},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System},
  adsurl = {https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J},
  archivePrefix = {arXiv},
  eid = {181},
  eprint = {2008.07568},
  eprinttype = {arxiv},
  journal = {\aj},
  number = {4},
  primaryClass = {astro-ph.SR}
}
```

I understand if this might be too idealistic, but what I hope can be possible is:
1. I use the Zotero Connector on the page: https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J/abstract and it creates a new entry for this reference and attaches the related PDF.
2. It recovers all the fields listed here (in the 'Export Citation' section, that is): https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J/exportcitation
3. The exported citation looks like this:

```
@article{ji2020_SouthernStellarStream,
  title = {The Southern Stellar Stream Spectroscopic Survey (S{$^5$}): {{Chemical}} Abundances of Seven Stellar Streams},
  author = {Ji, Alexander P. and Li, Ting S. and Hansen, Terese T. and Casey, Andrew R. and Koposov, Sergey E. and Pace, Andrew B. and Mackey, Dougal and Lewis, Geraint F. and Simpson, Jeffrey D. and {Bland-Hawthorn}, Joss and Cullinane, Lara R. and Da Costa, Gary. S. and Hattori, Kohei and Martell, Sarah L. and Kuehn, Kyler and Erkal, Denis and Shipp, Nora and Wan, Zhen and Zucker, Daniel B.},
  year = {2020},
  month = oct,
  volume = {160},
  pages = {181},
  doi = {10.3847/1538-3881/abacb6},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System},
  adsurl = {https://ui.adsabs.harvard.edu/abs/2020AJ....160..181J},
  archivePrefix = {arXiv},
  eid = {181},
  eprint = {2008.07568},
  eprinttype = {arxiv},
  journal = {\aj},
  number = {4},
  primaryClass = {astro-ph.SR}
}
```

In the desired format, every field except the citekey is identical to the incoming citation. Instead of importing the fields in its usual way, it will be great if Zotero lifts these fields verbatim from the 'Export Citation' section. Having the exported keywords identical to those in ADS citation will be immensely helpful.

**Comment by adam3smith** [comment]
Yeah, sorry, that's likely just not going to work. BBT does some magic to conserve custom bibtex fields such as primaryClass and adsurl between import and export, but since these fields have literally no meaning for Zotero, we're not going to import them into Zotero (nor could we do so in a meaningful way). 
I would expect us to get the keywords, though, so can check on why that's not the case.

**Comment by HNLala** [comment]
I understand. Thanks, anyway.
However, will it be possible for Zotero to recover at least the arXiv fields like eprint and eprinttype when I am using the Zotero Connector and not clipboard-copying the citation?
