### ISSUE TITLE
Update identifier for an OJS journal article

### ISSUE THREAD

**Issue by klausru** [zotero/translators#2334]
Dear all
both of these methods to reliably identify an OJS journal article seem to be outdated
https://github.com/zotero/translators/blob/573a963d31c439b600f122a1123aced4b9c6c040/Open%20Journal%20Systems.js#L39-L41

I would suggest to simply add/replace something like
`	if (ZU.xpathText(doc, '//meta[@name="generator"]/@content') == 'Open Journal Systems 3.2.1.3'` 
I am not sure how to wildcard the version number. So please add to this.

All the best
Klaus

**Comment by AbeJellinek** [comment]
Hey, thanks for reporting this! Could you give an example of a page that isn't detected correctly right now?

**Comment by klausru** [comment]
Hey @AbeJellinek 
after refreshing the translators in the advanced settings tabs of the zotero-connector plugin more journals are being detected properly.
But these ones for example are not being recognised:
https://www.revistacomunicar.com/ojs/index.php/comunicar/article/view/C67-2021-02
https://journal.meteohistory.org/index.php/hom/article/view/79

**Comment by AbeJellinek** [comment]
This should be fixed now. Thanks for pointing the issue out!
