### ISSUE TITLE
Problem with "Microbiology Society Journals.js"

### ISSUE THREAD

**Issue by rmzelle** [zotero/translators#2355]
Saving for the following URL (which I happened upon via Google Scholar) failed, but removing the query string solves the issue.

https://www.microbiologyresearch.org/content/journal/ijsem/10.1099/ijsem.0.004683?crawler=true
\> recognized by translator, but saving fails silently

https://www.microbiologyresearch.org/content/journal/ijsem/10.1099/ijsem.0.004683
\> works

By staring at the code, it seems to me that the URL isn't sanitized (to remove the query string) before manipulation to get to the RIS:

https://github.com/zotero/translators/blob/9a3dcb238f125cfefb2fe8c1682c829fcfd3bbf9/Microbiology%20Society%20Journals.js#L89

**Comment by dstillman** [comment]
Fixed in 6169f9e2cdb979377f687a01b9e5d55f11456049

**Comment by rmzelle** [comment]
Thanks for the super-quick fix!
