### ISSUE TITLE
Recognize mobile wikipedia links as wikipedia

### ISSUE THREAD

**Issue by natejlong** [zotero/translators#2366]
Mobile wikipedia links don't default to being saved via the Wikipedia translator when they should be treated identically.

Desktop link (correctly recognized by the Zotero Firefox Connector as a Wikipedia article):
https://en.wikipedia.org/wiki/1%25_rule_(Internet_culture)

Mobile link (defaults to COinS instead)
https://en.m.wikipedia.org/wiki/1%25_rule_(Internet_culture)

I'm guessing this is just an issue with the target regex over at https://github.com/zotero/translators/blob/master/Wikipedia.js#L5

Anyone with more knowledge able to confirm this?

**Comment by dstillman** [comment]
@natejlong: Fixed — thanks for reporting. (Your Zotero Connector should auto-update within 24 hours, or you can update manually by clicking Update Translators in the Advanced pane of the Zotero Connector preferences.)

**Comment by natejlong** [comment]
Thank you!
