### ISSUE TITLE
Twitter translator fails on "share" links

### ISSUE THREAD

**Issue by rmzelle** [zotero/translators#2369]
Don't judge, but I often share tweets from my iPhone with myself via the Gmail app. These URLs look like https://twitter.com/aerospacecorp/status/1391160460150382598?s=27 (per https://twitter.com/mattnavarra/status/1044147538922803201, these `?s=27` type suffixes indicate the sharing mechanism, e.g. I see `?s=10` when I share the same tweet via iMessage).

These tweets trip up the Zotero Twitter translator at https://github.com/zotero/translators/blob/b89f99c88a1f33e7f64d4a47fe7369fcfe545e8f/Twitter.js#L99, since these shared tweets don't include a "Tweet source label" URL (https://help.twitter.com/en/using-twitter/how-to-tweet#source-labels). I haven't looked for possible fixes.

Doesn't work:
https://twitter.com/aerospacecorp/status/1391160460150382598?s=27
![image](https://user-images.githubusercontent.com/77951/117559436-3b623c80-b053-11eb-9a74-89993b6bd170.png)

Works (same tweet at canonical URL):
https://twitter.com/AerospaceCorp/status/1391160460150382598
![image](https://user-images.githubusercontent.com/77951/117559457-6056af80-b053-11eb-80a5-14c6d48a7c65.png)

**Comment by dstillman** [comment]
Need to test a little more but I should have a fix for this later today.

**Comment by rmzelle** [comment]
Thanks again for the super quick fix!
