### ISSUE TITLE
Retsinformation broken after re-design

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2397]
Reported: https://forums.zotero.org/discussion/89972/translator-help-request-www-retsinformation-dk#latest
Redirects from test URLs work, so can use the data in tests as a template. The new site has very nice XML metadata linked to in the page header and also available by adding `/dan/xml` to the URL

We could also look at how widespread `eli:` type metatags for legal resources are (I assume that stands for electronic law information or so). This might be a EU-wide thing, which would be cool.

**Comment by AbeJellinek** [comment]
It's really unfortunate that the `eli:` tags are generated by React and don't exist in the static HTML! Either way, I'll work on this.

**Comment by AbeJellinek** [comment]
Ah, missed that it's the same data available at `/dan/xml`. Great.

**Comment by SimonSHansen** [comment]
@AbeJellinek just want to thank you for looking in to this. Retsinformation is a used very frequently for legal citations, so it will be great, when it works properly with Zotero again!

**Comment by adam3smith** [comment]
@AbeJellinek as you look into ELI maybe check out some of the other implementations listed here: https://eur-lex.europa.eu/eli-register/implementation.html -- would be cool to write this in a way to take advantage of the ontology across multiple sites
