### ISSUE TITLE
CI: `get_translators_to_check` fails

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/translators#2401]
Failing line is https://github.com/zotero/translators/blob/master/.ci/helper.sh#L55.

Example failure is https://github.com/zotero/translators/pull/2381/checks?check_run_id=2713541551.

The commit that it's trying to fetch the `rev-list` for (d968b5cdf28cc4eba205c9937f21c5eeabf84a16) isn't the parent of the commit being tested, so `first_parent` must be getting the wrong value. But how?

**Comment by dstillman** [comment]
We've had a [ton of trouble](https://github.com/zotero/translators/commits/master/.github/workflows/ci.yml) with this, though usually it happens on branches that have been rebased, which I don't think is the case here?

I don't remember the details, but it might be an issue with the number of commits between master and when this was branched off. We could try increasing this arbitrary 25 to something higher:

https://github.com/zotero/translators/blob/e09dfc27798b9063a0e5d8b5f5052c1f6743d492/.github/workflows/ci.yml#L17

**Comment by AbeJellinek** [comment]
Yeah, no rebases on branches where I'm having this issue. Might as well try 50, I guess.
