### ISSUE TITLE
Baidu Scholar returns no items

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/translators#2432]

**Comment by boan-anbo** [comment]
Abe are you working on this? If no one I can try fixing it. (I speak Chinese).

**Comment by AbeJellinek** [comment]
If you'd like to give it a try, please do. It seems like the citation export feature we were using might've broken, and I was having trouble finding where it's gone, mostly because of the language barrier.

**Comment by boan-anbo** [comment]
Just did a quick and dirty fix. Please advise.

**Comment by AbeJellinek** [comment]
Fixed via #2460
