### ISSUE TITLE
Journal articles no longer recognized on ASM journal websites after redesign

### ISSUE THREAD

**Issue by rmzelle** [zotero/translators#2455]
The American Society for Microbiology (ASM) recently redesigned its website, and journal articles are no longer recognized as such and currently save as webpages.

Example URL: https://journals.asm.org/doi/10.1128/mSystems.00283-21
DOI: https://doi.org/10.1128/mSystems.00283-21
PubMed: https://pubmed.ncbi.nlm.nih.gov/34061588/

![image](https://user-images.githubusercontent.com/77951/121834675-56048280-cc9d-11eb-9564-39199bd69503.png)

**Comment by rmzelle** [comment]
Looks like the redesign went live on May 25th (https://journals.asm.org/migration-information)

**Comment by adam3smith** [comment]
New version is using Atypon, so should be pretty quick to adapt that, although unfortunately the names are given as "Lastname Firstnames" (without comma...) in the RIS.

**Comment by rmzelle** [comment]
@adam3smith, @AbeJellinek, thanks!
