### ISSUE TITLE
NASA ADS broken

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2457]
https://ui.adsabs.harvard.edu/abs/2022MSSP..16208010Y/abstract

> [JavaScript Error: "HTTP GET http://adsabs.harvard.edu/cgi-bin/nph-bib_query?2022MSSP..16208010Y&data_type=REFMAN&nocookieset=1 failed with status code 404"]

Falls back to Embedded Metadata with OA PDF.

**Comment by adam3smith** [comment]
(note that there is another NASA ADS ticket if you're looking into this: https://github.com/zotero/translators/issues/2111 )

**Comment by AbeJellinek** [comment]
Alright, I'll figure this out today.
