### ISSUE TITLE
GitHub Discussions: Translator error, perhaps needs to be filtered out

### ISSUE THREAD

**Issue by jryans** [zotero/translators#2490]
GitHub discussions pages (such as https://github.com/MobileNativeFoundation/discussions/discussions/6) have a quite a different structure from a repo or issue. At the moment, they cause an error in the translator and it falls back to EM.

The existing GitHub translator seems meant for repo root pages, so perhaps the target URL needs to be more specific to avoid things like discussions...?

**Comment by AbeJellinek** [comment]
We started covering all repo pages because of [this issue](https://github.com/zotero/translators/issues/2390). That GitHub bug might be fixed now. I'll take a look and see if we can scale the translator's scope back again.
