### ISSUE TITLE
Tweets: forum posts or blog posts?

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/translators#2579]
We currently scrape tweets as blog posts, but [the wiki](https://www.zotero.org/support/kb/item_types_and_fields) recommends classifying them as forum posts:

Forum Post | A post on an online discussion forum. Also use this type for items such as Facebook posts or tweets.
-- | --

It seems like either the translator or the documentation should change.

**Comment by AbeJellinek** [comment]
@adam3smith thoughts on this?

**Comment by bwiernik** [comment]
Agreed. forumPost for social media posts is a better fit
