### ISSUE TITLE
Adjust target URL for beck-online

### ISSUE THREAD

**Issue by errotu** [zotero/translators#2598]
First of all, thank you for the great work done here (in particular @zuphilip)!
Unfortunately, the beck-online translator stopped working for me since I am accessing the site now via a webvpn of my university. The URL has changed from
> https://beck-online.beck.de/

to

> https://beck-online-beck-de.ubproxy.ub.uni-heidelberg.de

Since that, Zotero does not recognize articles on beck-online as articles anymore.
If I'm not mistaken, the removal of the dot in front of the second "beck" in the target URL could fix it without any further troubles.

Also, would it be possible to integrate the beck-online PDF download? The URL to the PDF is
> https://beck-online.beck.de/Print/CurrentMagazine?vpath=[vpath]&printdialogmode=CurrentDoc&actionname=Index&gesamtversionpath=&exportFormat=pdf&options=WithLinks

That would be great feature!

**Comment by dstillman** [comment]
Detection of proxied URLs isn't dealt with at the translator level — that's handled by the connector itself. But the hyphen here might complicate things. Have you tried manually entering `beck-online.beck.de` as a host entry for your proxy in the Proxies pane of the Zotero preferences?

@adomasven: Do we do anything special to try to handle domains that already include hyphens for proxy detection?

**Comment by errotu** [comment]
I've not yet configured the proxy in the connector since it didn't work well at sometime in the past (but I don't really remember what the problem was). 

It might be a dirty solution but changing the target URL to 

> ^https?://beck-online.beck.de

actually worked for me (since the dots are becoming single character wildcards).

However, I'll take a closer look into the proxy solution tomorrow. Thanks for the advice!

**Comment by dstillman** [comment]
The proxy should generally be auto-configured, but if it wasn't, or you said no or removed it, you definitely will want to configure that. Again, detection of proxied URLs is not done in translators — target regexes are written for unproxied URLs — and most proxied sites won't be detected if you don't have a proxy configured. That wouldn't have anything to do with Beck specifically.

The only way this situation might be different is because of the hyphen in the URL, since EZproxy's mechanism for HTTPS domain rewriting uses hyphens, but Adomas will have to comment on that.

**Comment by errotu** [comment]
I just tried it and the proxy itself works like a charm. However, unfortunately, the translator doesn't seem to recognize the proxied page and only offers to save articles as webpage (and not as journal article).

**Comment by AbeJellinek** [comment]
I can reproduce this, unfortunately! I guess EZproxy developers didn't account for hyphens in domain names. Considering that this situation is relatively rare (I don't know that we support any hyphenated sites besides beck-online), it might be worth adding a workaround to the translator's target just in this case.

**Comment by errotu** [comment]
Thanks a lot for the fix!

**Comment by AbeJellinek** [comment]
No problem!
