### ISSUE TITLE
Research Square article not detected

### ISSUE THREAD

**Issue by rmzelle** [zotero/translators#2599]
@AbeJellinek, I saw you recently added a translator for Research Square in #2563, but the translator isn't activated for https://www.researchsquare.com/article/rs-762539/v1 (it uses the "Embedded Metadata" translator instead for me in Firefox). Could you take a look to see what's going wrong here? Thanks a bunch!

**Comment by dstillman** [comment]
That's working for me. Try resetting your translators in Zotero and updating them in the Zotero Connector preferences.

**Comment by rmzelle** [comment]
Awesome, that worked. I tried updating my translators via the Zotero client preferences panel, which didn't help, but these steps did.

**Comment by dstillman** [comment]
OK, great. Most likely your Zotero just missed a translator update and would've gotten it in the next app update. We're going to be making some changes to make translator updating a bit more robust — it's been having a bit of trouble keeping up with new users and all the translator updates @AbeJellinek has been cranking out.
