### ISSUE TITLE
WHO ISBN search translator

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2617]
https://forums.zotero.org/discussion/91092/whos-iris-pdf-metadata-automatic-citation-download-anyone-would-want-to-develop

I think we can just reject detection when the ISBN doesn't start with "978924". (This seems like something we should do for more things?)

I think we can just put this in the existing WHO translator and make it translatorType 12.

**Comment by AbeJellinek** [comment]
We don't want to use EM in a search translator, do we? Do they have an API that we aren't using? Ideally we won't have to do screen scraping for this.

**Comment by AbeJellinek** [comment]
I'll look into it, though.

**Comment by dstillman** [comment]
I don't see why it'd be a problem. We'd only be scraping when we had what appeared to be a valid WHO ISBN, so it wouldn't affect other lookups.

If someone pasted 100 WHO ISBNs into Add Item by Identifier, I guess that wouldn't be ideal and maybe they'd get throttled, but it could easily be the same with an API — if anything, we should be rate-limiting all lookup requests to the same domain.

**Comment by dstillman** [comment]
(I don't know if they have any sort of API, though.)
