### ISSUE TITLE
Request to read new attribute to support Zotero for  Primo Full record display 

### ISSUE THREAD

**Issue by nilinatan** [zotero/translators#2626]
This issue refers to Primo Translator 2018 

In Primo we are adding new attribute to support better export to Zotero in case of Primo Full record display .
Today Primo translator uses the class urlToXmlPnx in order to read Primo records metadata when exporting to Zotero, this class was used both in Primo brief results and in Primo Full record display. 

Due to a change we have done in the application, we are adding new class called to support Primo Full record display when it is opens as an overlay on top of the Primo brief results  
The new class is **urlToXmlPnxSingleRecord**

Our request is to change the Primo translator to support also the new class and give it priority , that means if a Primo Full Record display is opened on top of the brief results , you will be able to see both classes 
-  urlToXmlPnxSingleRecord - showing the metadata for the current displayed record
- urlToXmlPnx  - show for each record in the brief results pointer to its Primo record
In such case you should give priority to the urlToXmlPnxSingleRecord and read only its data
To clarify if the full display is closed or you see only the Primo search results the exiting attribute **urlToXmlPnx**   should still be supported and used.

To see this change you can use link to our QA environment 
- https://primo-qa.hosted.exlibrisgroup.com/primo-explore/search?query=any,contains,sea&tab=default_tab&search_scope=default_scope&vid=CTWCC&offset=0&noCustomization=true
- Click on one of record in the results list
-  see in the HTML the new attribute to support
![image](https://user-images.githubusercontent.com/16845055/129004728-e145c03e-368a-4587-b5e6-74810290f2db.png)

Currently if new attribute is not supported zotero exports all the records within the brief results
To fix this issue we have added the new attribute

Timeline - new attribute will be in production starting of October 2021 release, this is why we share with you link to our QA

please let us know if there more details to provide

Best Regards
Nili Natan
Product Manager of Discovery & Delivery 
nili.natan@exlibrisgroup.com

-

**Comment by AbeJellinek** [comment]
Great, thank you. I've been looking to fix the single item overlay still being detected as a multiple, so this will be a big help.

**Comment by AbeJellinek** [comment]
I found one issue with the new feature: if you click an item to open the details overlay, close the overlay, and then click the *same* item to open the overlay again, no `.urlToXmlPnxSingleRecord` element is created.

**Comment by nilinatan** [comment]
@symac we have two deployment flavor for Primo : Primo and Primo VE , for Primo VE this is available with October release , for Primo customers it is available starting November release which is currently being deployed to all customers gradually.
this is example for Primo customer that is already in November release : https://search.library.uq.edu.au/primo-explore/fulldisplay?docid=61UQ_ALMA21266209920003131&context=L&vid=61UQ&lang=en_US&search_scope=61UQ_All&adaptor=Local%20Search%20Engine&tab=61uq_all&query=any,contains,water&sortby=rank&facet=rtype,exclude,newspaper_articles,lk&facet=rtype,exclude,reviews,lk&offset=0 where you can see the SingleRecord indication .

The customer you refer to will be installed within the next few weeks https://babordplus.hosted.exlibrisgroup.com/primo-explore/search?vid=33PUDB_UBM_VU1
