### ISSUE TITLE
Add `ADS Bibcode: [code]` to Extra field

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2631]
It's technically in the URL but seems good to keep identifiers around in an easily accessible manner.

Follow-up to #2529

**Comment by AbeJellinek** [comment]
I just opened a PR for this. I hadn't seen this issue yet. Scary.

That aside, I'm putting it in `Citation Key` because it seems like that's the common workflow when working with ADS sources. How does that seem to you?

**Comment by AbeJellinek** [comment]
I'm getting that it's a common workflow from the forum discussion, [specifically](https://forums.zotero.org/discussion/comment/386307/#Comment_386307):

> The ADS Bibcodes are thus very commonly used because it is literally the Bibtex cite key for a particular publication.

**Comment by dstillman** [comment]
Hmm, I think I would put it in both, then, even if it's a bit redundant. There's a good chance we'll gain more flexible ID support at some point — think many-to-one identifiers for an item — and ADS Bibcode should probably be one of those, along with all the other supported identifiers. It'd be useful for things like metadata updating without needing to follow the URL.

Someone could also have a citation key format that they prefer and want to change the Citation Key field without losing the identifier. (Maybe in astrophysics people always stick to the Bibcode for the citation key, but on principle it still seems like it should be separate.)

**Comment by AbeJellinek** [comment]
OK, added.
