### ISSUE TITLE
Web of Science Nextgen not working in proxied WOS site

### ISSUE THREAD

**Issue by mplentzez** [zotero/translators#2674]
We noticed that the translator is not being called in the proxied version of Web of Science new interface, like for instance:

Here the plugin works: https://www.webofscience.com/wos/woscc/summary/b6af48af-aa29-43ac-a91f-1cd9e6e638c8-05c13a53/relevance/1

Here the plugin don't work: https://www-webofscience.ez45.periodicos.capes.gov.br/wos/woscc/summary/0b749e33-cbc2-4aba-86b8-16e94882a6e1-05c12fcf/relevance/1

**Comment by adam3smith** [comment]
It's very unusual to truncate the URL with the proxy: we're expecting www-webofscience-com.ez45... here and I'm pretty sure that'd be the standard for EZProxy (which I think you're using?)

**Comment by mplentzez** [comment]
Yes, it is an EZProxy. With the classic interface, the proxy worked similarly (the link was constructed as http://apps-webofknowledge.ez45.periodicos.capes.gov.br/Search.do?product=WOS&SID=8C2KJkJyI7XqKk ....) and the translator worked. Should the link for the new interface include the app string to make the translator functional?

As I'm just the librarian, who identified the trouble and generally show to users how to access the databases, I would really appreciate any suggestions as to how this problem should be corrected to give the institutional tech support the most information to make things right. 

What I noticed is that this behavior, mixing the proxy address with the base url is common, Scopus became https://www-scopus.ez45.periodicos.capes.gov.br/search/form.uri?display=basic#basic, but here the plugin work normally. 

I don’t know if it helps, but we are accessing by a brazilian portal of scientific bases and journals called  Portal Capes (https://www-periodicos-capes-gov-br.ezl.periodicos.capes.gov.br/index.php?), where the user identifies his/hers institution and the page redirect to the University proxy, so I’m not sure if the problem is at the Portal as a whole or in our institutional proxy.

**Comment by AbeJellinek** [comment]
Yeah, this is odd. It would work if the proxied URL looked like https://www-webofscience-com.ez45.periodicos.capes.gov.br/, but the missing `-com` causes Zotero to de-proxify the URL without a top-level domain. Is there any way that the institution's EZproxy config could be updated not to perform that transformation? Otherwise it's unlikely that this translator, not to mention most others, can detect pages correctly.

**Comment by AbeJellinek** [comment]
Either way, I'm closing this since it isn't an issue with the translator.
