### ISSUE TITLE
Translator request: chemrxiv

### ISSUE THREAD

**Issue by dcambie** [zotero/translators#2685]
Chemrxiv the primary preprint server in chemsitry, but as of today, existing translators can't seem to deal with it at all. If someone were to find the time to do this, it would go a long, long way towards making Zotero more useful in chemistry.

I'd be more than happy to assist with any questions regarding the functioning of the platform and attributing materials to the relevant Zotero item types.

From the HTML source I can see that the following info can be directly extracted from the corresponding  `<meta>` tags:
- citation_title
- citation_publication_date
- citation_doi
- citation_pdf_url
- citation_keywords
- citation_abstract
- citation_author (multiple, + institution and orcid)

Further info might be accessible via the OpenAPI interface (docs at https://chemrxiv.org/engage/chemrxiv/public-api/documentation) but imho parsing meta would be more than enough.

I would attempt to code it myself, but my latest experiments with JS were in the early 2000s, and the language seems to have evolved a bit since then ;)

**Comment by AbeJellinek** [comment]
We support ChemRxiv via the Embedded Metadata translator! (Those `<meta>` tags you list are part of the Highwire standard, which EM handles.) If you go to [this page](https://chemrxiv.org/engage/chemrxiv/article-details/60c757db337d6cb6fde290d5), does the connector detect it as a journal article and offer to translate with EM? If not, there's something going on on your end, unfortunately.

We could definitely improve support with a dedicated translator - preprints should really be translated as reports with `Type: article` in the `Extra` field - but EM should be working for the time being.

**Comment by dcambie** [comment]
@AbeJellinek you are right, somehow it was not working for me yesterday but it works today. Sorry for the confusion, it can be closed as EM is probably good enough
