### ISSUE TITLE
JSTOR fails to detect DOI

### ISSUE THREAD

**Issue by andrusha** [zotero/translators#2704]
JSTOR translator fails to detect DOI, while it is available in the `data-doi` field, example article https://www.jstor.org/stable/2117352

![image](https://user-images.githubusercontent.com/387791/133607974-14f7f992-53bb-43b3-baa5-a3a96f222e06.png)

Ref https://github.com/ethanwillis/zotero-scihub/issues/55

**Comment by adam3smith** [comment]
That's not actually a DOI. JSTOR just uses internal IDs that look like DOIs. Check doi.org/10.2307/2117352
