### ISSUE TITLE
EBSCO attaches wrong PDF 

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2717]
Reported by @elotroalex [on the forums](https://forums.zotero.org/discussion/92074/different-ebsco-titles-downloading-the-same-pdf-over-and-over) and successfully replicated by me:

> Once a record with a pdf is attached has been downloaded, subsequent downloaded records for items without an attached pdf (almost always) have a copy of that earlier pdf attached, totally inappropriately, to the new record. The problem ends when a new record for an item with an attached pdf is downloaded, but it resumes again as soon as another record without an attached pdf is downloaded.  Users, if and when they realize what is happening, need to go back and delete the incorrectly attached pdfs.  To make matters worse, it appears that every now and then the correct text is actually appended even if the Ebsco record does not itself include one.  I suspect that Ebsco is searching, though not very effectively, to see if there is full text for the item somewhere else in our collections.

**Comment by elotroalex** [comment]
Following

**Comment by adam3smith** [comment]
Steps to reproduce:
1. Select the ERIC database on EBSCO (the issue isn't limited to ERIC, this is just for ease of reproducibility)
2. Search for "testing" -- no field or any other restrictions (I'm seeing 82,215 results)
3. Click on 8. "Factors Affecting Family Compliance with Genetic Testing of Children Diagnosed with Autism Spectrum Disorder"
4. This opens in PDF view --> Click on "Detailed Record"
5. Click the Save to Zotero icon --> item imports with (correct) PDF
6. Click on "Result list" on the left to return to search results
7. Click on "Testing, Teacher Turnover and the Distribution of Teachers across Grades and Schools. Working Paper No. 229-0220"
8. Click Save to Zotero icon --> Item imports with PDF, although PDF isn't in EBSCO
9. Open the PDF: It's the "Factors Affecting...." PDF above. (Note that the filename will, of course, be different and _look_ correct since the PDF is renamed using the -- correct -- metadata)
