### ISSUE TITLE
ChromeDriver needs update for M1

### ISSUE THREAD

**Issue by boan-anbo** [zotero/translators#2744]
https://github.com/zotero/translators/blob/0d435d8a952639d4e7489263b3a40c89377ecd31/package.json#L19

`npm i` return `Only Mac 64 bits supported.` for ChromeDriver on M1 chip.

Pumping it up to `^91.0.1` solves the problem.

**Comment by dstillman** [comment]
Thanks — I updated it to `^95.0.0`. (I didn't actually test that ChromeDriver still works, but we'll find out soon enough.)
