### ISSUE TITLE
ScienceDirect: Open-access PDF fails to save

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2745]
Reported here: https://forums.zotero.org/discussion/92831/zotero-connector-unable-to-download-the-pdf-in-sciencedirect

https://www.sciencedirect.com/science/article/pii/S0968090X21004307

I can open the file via the browser, but its fails via Zotero with "Downloaded PDF was not a PDF".

@AbeJellinek: I can look at this if you don't have time today.

**Comment by AbeJellinek** [comment]
Yeah, that's what I was working on in #2742. (I'm guessing this is the same issue.) It seems like it might be something about `proxy: false`; maybe it isn't resolving relative URLs correctly when that's set? It worked when I manually appended the domain name to the attachment URL before completing the item.

I won't have time to figure this out today, most likely, so go ahead.

**Comment by dstillman** [comment]
`proxy: false` shouldn't be relevant here. Zotero has the correct URL, and if I open it in the browser I get the PDF. So they may have added some sort of additional check beyond the cookies that transfer to the request. I'll investigate.

**Comment by AbeJellinek** [comment]
Any luck with this? You're right that it isn't `proxy`; I was seeing successful PDF grabs when that field was set to false, unsuccessful ones when it was true, but I think that was just a coincidence. Attachments do _sometimes_ work for me - it seems that the new indirect redirect isn't always there, and sometimes the link goes directly to the PDF.

**Comment by dstillman** [comment]
Duplicate of #2739
