### ISSUE TITLE
University of Chicago Press Book translator broken

### ISSUE THREAD

**Issue by boan-anbo** [zotero/translators#2747]
Only title and abstract information is captured now. 

Example: [A book](https://press.uchicago.edu/ucp/books/book/chicago/P/bo5780990.html)

I can work on fixing it later.

**Comment by boan-anbo** [comment]
Sorry just saw the related issues and upcoming PR. If this is redundant feel free to remove this.

#2731 

#2167

**Comment by adam3smith** [comment]
Yes, this will be fixed in PR under review
