### ISSUE TITLE
Amazon Book

### ISSUE THREAD

**Issue by pixiandouban** [zotero/translators#2753]
**Scaffold** test can do translation, but **Zotero** can't save book info.

For example, [Test](https://www.amazon.com/Test-William-Sleator/dp/0810989891)

**Comment by dstillman** [comment]
Works fine for me.

See <a href="https://www.zotero.org/support/troubleshooting_translator_issues">Troubleshooting Problems Saving to Zotero</a>, and post to the forums if you're still having trouble.
