### ISSUE TITLE
Customize translator property format (like date format in imported wikipedia web pages)

### ISSUE THREAD

**Issue by QuantumGrizzly** [zotero/translators#2756]
By default, most translators like the one for Wikipedia import a web page using the following the extended [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations), using a T character to delimitate time, and a Z character to delimitate the timezone. Having items using different date format make it harder to parse the information in collections.

Is it possible to either:

1. Provide an enhancement to let users customize how they would like to format properties like the date for imported items?
2. Provide a workaround to customize the date format in my software installation?

# Current behavior

Format: `YYYY-MM-DDThh:mm:ssZ`
Example: `2021-11-28T22:09:12Z`

![Screenshot - 20211207 174548 - zotero](https://user-images.githubusercontent.com/22773715/145117586-91d27449-1821-4b15-b9ee-2865928013f3.png)

# Desired behavior

Format: `YYYY-MM-DD`
Example: `2021-11-28`

![Screenshot - 20211207 174613 - zotero](https://user-images.githubusercontent.com/22773715/145117598-a2c817b1-784f-4a75-ab30-7d857171df7d.png)

# Relevant links

- Similar request in issue 797
  - https://github.com/zotero/translators/issues/797#issuecomment-162344530
- Code in the Wikipedia translator
  - https://github.com/zotero/translators/blob/ef1c1951ae7ec3eb198f90b28aadf724b062f975/Wikipedia.js#L163

**Comment by dstillman** [comment]
Please post all feature requests and bug reports to the Zotero Forums. See [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.

Translators generally save to ISO 8601, as you say, and that's the appropriate behavior. We're not going to throw away data at save time.

There's an [unfinished pull request](https://github.com/zotero/zotero/pull/1199) to display cleanly parsed dates in a uniform format. If you'd like to work on this, you're welcome to bring that up to date and help finalize it.

**Comment by QuantumGrizzly** [comment]
Thanks for your answer dstillman, and I am sorry for posting here. GitHub is my to-go place to check and report feedback on open source projects, and I did not have an account on the Zotero forum. I will know in the future.

I will try to test the changes of the pull request on my local installation.

**Comment by dstillman** [comment]
Not a problem — we were missing an issue template in this repo with that information. I've added it now.

**Comment by QuantumGrizzly** [comment]
If anybody else finds this thread and wants to also customize the Wikipedia translator, I was able to accomplish mostly what I wanted to do by modifying the Wikipedia.js file in my Zotero data directory.

# Changes

- Add 'Wikipedia' as a creator
- Add 'Wikimedia Foundation' as the publisher
- Add the article title in the short title
- Replace the language (typically en-us for me) with English

# Edits 

You can copy and paste the modified Wikipedia.js file:

https://gist.github.com/QuantumGrizzly/9680b810d25527fffcd5ab5005f806f1
