### ISSUE TITLE
ProQuest breaks on standard pages

### ISSUE THREAD

**Issue by owcz** [zotero/translators#2760]
PQ defaults to Embedded Metadata (not the PQ translator) on basic pages such as the following:

* https://www.proquest.com/docview/557394080/74D8D0EE05304335PQ/8

Tested with proxy redirection off

Been like this for a few months, to my recollection

```
18:16:17 On Abstract page, scraping
18:16:17 WARNING: No item type specified
18:16:17 Translation using ProQuest failed: 
         Error: No title specified for item

**Comment by owcz** [comment]
For posterity, logged out abstract pages are supposed to fail to EM because there is no structured metadata to scrape (just the citation listing at the top)

**Comment by adam3smith** [comment]
@owcz we can close this, right?

**Comment by owcz** [comment]
Yes, assuming that it's not worth the effort writing a potentially brittle translator for logged-out metadata
