### ISSUE TITLE
IETF translator failed due to lack of item title 

### ISSUE THREAD

**Issue by mvolz** [zotero/translators#2770]
The IETF translator seems to use the bibtex translator; however it consistently fails to find the title and the entire translator fails because of that, since title is a required field.

**Comment by AbeJellinek** [comment]
Example page that fails?

**Comment by mvolz** [comment]
All of the ones in the tests! i.e. https://datatracker.ietf.org/doc/html/rfc1737 

I'm using translation-server locally but they failed in scaffold too.

**Comment by AbeJellinek** [comment]
Thanks, should be working now!
