### ISSUE TITLE
nbib -- add article numbers

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2783]
Reported here: https://forums.zotero.org/discussion/94403/nbib-article-number-missing-from-metadata#latest
We are importing article numbers into the page field from Pubmed XML and should just copy the logic

**Comment by georgegebbett** [comment]
The issue would seem to stem from [these lines](https://github.com/zotero/translators/blob/3db541be41714f828830d2f09817ccda822b7158/PubMed%20XML.js#L139-L142), and so fixing it should be straightforward enough (as long as this doesn't have unintended effects where this is the correct behaviour) - it is just a case of selecting the appropriate field for the article number to go into in the resulting item.

**Comment by georgegebbett** [comment]
The [spec](https://en.wikipedia.org/wiki/Publisher_Item_Identifier) suggests that a PII should be 17 characters long, so it would carry that when we find a PII that is not 17 characters, it probably isn't a PII. 

I'm not sure why we have code which takes what we expect to be a PII and puts it in the pages field though? [PubMed are quite clear that that is what should be provided at that point in the XML](https://dtd.nlm.nih.gov/ncbi/pubmed/doc/out/190101/el-ELocationID.html) so quite why they are providing something which simply is not that is very odd.

**Comment by adam3smith** [comment]
I'm guessing because PIIs as defined in the spec never really got adopted (possibly because DOIs took their place - I think some publishers may actually use the PII as the DOI suffix), so they use the field if that name for more generic elocation now.

**Comment by adam3smith** [comment]
But you are misunderstanding the issue: the behavior on import from PubMed XML is correct for Zotero purpose. It should be extended to nbib import
