### ISSUE TITLE
PNAS broken after redesign

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2791]
reported https://forums.zotero.org/discussion/94788/pnas-site-update-seems-to-have-broken-translator#latest

I think it's still Atypon, just not recognized.
https://www.pnas.org/doi/10.1073/pnas.2117831119

**Comment by stanleyrhodes** [comment]
Fellow Zotero user here, looking to see if this issue had been filed. And it had! :) I poked around in the PNAS site and found this (putting it here if it has any useful leads):
"PNAS will be moving to the Atypon Literatum platform on February 28, 2022. To ensure a smooth transition, PNAS has prepared a checklist for libraries to follow."
https://www.pnas.org/librarians/migration-checklist
