### ISSUE TITLE
zotero translator doesn't work in some url of WOS

### ISSUE THREAD

**Issue by tughv** [zotero/translators#2792]
when url is https://www.webofscience.com/wos/alldb/full-record/INSPEC:20213300 ,the translator can't recognize this url.
![image](https://user-images.githubusercontent.com/40344969/156722658-f8ea623f-4b03-4e9e-ad5f-9c2fa421289d.png)

**Comment by AbeJellinek** [comment]
Fixed by #2817 (I think).
