### ISSUE TITLE
Lingbuzz: Map  "Published in" field of Lingbuzz with "Extra" field of Zotero

### ISSUE THREAD

**Issue by Dellu** [zotero/translators#2797]
I have stated the request here: https://github.com/zotero/translators/pull/2257

Currently, the Extra field contains "type:article" for all types of entries. That is inaccurate information because the entries are not actually articles. Some of them are dissertations, drafts to books, articles or any kind of unpublished material. But, Lingbuzz doesn't have the field for the "type". That information is supposed to be noted in the "published in" field. 

For that, I think the right approach is to map "published in" field of Linbuzz with Extra field of Zotero. 

Dear @[AbeJellinek](https://github.com/AbeJellinek), is it difficult to include the "published in" field?

**Comment by AbeJellinek** [comment]
Is this still an issue with the Preprint item type (97f6c5466f210956fec978afe4dd7a84114c11fb)? It doesn't look like "Published in" data is very structured, so I'm not sure how we'd parse it.

**Comment by Dellu** [comment]
Is it difficult to map "published in" to the "extra" field?

It doesn't matter what is written in the field. Often, the content of the "published in" filed is either a journal, a conference, or just a simple comment/note by the author. If it can be mapped to "extra" field, then, we can map it to the "note" field of bibtex.

**Comment by AbeJellinek** [comment]
>Is it difficult to map "published in" to the "extra" field?

Not difficult, but directly mapping it would be wrong. Extra is supposed to be in a key-value format, e.g.

```
Publication Title: Something
Original Date: 1955
Some Custom Data: xyz
```

I'm not totally sure that BBT supports mapping custom Extra fields to BibTeX fields, but if it does then I suppose we could map save it as something like `LingBuzz Published In: to appear in XX journal`.

**Comment by AbeJellinek** [comment]
(But I think I'm less confident than you are that you'll always want whatever the author wrote in "Published In" to appear in your bibliography! As I mentioned above, it doesn't have a defined structure. You'll probably be better off adding it on a citation-by-citation basis.)

**Comment by Dellu** [comment]
>But I think I'm less confident than you are that you'll always want whatever the author wrote in "Published In" to appear in your bibliography!
I totally agree. Most of the stuff the authors write is actually irrelevant; need not go to the bibliography. I am aware of that. But, my idea was to have the data in the library; and then make a decision to include it or not on individual entries. 

BBT supports customization: https://retorque.re/zotero-better-bibtex/exporting/#add-your-own-biblatex-fields
It is possible to add "key-value" custom entries in the Extra field: 

`published in: to appear in XX journal`

**Comment by AbeJellinek** [comment]
OK, I had it save as "LingBuzz Published In:" in Extra. We generally try to use unique keys for things like this.

**Comment by Dellu** [comment]
OK, thank you. I will look for ways to remap the "LingBuzz Published In:" to "note" in BBT.
