### ISSUE TITLE
Lingbuzz: Change the  default "type"  to  "Preprint"

### ISSUE THREAD

**Issue by Dellu** [zotero/translators#2798]
I am suggesting some improvements on the  https://github.com/zotero/translators/pull/2257 translator. 
Thank  you guys (@cadadr  and @AbeJellinek  ) for making this amazing translator. It is one of the best thing that happen to us linguists. 

Here is my suggestion for improvement: 

Currently, the items are imported as Reports. When we export them to bibtex format, they come out as "techreport" which is not the right kind. 

Lingbuzz contains materials mostly unpublished; or drafts to be published, and some published items. The right type for this from the Zetoro ones is the Manuscript. 
But, the problem with the Manuscript type is it assumes/suggests unpublished material. 

Out of all the "types", I think Preprint seems to best describe the items in Lingbuzz. It also nicely maps to the Misc type of bibtex. 

For that, I suggest you guys make the preprint to be the default field for Linbuzz items.

**Comment by adam3smith** [comment]
Currently, report with type: article is how Zotero saves preprints. We're still fine-tuning  how to save into the new preprint item types. The old items will eventually be auto-converted

**Comment by Dellu** [comment]
That will be great. I will be looking forward to it.

**Comment by Dellu** [comment]
I reset and update both within Zotero and the Firefox connector(addon). I am still getting "report".

**Comment by adam3smith** [comment]
@AbeJellinek have you tested this in Zotero proper? I'm getting the right import in Scaffold, but it's not working in any of the preprint translators (Lingbuzz, Highwire on MedrXiv or BiorXiv)

**Comment by AbeJellinek** [comment]
Yeah, sorry, I've been meaning to update this thread. I think we need to update the connectors so `fieldIsValidForItemType` supports `preprint` before the check will work in a browser environment.

**Comment by AbeJellinek** [comment]
This should now be working in the [Connector Beta](https://www.zotero.org/support/dev_builds#zotero_connector_beta).

**Comment by Dellu** [comment]
Yes, I just confirmed that it is working in the Beta. 
Thank you!
