### ISSUE TITLE
doesn't work for NeurIPS 2020 and 2021

### ISSUE THREAD

**Issue by wenyan4work** [zotero/translators#2803]
maybe related to #2590 . For the proceedings 2020 and 2021 the zotero-connector doesn't detect any articles in the webpage when clicking 'save to zotero'. For example, this paper: https://proceedings.neurips.cc/paper/2020/hash/0060ef47b12160b9198302ebdb144dcf-Abstract.html

Is this caused by the change of webpage structure? The webpage for 2018 and 2019 has a 'metadata' link, but this is removed in the webpage for year 2020.

**Comment by adam3smith** [comment]
(I have a (partial) fix for this)
