### ISSUE TITLE
projecteuclid can't get the right DOI

### ISSUE THREAD

**Issue by pixiandouban** [zotero/translators#2806]
[Eculid.js](https://github.com/zotero/translators/blob/master/Euclid.js) translator can't get the right DOI, For example, [Growth of quantum 6j-symbols and applications to the volume conjecture](https://projecteuclid.org/journals/journal-of-differential-geometry/volume-120/issue-2/Growth-of-quantum-6j-symbols-and-applications-to-the-volume/10.4310/jdg/1645207506.short).

I'm using Firefox.

**Comment by adam3smith** [comment]
Please report import/translator issues on forums.zotero.org -- this doesn't look like a general issue, so we'd want you to run through https://www.zotero.org/support/troubleshooting_translator_issues  and then troubleshoot on the forums if that doesn't fix your issues.
