### ISSUE TITLE
wos can not be recongnized

### ISSUE THREAD

**Issue by tughv** [zotero/translators#2815]
URL: https://www.webofscience.com/wos/alldb/full-record/DIIDW:202205717D
![image](https://user-images.githubusercontent.com/40344969/163313922-908f9305-b5a1-4135-87d1-8a0e8031c29f.png)

**Comment by AbeJellinek** [comment]
@adam3smith, any chance you could take a look at this? I don't have WoS access anymore and they don't even let you see abstracts without logging in.
