### ISSUE TITLE
Semantic Scholar.js  error in conferencePaper Type

### ISSUE THREAD

**Issue by hbzhou530** [zotero/translators#2825]
Conference paper was incorrectly identified as a journal article

two links for test：
1、CVPR Paper
https://www.semanticscholar.org/paper/Graph-Attention-Convolution-for-Point-Cloud-Wang-Huang/292f120b2664a37335e557bcb2a860a7a8b507a6
2、ICCV Paper
https://www.semanticscholar.org/paper/Hierarchical-Point-Edge-Interaction-Network-for-Jiang-Zhao/a1c5919bd310112202e2041ecf0db09353c32ffe

**BTW, Could** you please add the ‘folder’ function to grab Multiple Captures for search results pages in Semantic Scholar？

THX!

@GuyAglionby @aschokking 
Please excuse the interruption!

**Comment by hbzhou530** [comment]
@GuyAglionby @aschokking 
Please excuse the interruption

**Comment by GuyAglionby** [comment]
I'm not sure how much can be done about the two examples you've given. The translator uses the BibTex on the site to set the item type, and Semantic Scholar lists them as journal articles.

The search functionality is probably doable, though note that the results are loaded asynchronously so might be a little more difficult.

**Comment by hbzhou530** [comment]
Thank you for your reply. It has been reported to Semantic Scholar.

**Comment by AbeJellinek** [comment]
Multiples added in 3ecd7b22e0e5b162641b02b08460c545ef3f134a; other changes are out of the scope of this repo.
