### ISSUE TITLE
Bug report for doi website

### ISSUE THREAD

**Issue by fredericky123** [zotero/translators#2831]
The translator cannot import items from doi website, for example:
https://doi.apa.org/doiLanding?doi=10.1037%2F0882-7974.21.2.253
However, for the same paper, when using the link below, the translator can import correctly.
https://psycnet.apa.org/doiLanding?doi=10.1037%2F0882-7974.21.2.253

The similar issue were solved for reference:https://github.com/zotero/translators/issues/2814

**Comment by adam3smith** [comment]
That's the same link twice. Could you clarify?

**Comment by fredericky123** [comment]
> That's the same link twice. Could you clarify?

That's the same paper but two different links. One begins with "doi.apa", and the other begins with "psycnet.apa"

**Comment by AbeJellinek** [comment]
Thanks, should be fixed.
