### ISSUE TITLE
ESLint: Translator [name] should not be executable always fails on Windows

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2850]
The files definitely aren't executable and pass linting in the CI. This is only a small inconvenience when using `npm run lint` (you just know you'll get 1 error) but it does make the live validation in VS Studio -- very excited to have that otherwise -- almost useless because the entire code is highlighted, so I'd appreciate a fix or any pointers of what I could do locally.

**Comment by AbeJellinek** [comment]
Alright, should be good now.
