### ISSUE TITLE
New Open Worldcat format

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2868]
Reported here: https://forums.zotero.org/discussion/99243/new-worldcat-interface-and-zotero-connector-translator#latest
New interface example e.g. https://worldcat.org/title/1267333854

It doesn't look like they're still offering any RIS or other bib data, but there is quite decent-looking JSON-LD/schema.org in the header, I'd use that? We still don't have an import translator for that, right? So would have to code that into the style?

@AbeJellinek @dstillman any thoughts on the approach here? (would generally be nice to finally support JSON-LD...)

**Comment by AbeJellinek** [comment]
On it. JSON-LD doesn't have everything we need (publisher...) but the internal metadata in `__NEXT_DATA__` is fine.
