### ISSUE TITLE
Add Standard E-books translator

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2875]
Requested: https://forums.zotero.org/discussion/99371/standard-ebooks-metadata-errors-juris-m-connector#latest

Example: https://standardebooks.org/ebooks/william-shakespeare/titus-andronicus
Lots of semantic schema.org tags on the site, shouldn't be hard.

**Comment by brendan-oconnell** [comment]
Pull request here: https://github.com/zotero/translators/pull/2981

**Comment by brendan-oconnell** [comment]
Merged to translators
