### ISSUE TITLE
Bug report: doesn't work on infomm website

### ISSUE THREAD

**Issue by fredericky123** [zotero/translators#2955]
For example,
https://pubsonline.informs.org/doi/epdf/10.1287/orsc.2020.1408
For scholars who have an access to the journal, the add-on doesn't work for informs website with "epdf"

**Comment by adam3smith** [comment]
Zotero import only rarely works on PDF and epdf pages, so I'm afraid that's just to be expected. Importing [from the landing page](https://pubsonline.informs.org/doi/10.1287/orsc.2020.1408) works fine & attaches the PDF.
