### ISSUE TITLE
(IMDB) Apostrophes and other special characters are not being encoded correctly in Title and Abstract fields

### ISSUE THREAD

**Issue by stees** [zotero/translators#2988]
From this:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/57099996/223310585-dafead00-15a6-4c47-ba51-c971968e4015.png">

I'm getting this:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/57099996/223310656-1bb0cd56-1faf-48a3-b5df-a78d168be85e.png">

Also applies to the abstract.

**Comment by brendan-oconnell** [comment]
@stees this has been fixed and merged to the translators repo, thanks for reporting the issue!
