### ISSUE TITLE
BibTeX Import removes special characters when combined with sub/superscript

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#3013]
Example:

```
 @article{Borissov:2855446,
               author        = "Borissov, Alexander and Solokhin, Sergei",
               collaboration = "ALICE",
               title         = "{Production of $\Sigma^{0}$ Hyperon and Search of
                                $\Sigma$$^{0}$ Hypernuclei at LHC with ALICE}",
               journal       = "Phys. At. Nucl.",
               volume        = "85",
               number        = "6",
               pages         = "970-975",
               year          = "2023",
               url           = "https://cds.cern.ch/record/2855446",
               doi           = "10.1134/S1063778823010131",
         }
 ```

(from the included URL)
title imports as 
> Production of <sup>0$</sup> Hyperon and Search of <sup>0$</sup> Hypernuclei at LHC with ALICE

i.e. makes a complete mess of things. The problem is the `mapTeXmarkup` function.

@retorquere -- you're probably (and understandably) not super interested in messing with the generic BibTeX import, but since you've thought about this about 100x as much as I have... if you would take a look that'd be wonderful.

**Comment by retorquere** [comment]
The problem sits deeper -- `getFieldValue` mangles the input before it gets to `mapTeXmarkup`. I'll see what I can do.

**Comment by retorquere** [comment]
There was an error in the regex for postscript, see #3014.

**Comment by retorquere** [comment]
The github action keeps getting canceled. I don't know why that is.
