### ISSUE TITLE
New translator for GeneCards

### ISSUE THREAD

**Issue by brendan-oconnell** [zotero/translators#3031]
Pages on the site GeneCards are triggering the DOI Search Translator because the regex in the DOI Search Translator is matching non-DOIs, causing the DOI translator to fail on this site.

Issue reported here: [https://forums.zotero.org/discussion/103753/genecards-page-cannot-be-saved-to-zotero#latest](https://forums.zotero.org/discussion/103753/genecards-page-cannot-be-saved-to-zotero#latest)

Examples: https://www.genecards.org/cgi-bin/carddisp.pl?gene=CRTAC1

On this page, there's a link to https://academic.oup.com/database/article/doi/10.1093/database/bax028/3737828, so `getDOIFromURL` in `DOI.js` returns a match on `10.1093/database/bax028/3737828`, which is not a DOI - 10.1093/database/bax028 is. 

This seems to be an issue with all links out to GeneHancer from GeneCards, here's another example:
https://www.genecards.org/cgi-bin/carddisp.pl?gene=DDC&keywords=acidic

We could tweak the DOI regex in `DOI.js`, but this would result in Zotero saving metadata from the GeneHancer items with DOIs, which isn't what the user wants - I assume they want to save the GeneCards page and associated metadata. So it seems to make the most sense to build a new translator for GeneCards.

**Comment by adam3smith** [comment]
This can't be fixed via regex: 10.1093/database/bax028/3737828 is, in theory, [a perfectly valid DOI](https://www.doi.org/the-identifier/resources/handbook/2_numbering#2.5.1): " Neither the Handle System nor DOI system policies, nor any web use currently imaginable, impose any constraints on the suffix, outside of encoding (see below)."

**Comment by brendan-oconnell** [comment]
@adam3smith OK, thanks - so we'll need to build a translator for GeneCards

**Comment by dstillman** [comment]
What kind of data would a translator save?

**Comment by brendan-oconnell** [comment]
Good question. I could ask the user on the Forums what exactly they want to save... I don't know enough about the discipline to say how people typically cite genes. A quick search on Google Scholar turned up a couple examples of articles that cite specific genes from GeneCards. In both cases, the GeneCards page isn't part of the References list, just a parenthetical citation with a link to the relevant gene from GeneCards.
https://ojrd.biomedcentral.com/articles/10.1186/s13023-021-01775-8#Bib1
https://assets.researchsquare.com/files/rs-1977193/v1/a6a8a00a-e42c-4a1d-a8db-003311ced59f.pdf?c=1661277392

This would seem to indicate that saving a GeneCards page with the Webpage item type would be sufficient (and is the only item type that would really fit). In this case, I'd just save Title, URL, perhaps the GeneCards Summary as Abstract.

To return to the original issue reported on the Forums, though, the user wants to save pages from GeneCards with a Zotero Connector. Maybe right-clicking on the Connector every time to override the DOI detection and save as Webpage  is a good enough workaround, though? What do you think?

**Comment by dstillman** [comment]
Yeah, no need to create a translator just to avoid faulty DOI detection. The proper fix here is just to [always show the webpage itself](https://github.com/zotero/zotero-connectors/issues/392) as an option at the top of the select-items dialog for the DOI translator.
