### ISSUE TITLE
clinicaltrials.gov website changes

### ISSUE THREAD

**Issue by agitter** [zotero/translators#3069]
ClinicalTrials.gov updated their website ([announcement](https://nexus.od.nih.gov/all/2023/06/27/the-modernized-clinicaltrials-gov-website-is-here/)). This will likely affect `clinicaltrials.gov.js`. For instance, the classic version of the site now has URL patterns like `https://classic.clinicaltrials.gov/ct2/show/NCT04292899`, and the translator target is `"target": "^https://(www\\.)?clinicaltrials\\.gov/ct2/(show|results\\?)"`. The new version of the site may store metadata differently or different metadata altogether.

Here's an example of the new and classic sites:
- https://classic.clinicaltrials.gov/ct2/show/NCT04292899
- https://www.clinicaltrials.gov/study/NCT04292899

**Comment by dstillman** [comment]
Is there any reason to support the `classic` domain?
