### ISSUE TITLE
the SSRN translator.

### ISSUE THREAD

**Issue by momomyj** [zotero/translators#3185]
I wanted to bring to your attention an issue I encountered while using the SSRN translator. When attempting to save an item, I received an error message stating, "An error occurred while saving this item. Please refer to Translator Troubleshooting for more information." Could you please assist me in resolving this problem?

[JavaScript Error: "Error: HTTP request to https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3506084 rejected with status 429
    at chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/messaging_inject.js:79:17
    at async Zotero.HTTP.processDocuments (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/inject/http.js:107:17)
    at async Zotero.Utilities.Translate.processDocuments (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/translate/utilities_translate.js:261:5)" {file: "[object Object]"}]

Thank you for your attention and assistance.

**Comment by LaurenceOfAustralia** [comment]
From the error message it looks like Zotero was unable to connect to SSRN, receiving http error 429 which indicates the site is rate limiting your connection. If you try again now it is likely the site is no longer doing that, and you should be able to get the citation without any further difficulties.
