### ISSUE TITLE
Translator can't work on CNKI page currently.

### ISSUE THREAD

**Issue by LaoshuBaby** [zotero/translators#3189]
Site: CNKI
Test webpage: ```https://kns.cnki.net/kcms2/article/abstract?v=jDUTNXVfqCo6eFMtwDv47p2Lo-TIPgJZqjSKeAFswkQJY6jhSySKFemacgFMs6327E5z6iZg0upsclk3rc3n-47k8-iI0nUpEnJ74X-RL4sbAC7ZhhZk1vGVulA8JKh6d1dtaR1Bg0mowLH57niC_A==&uniplatform=NZKPT&language=CHS``` (Yes, surely long as that)
Report date: 2023-11-18
Screenshot:
![图片](https://github.com/zotero/translators/assets/42690037/a44253fa-d90f-4fb3-98d0-6823b4945fe3)
![图片](https://github.com/zotero/translators/assets/42690037/96d66dbe-1823-43dd-a286-116e7cd70ccc)

"Failed to save while using **CNKI**, try to **Save as Webpage**"

---
Note: similar bug was also reported to "translators_CN" project in https://github.com/l0o0/translators_CN/issues/231

**Comment by wudizgx** [comment]
有处理方法吗

**Comment by LaoshuBaby** [comment]
> 有处理方法吗

不知道啊，您也是？

**Comment by wudizgx** [comment]
是的，正要写论文就用不了了

**Comment by BlueBubble23** [comment]
有解决方法吗

**Comment by QJerryxjh** [comment]
1

**Comment by linzang3119** [comment]
When will this be resolved?

**Comment by linzang3119** [comment]
这个啥时候能解决呢？

**Comment by hahaha9968** [comment]
就有点突然，昨天还能用

**Comment by Jacky1226Fu** [comment]
1，同样的状况，mac

**Comment by appreciatesharer** [comment]
yes，I have the same question

**Comment by appreciatesharer** [comment]
今天，我在更新过茉莉花插件的知网翻译器后，又可以正常使用了，不知大家情况是否都已好转

**Comment by ashtray703** [comment]
还是不行

**Comment by hswyy** [comment]
> 今天，我在更新过茉莉花插件的知网翻译器后，又可以正常使用了，不知大家情况是否都已好转

怎样更新啊

**Comment by appreciatesharer** [comment]
> > 今天，我在更新过茉莉花插件的知网翻译器后，又可以正常使用了，不知大家情况是否都已好转
> 
> https://blog.csdn.net/weixin_49818157/article/details/125261306#:~:text=%EF%BC%881%EF%BC%89%E8%BF%9B%E5%85%A5%E8%8C%89%E8%8E%89%E8%8A%B1%E6%8F%92%E4%BB%B6%20%EF%BC%882%EF%BC%89%E7%82%B9%E5%87%BB%E5%B7%A6%E4%B8%8B%E8%A7%92%E2%80%9C%E5%88%B7%E6%96%B0%E2%80%9D%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%88%B0%E5%B7%B2%E7%BB%8F%E5%AE%89%E8%A3%85%E7%9A%84%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AF%91%E5%99%A8%EF%BC%8C%E5%9C%A8%E8%BF%99%E9%87%8C%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%88%B0%E6%94%AF%E6%8C%81%E6%88%91%E4%BB%AC%E6%8A%93%E5%8F%96%E7%9A%84%E5%90%84%E7%B1%BB%E4%B8%AD%E6%96%87%E7%BD%91%E9%A1%B5%EF%BC%8C%E5%8C%85%E6%8B%AC%E7%99%BE%E5%BA%A6%E5%AD%A6%E6%9C%AF%E3%80%81%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E3%80%81%E4%B8%AD%E5%9B%BD%E7%9F%A5%E7%BD%91%E3%80%81%E5%BD%93%E5%BD%93%E3%80%81%E8%B1%86%E7%93%A3%E3%80%81%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7%E7%AD%89%E3%80%82,%E6%B3%A8%E6%84%8F%EF%BC%9A%E5%A6%82%E6%9E%9CUpdate%E4%B8%80%E5%88%97%E7%9A%84%E5%9B%BE%E6%A0%87%E4%B8%BA%E8%93%9D%E8%89%B2%EF%BC%8C%E5%88%99%E8%A1%A8%E7%A4%BA%E7%BF%BB%E8%AF%91%E5%99%A8%E9%9C%80%E8%A6%81%E6%9B%B4%E6%96%B0%EF%BC%8C%E7%82%B9%E5%87%BB%E4%B8%8B%E6%96%B9%E7%9A%84%E2%80%9C%E6%9B%B4%E6%96%B0%E5%85%A8%E9%83%A8%E2%80%9D%E5%8D%B3%E5%8F%AF%E5%AE%8C%E6%88%90%E6%9B%B4%E6%96%B0%E3%80%82%20%EF%BC%883%EF%BC%89%E6%9B%B4%E6%96%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E7%BF%BB%E8%AF%91%E5%99%A8%E4%BF%A1%E6%81%AF

对的，就是通过更新茉莉花内部的知网翻译器，尔后更新浏览器的翻译器后，就可以正常使用的。茉莉花内部的知网翻译器应当是20号左右更新过了

**Comment by tt-mbw** [comment]
成功了

**Comment by dstillman** [comment]
Fixed by https://github.com/zotero/translators/pull/3191
