### ISSUE TITLE
Belgian newspapers broken

### ISSUE THREAD

**Issue by Themanwithnowifi** [zotero/translators#3314]
It seems that a couple of Belgian newspapers are broken like Het Nieuwsblad, Gazet van Antwerpen, Belang van Limburg and a couple of  other as well.

**Comment by Themanwithnowifi** [comment]
Its about the visual editor in wikipedia, i did think it uses zotero as a basis. But i dont know I am on the right place to ask. Its my first time.

**Comment by adam3smith** [comment]
Just to clarify -- there isn't I believe, dedicated support for any Belgian newspaper in Zotero, so Zotero (and thus WP's visual editor's cite function) relies on the basic metadata they provide on their article pages, which likely isn't very good. Specific code contributions (i..e. translators) would be welcome

**Comment by adam3smith** [comment]
Just to clarify -- there isn't I believe, dedicated support for any Belgian newspaper in Zotero, so Zotero (and thus WP's visual editor's cite function) relies on the basic metadata they provide on their article pages, which likely isn't very good. Specific code contributions (i..e. translators) would be welcome, but I'd guess it's unlikely this would come from Zotero's core team.
