### ISSUE TITLE
IEEE Xplore Fails

### ISSUE THREAD

**Issue by gcoremans** [zotero/translators#3340]
Concretely on this page: https://ieeexplore.ieee.org/document/8719492

Pressing the translator button stalls for about ~10 seconds with the title appearing greyed-out after which it seems to time out and fail. I have pressed 'reset translators' and the issue persists (after hard-reloading the page)

**Comment by adam3smith** [comment]
not a general issue -- please run through https://www.zotero.org/support/troubleshooting_translator_issues and if not fixed report with all requested information on the Zotero forums.
