### ISSUE TITLE
Non-ascii translator names

### ISSUE THREAD

**Issue by avram** [zotero/translators#459]
Another complaint about translator names causing issues:  http://forums.zotero.org/discussion/25390

I'm at fault for most of these, since I've opted to use native-language titles for translators, and Zotero unpacks the translators into files that match the name specified in the JSON header. I generally think that modern computers should be expected to handle them fine and we are under no obligation to rename, but perhaps we can come agreement?

Two options, as I see it:
1. Keep names as-is, with occasional issues around backup software
2. Rename translators, so tooltips in address bar show up in Latin transliteration / English translation

Either works, but we should probably come to an explicit decision.

**Comment by lborgman** [comment]
As long as you work only inside Zotero it is fine with non-ascii file names. However as soon as you start to do something else with the translators it is a pain. Trying to make git, grep, php, windows etc cooperate on non-ascii file names is quite a bit time consuming.

Please rename the files to ascii names. (The content within the files does not usually matter. Preferably UTF8, of course.)

Some files i have seen now that causes me problems:

 Bibliothèque et Archives nationales du Québec.js
 Tatar zamanı.js

**Comment by aurimasv** [comment]
Do these issues extend beyond just typing at the prompt? Personally, I haven't experienced any issues working on Windows, but I don't generally have to type out translator names without auto-complete being available.

**Comment by adam3smith** [comment]
but I mean -- we decided to use ascii for filenames, so these two just seem like an oversight, no?

**Comment by lborgman** [comment]
It is the tool-chain that can't handle non-ascii file names. There are several issues. (I use mostly unix-style tools on Windows.)

**Comment by aurimasv** [comment]
>but I mean -- we decided to use ascii for filenames, so these two just seem like an oversight, no?

Well, sort of. I guess this issue was more about translator labels. The annoying part (mostly for cyrillic) is finding translator files from labels, but given the small amount of such translators and since we already romanized the file names anyway, oh well.

That does remind me that Scaffold needs to be fixed to not rename these files.

**Comment by avram** [comment]
I think just fixing these filenames makes sense-- I mainly wouldn't want to back off from native-language / native-script names in the label, since that's what shows to the user.

**Comment by adam3smith** [comment]
no, the issue here was specifically about filenames which also confused backup tools. Like Avram, Dan above says to keep the labels, which and @lborgman doesn't object to utf-8 within the files, either.

**Comment by adam3smith** [comment]
I'll do it tonight or we'd accept patches.

**Comment by lborgman** [comment]
thanks adam3smith.

**Comment by aurimasv** [comment]
Done

**Comment by gracile-fr** [comment]
Was it voluntary to replace `è` by `ee` in `Bibliothèque et Archives nationales du Québec.js`?
