### ISSUE TITLE
SSRN translator does not download PDFs

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#523]
SSRN translator will not download PDFs (even thought the URL for the PDF is correct), because Zotero does not pass `Referer` header in the request.

@simonster Could we maybe make Zotero add `Referer` header based on item.URL (which I realize does not have to match the page where the PDF link is) or maybe from an additional field in the attachment item (e.g. `item.attachments[0].referer`)?

Edit: or first the latter and fall back on the former

Edit2: The url should also be proxified if needed

**Comment by dstillman** [comment]
Another report of this: https://forums.zotero.org/discussion/70404/zotero-connecter-bug-with-ssrn-file

**Comment by dstillman** [comment]
Closed this accidentally. So as noted in the commit, this might work now.
