### ISSUE TITLE
Add support for Europe PubMed Central

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#544]
We should add support for http://europepmc.org/ as well as other international PubMed Central websites http://www.ncbi.nlm.nih.gov/pmc/about/pmci/

**Comment by hubgit** [comment]
As there's no metadata in the HTML, maybe it would be possible to translate from a URL like https://europepmc.org/article/MED/32923700 to a web service request like https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=src%3Amed%20ext_id%3A32923700&resultType=core&pageSize=1&format=json that returns the metadata.
