### ISSUE TITLE
No longer able to preserve capitalization in BibTeX export.

### ISSUE THREAD

**Issue by QuLogic** [zotero/translators#550]
Previously, one could use braces to force BibTeX to preserve case and Zotero would output them just fine. Now this is no longer possible.

If you put something in braces, Zotero will escape the braces:

```
Zotero: "{S}trange{W}ord" -> .bib file: "{\{S\}trange\{W\}ord}" -> final result: "{s}trange{w}ord"
```

If you don't put anything in braces, the capital letters remain as usual and BibTeX makes them lowercase:

```
Zotero: "StrangeWord" -> .bib file: "StrangeWord" -> final result: "strangeword"
```

**Comment by jooolia** [comment]
I am curious too. Is there a recommended workaround?

**Comment by aurimasv** [comment]
#813 should have made it so Zotero does "the right thing" without any need to escape. Please post the issue on the forums if you find a case with unexpected behavior/

**Comment by jooolia** [comment]
Thanks. So is there a way to protect capitals then?

**Comment by aurimasv** [comment]
Not explicitly, but they should be protected by default.

**Comment by adam3smith** [comment]
@aurimasv -- did we forget to actually declare the preference?

**Comment by jooolia** [comment]
No it is perfect! Was using an old exporter! Thanks for the help!
