### ISSUE TITLE
add support for Polaris library catalog

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#657]
http://pac.kings.edu/polaris/
http://librarycatalog.eugene-or.gov/Polaris/Search/default.aspx?ctx=3.1033.0.0.1&type=Default

**Comment by aurimasv** [comment]
Another request https://forums.zotero.org/discussion/46822/innovative-interfaces-polaris-opac/
Catalog at http://www.clan.lib.nv.us/polaris/

I'll give this a shot, since I had it marked as easy....
