### ISSUE TITLE
Create a single Embedded Metadata translator

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#686]
We have discussed this already to some extent, but because this is a somewhat difficult undertaking, this has not really been done yet.

The general idea is to have a single Embedded Metadata translator that would cover metadata in META tags (as it does now), DOIs on the page (taking over for DOI), and I would argue COinS and probably unAPI.

This would have a couple of advantages:
* We could gracefully fall back to a lower priority translator if a higher priority translator ends up failing (as reported in #685)
* We could combine metadata from multiple sources (e.g. retrieve high quality metadata via DOI and supplement it with abstract, keywords, and attachments from META tags)
* More convenient to the users, since they wouldn't have to worry about switching translators (if at all possible) to import what they want.

One difficulty about this approach is figuring out when different "embedded metadata" (DOI, COinS, etc.) describes the same resource so that data could be combined and not displayed as multiple choices to the user. We'll probably end up deciding this based on unique identifiers, like DOI, ISBN, etc. and/or similarity between titles (maybe ignoring case and punctuation). Any ideas on this would be helpful.

**Comment by dstillman** [comment]
Superseded by https://github.com/zotero/translators/issues/1092, but all of this applies to that.
