### ISSUE TITLE
U of Vienna Library Catalog (Aleph) doesn't work

### ISSUE THREAD

**Issue by ockham** [zotero/translators#747]
Clicking on the Zotero icon in Firefox's URL bar on a result from https://aleph.univie.ac.at/ fails, though it's apparently recognized as "Library Catalog (Aleph)" based.

Zotero's debug window gives "TypeError: newItem.title is undefined [...] Library Catalog (Aleph).js:257".

The error occurs under Firefox 29 both with current Zotero 4.0.20 and a fresh git checkout under Ubuntu 12.04 and 14.04, respectively.

**Comment by AbeJellinek** [comment]
U of Vienna's library now uses Primo, not Aleph, and catalog entries seem to translate correctly.
