### ISSUE TITLE
Add OPOCE DOI translator

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#767]
Sample DOI: 10.2788/86941

RA resolves to "OPOCE" http://doi.crossref.org/doiRA/10.2788/86941

DOI leads to http://bookshop.europa.eu/en/marine-strategy-framework-directive-pbLBNA24340/ which would require a bookshop.europa.eu scraper.

**Comment by adam3smith** [comment]
OPOCE exports nice CSL JSON now and this works via content negotiation
