### ISSUE TITLE
Clean up import translator list

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#774]
Under Gear Menu -> Import..., the file type filter lists all the import translators. The list is quite messy, since we use `target` to determine file extensions and some import translators are coupled with web translators. This results in things like `NCBI PubMed (https?://[^/]*(www|preview)[\\.\\-]ncbi[\\.\\-]nlm[\\.\\-]nih[\\.\\-]gov[^/]*/(?:m/)?(books|pubmed|sites/pubmed|sites/entrez|entrez/query\\.fcgi\\?.*db=PubMed|myncbi/browse/collection/|myncbi/collections/))`

The best approach is probably to separate import/export and web translators (calling import translator from the web translator via `Zotero.loadTranslator`). This way we could continue to reuse `target` field and, as a bonus, we could name the import/export translator differently from the web translator. This would make sense for something like PubMed, where the web translator should be named "NCBI PubMed", but the import translator should probably read "PubMed XML"

**Comment by zuphilip** [comment]
PubMed is an import + web + search translator. How would you suggest to split these three translators up? I guess that the search translator can go either way without interfering anhow the labeling, right? I have a slight preference for a sole import translator and an web/search translator, but I am really not sure here...

**Comment by aurimasv** [comment]
Separate import and search/web translators sounds right to me

**Comment by aurimasv** [comment]
Thanks @zuphilip for all the work!
