### ISSUE TITLE
Add translator for WHO

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#791]
See https://forums.zotero.org/discussion/39254/zotero-importing-book-as-article-from-world-health-organizations-website/ for samples

Overall poor metadata presented on the page, but I'd imagine it's a useful resource for many academics.

**Comment by mvolz** [comment]
The other thing worth mentioning is that embedded metadata translator doesn't seem to run on this, at least not sure from translation-server-v2 for instance this one gets no data, http://apps.who.int/iris/handle/10665/70863 but there actually is embedded metadata in the page.

**Comment by zuphilip** [comment]
This is now implemented as a separate translator.

@mvolz Your example works for me now in the browser. If you encountered any particular problems with the new translation server, then please feel free to open a ticket there.
