### ISSUE TITLE
Add Oxford Reference translator

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#796]
http://www.oxfordreference.com/

Unfortunately no good metadata format available, but the metadata seems to be structured ok on the page and designated by unique classes.

E.g. http://www.oxfordreference.com/view/10.1093/acref/9780199546572.001.0001/acref-9780199546572-e-0009

Re https://forums.zotero.org/discussion/41765/oxford-reference/

**Comment by sonali0901** [comment]
I'll take this up.
