### ISSUE TITLE
Add support for European Commission's Joint Research Centre (JRC)

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#819]
Re https://forums.zotero.org/discussion/42690/translator-problems-at-ec-joint-research-center-jrc/

E.g. http://publications.jrc.ec.europa.eu/repository/handle/JRC87799

Should be quite easy. I think Embedded Metadata should cover everything, except for PDF, which seems easy to attach.

**Comment by zuphilip** [comment]
Close?
