### ISSUE TITLE
Use CrossRef's text mining API to retrieve PDFs by DOI

### ISSUE THREAD

**Issue by aurimasv** [zotero/translators#829]
http://tdmsupport.crossref.org/researchers/

E.g. http://api.crossref.org/works/10.1155/2014/413629 returns a link to the PDF (application/pdf) http://downloads.hindawi.com/journals/bmri/2014/413629.pdf

Not everything works 100% though. E.g. http://api.crossref.org/works/10.5555/515151 could lead you to 404s or http://api.crossref.org/works/10.7554/eLife.05244 might not even lead you to the PDF

The instructions for researchers (link at the top) talks about click-through service, so there's plenty to consider, but overall this is excellent news.

edit: also have to think about licensing

**Comment by adam3smith** [comment]
Zotero PDF retrieval does some version of this now
