### ISSUE TITLE
Search translator (GBV) for ISBN

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#846]
I would like to add an ISBN search translator for the German library network <a href="https://www.gbv.de/">GBV</a>. They have a nice interfaces for this porpuses for example SRU (<a href="https://www.gbv.de/benutzer/z39.50-zugang">Details</a>). Technically a translator can go the exact lines as <a href="https://github.com/zotero/translators/blob/master/Library%20of%20Congress%20ISBN.js">the one for the Library of Congress</a>. But I guess we have several options here and there might be other countries to consider at some time:
 1. Make two seperate translator (LoC, GBV) maybe with different priorities
 2. a) Make one translator which goes over both urls in some order
 2. b) Make one translator with some more logic how to decide which library catalogue to ask in what order. For example in the ISBN number the country/region where the book is published is encoded.

@aurimasv , @adam3smith : What do you think?

**Comment by adam3smith** [comment]
Cool, that's been on my list, too. Obviously we can't add ISBN searches ad infinitum, but my guess would be that GBV is among the larger catalogs out there and will probably perform a lot better than LoC for much European literature (with better data than Worldcat).
I don't have a strong opinion between 1, 2, and 3--I think 2 is probably my least favorite simply because I don't see much of an advantage of backing this into a single translator if we're not going to do 3 (the bulk of the translation is presumably done in MARC or MARCXML anyway). 
If 3 works decently well, that'd be ideal--the country origins of ISBNs don't have convenient ranges, right? We'd just have to match that against a [list](https://www.isbn-international.org/range_file_generation)?

**Comment by aurimasv** [comment]
I'd say ignore 3 for now and place it after WorldCat. If data from worldcat or LoC turns out to be an issue, we can work on optimizing this

**Comment by adam3smith** [comment]
why after worldcat? Isn't WorldCat pretty poor in terms of data quality (by which I mean completeness)?

**Comment by aurimasv** [comment]
Is GBV more likely to contain an ISBN than WorldCat? Is there a lot of overlap between the two catalogs? There's no point in querying GBV all the time if we're just going to fall back to WorldCat most of the time anyway.

**Comment by adam3smith** [comment]
I think you'll find very few (if any) ISBNs in either LoC or GBV that are not in WorldCat. The goal is to get better data for a broader set of ISBNSs.

**Comment by zuphilip** [comment]
What about our discussion here: https://forums.zotero.org/discussion/42350/german-umlauts-aeoeue-problem-with-isbn-identifier/ ?

**Comment by adam3smith** [comment]
Aurimas fixed the character normalization in https://github.com/zotero/zotero/commit/bd87bd3f56e943675cb5fa76812e097c5d672060

**Comment by avram** [comment]
I don't suppose it's possible or feasible to request from these sources in
parallel rather than in sequence?

>

**Comment by adam3smith** [comment]
We probably could. One of the nice things about the LoCs SRU is that it's insanely fast--there's pretty much no noticeable delay between hitting return and import, whereas WordCat easily takes a couple of seconds. If GBV is as fast, running them in sequence would have little downsides.

**Comment by zuphilip** [comment]
It is about data quality and not further ISBN sources. Since some German libraries send their data to Worldcat, they are somehow there. But as in most cases, the data quality in a large aggregation pool is not always great.

I could imagine to have different orders and choices for different ISBN prefixes, e.g.
 * for English books: LoC > WorldCat > Lulu
 * for German books: GBV > WorldCat
 * for Finnish books: Finish National Library > WorldCat
 * ...

This wold be my option 3.

**Comment by adam3smith** [comment]
I agree with zuphilip on the general issue--not sure about the best solution still.
Examples for data quality are, perhaps most importantly, correct distinctions between authors and editors for books, correct title/subtitle handling, automatic tags, and number of pages. That data simply isn't there in Worldcat, there's nothing we can do to improve it.

**Comment by adam3smith** [comment]
(the search parameter, in case you haven't looked for it yet, is pica.isb . The MARCXML will require some light tweaking either to the XML and/or to our import translator to work)

**Comment by zuphilip** [comment]
How did you create the test for the LoC search translator? Scaffold cannot deal with search translators AFAIK.

**Comment by adam3smith** [comment]
Manually I believe, though of course you can get the Zotero item object via Z.debug

**Comment by zuphilip** [comment]
Okay, I see. @aurimasv : Here is a specific exampel about the data quality: ISBN = 9783406644009 with GBV search translator (not yet tuned). You can compare it with OpenWorldcat which is the current search translator:
```
           {
             "itemType": "book"
             "creators": [
               {
                 "firstName": "Otto"
                 "lastName": "Palandt"
                 "creatorType": "editor"
               }
               {
                 "firstName": "Peter"
                 "lastName": "Bassenge"
                 "creatorType": "editor"
               }
             ]
             "notes": []
             "tags": [
               "Bürgerliches Gesetzbuch"
               "Civil law Germany"
               "Civil law Germany (West)"
               "Kommentar"
             ]
             "seeAlso": []
             "attachments": []
             "ISBN": "3406644007"
             "title": "Bürgerliches Gesetzbuch mit Nebengesetzen ; insbesondere mit Einführungsgesetz (Auszug) einschließlich Rom-I-, Rom-II- und Rom-III-Verordnungen sowie Haager Unterhaltsprotokoll und EU-Erbrechtsverordnung, Allgemeines Gleichbehandlungsgesetz (Auszug), Wohn- und Betreuungsvertragsgesetz, BGB-Informationspflichten-Verordnung, Unterlassungsklagengesetz, Produkthaftungsgesetz, Erbbaurechtsgesetz, Wohnungseigentumsgesetz, Versorgungsausgleichsgesetz, Lebenspartnerschaftsgesetz, Gewaltschutzgesetz"
             "edition": "73., neubearb. Aufl"
             "place": "München"
             "publisher": "Beck"
             "date": "2014"
             "numPages": "3220"
             "series": "Beck'sche Kurz-Kommentare"
             "seriesNumber": "7"
             "callNumber": "340"
           }
```

**Comment by aurimasv** [comment]
Like I said, let's get a search translator going and then we can decide the best way to integrate it.
