### ISSUE TITLE
Specify default license for translators

### ISSUE THREAD

**Issue by nemobis** [zotero/translators#851]
https://www.zotero.org/support/dev/translators#licensing implies that AGPLv3 is the preferred license and https://github.com/zotero/zotero/blob/4.0/COPYING is clear, but I see some translators don't specify any license and this repository doesn't have a COPYING file or similar. Can you add one?

I'm fine with any license, but I need to republish my contribution elsewhere and I want to be sure I state the license you actually chose.

**Comment by adam3smith** [comment]
(the reason that some translators are missing an explicit license is that they predate us adding AGPL to all translators. Since they're contributed to Zotero, which as a whole in under AGPL3, I think you can reasonably assume the same license, but IANAL).
