### ISSUE TITLE
Strip formatting from title for bibtex keys

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#853]
I.e. if we have \<i>Species Name\</i> title in Zotero, the bibtex key should still be author_species_year, not author_\<i>species\</i>_year
See:
https://github.com/zotero/translators/pull/813#issuecomment-74319644

**Comment by Cathryne** [comment]
Please note that this bug breaks (partially) automated workflows, [such as this](https://github.com/JensErat/scientific-markdown). Letting Zotero auto-export the library to a writing project's directory, where it is picked up by pandoc. I'm starting such a writing project soon and am willing to post a cash bounty for this issue through [BountySource](https://www.bountysource.com/).

Would that be acceptable to the Zotero community? I'm unfortunately not advanced enough in programming, to be able to patch this myself.

**Comment by adam3smith** [comment]
I assume there wouldn't be any objections. @dstillman ? It's a small fix, so no need for anything big.

**Comment by dstillman** [comment]
Doesn't matter to me, but note [my warnings about BountySource's model](https://forums.zotero.org/discussion/39168/can-we-the-users-start-a-zotero-features-fund-club/#Item_13). Don't know if that's still the situation, and this bug is probably small enough that someone will do it, but I'd be wary of using them for most things.

**Comment by adam3smith** [comment]
yeah, I can promise that either aurimas or me will do this quickly for (the bounty equivalent of) a drink, so no concerns about that issue here.

**Comment by rmzelle** [comment]
https://freedomsponsors.org/ seems better? (3% fee, direct payments)

**Comment by Cathryne** [comment]
OK, thanks for the feedback :-) I'll try to set up a [FreedomSponsors](https://freedomsponsors.org/) sponsorship.

**Comment by Cathryne** [comment]
Any news on this issue? Would a bounty in USD be better?

**Comment by adam3smith** [comment]
I never got the notification for this. Will go ahead and work on this over the weekend.

**Comment by Cathryne** [comment]
Merci! All the headache-causing `<i>` are gone from the exported bibtex keys now.

**Comment by adam3smith** [comment]
For those following the sponsorship part of this. There was a small glitch along the way, but support was quick and overall freedomsponsors.org worked nicely. For those who don't want to do bitcoins, paypal works, too.
