### ISSUE TITLE
Mangled authors in The Guardian.js

### ISSUE THREAD

**Issue by mvolz** [zotero/translators#866]
For example, http://www.theguardian.com/media/2015/feb/18/peter-oborne-daily-telegraph-newspaper-unprecedented

gives author "Arthur", "Bl" instead of "Archie","Bland"

fails test urls too: http://www.theguardian.com/world/2013/mar/05/hugo-chavez-dies-cuba

gives "Virginia Lopez in", "Caracas" instead of "Virginia","Lopez". 

A brief look at the source code looks like it's looking for creators in a class that no longer exists at all on the guardian( 'contributors-all' (line 47)) so I'm not sure where the mangled authors are being pulled from.

**Comment by owcz** [comment]
So a year later, this appear to be resolved. There isn't a translator for The Guardian so it pulls from Embedded Metadata. In the second example, EM accurately pulls "Jonathan Watts", who is in the metadata as the author, but "and Virginia Lopez in Caracas" lies outside the metadata. Unless we built special handling for the way The Guardian does multi-author pieces, I'd say we're best off just pulling the people they do tag as authors.

**Comment by adam3smith** [comment]
the guardian is a very commonly used source and we have a translator -- it's just broken. We should look at fixing this (though good to no that EM now works better).

**Comment by zuphilip** [comment]
No, there is a translator for The Guardian. But there are two small problems... I will try to fix them.

**Comment by zuphilip** [comment]
Ah, sorry I didn't update the website. I will create a PR for The Guardian.
