### ISSUE TITLE
ArXiv Translator Broken

### ISSUE THREAD

**Issue by FredericJacobs** [zotero/translators#883]
I'm getting this error in Chrome when trying to save Arxiv papers. 
![screen shot 2015-04-15 at 15 18 01](https://cloud.githubusercontent.com/assets/400296/7159483/bbb34f4a-e382-11e4-8313-a0ab4da055d7.png)

**Comment by aurimasv** [comment]
Please post error reports to the [Zotero forums](https://forums.zotero.org/) (you can post just the error message). Include URL you're importing from and OS, browser, and Zotero versions.

**Comment by simonster** [comment]
I think this is the bug I fixed in zotero/zotero@d881d4a6473fe9b5e72d9ecab48b8fde450f6149. I just need to push that fix.

**Comment by FredericJacobs** [comment]
Sweet, thanks @simonster.
