### ISSUE TITLE
HTML appearing in title from wikipedia translator

### ISSUE THREAD

**Issue by mvolz** [zotero/translators#892]
input: https://fr.wikipedia.org/wiki/Ninja_Turtles_(film)

output:

```
[
    [{
        "itemKey": "T75UK2BF",
        "itemVersion": 0,
        "itemType": "encyclopediaArticle",
        "creators": [],
        "tags": [],
        "title": "<i><span class=\"lang-en\" lang=\"en\"><span class=\"lang-en\" lang=\"en\">Ninja Turtles</span></span></i> (film)",
        "rights": "Creative Commons Attribution-ShareAlike License",
        "encyclopediaTitle": "Wikipédia",
        "url": "http://fr.wikipedia.org/w/index.php?title=Ninja_Turtles_(film)&oldid=115125238",
        "extra": "Page Version ID: 115125238",
        "language": "fr",
        "date": "2015-05-18T11:24:39Z",
        "abstractNote": "Ninja Turtles ou Les Tortues Ninja au Québec (Teenage Mutant Ninja Turtles) est un film d'action américain réalisé par Jonathan Liebesman et sorti en 2014.",
        "libraryCatalog": "Wikipedia",
        "accessDate": "CURRENT_TIMESTAMP"
    }]
]
```

**Comment by adam3smith** [comment]
The HTML gets swallowed by github here, so for reference, what we get is:
```<i><span class="lang-en" lang="en"><span class="lang-en" lang="en">Ninja Turtles</span></span></i> (film)```

Only question is: do we want to preserve the italics or not? I can see a strong case for doing so (and they work with Zotero citation styles).

**Comment by dstillman** [comment]
We really need a JS HTMLPurifier-like tool that doesn't involve passing data through TinyMCE. Maybe <a href="https://github.com/google/caja">Caja</a>, though I haven't looked at what it involves.

Once we have that, we can render titles as HTML safely and use a TinyMCE (or something simpler/faster) instance for editing.

In the meantime, I'm not crazy about leaving visible HTML in fields imported from a major site, though obviously throwing out data isn't great either...

**Comment by adam3smith** [comment]
Well, I figured we throw the Spans out. The question is whether we leave the italics in because they make bibliographic sense.

**Comment by dstillman** [comment]
Right, but the only safe way to clean HTML is with a tool designed (carefully) for that job. (The only reason it's not a major issue is that we would repurify any field content before displaying it anywhere.) And I'm saying that, from an aesthetic and usability standpoint, showing &lt;i&gt; in a title field imported from a major site isn't great. That happens to work in citeproc-js, but that's not our feature — from our perspective, we want to be rendering HTML and displaying it in a proper rich-text editor.

As a stopgap solution before we have proper HTML editing of titles, though, if there's a good, modular JS purifier, we could probably pretty trivially purify contents at display time and then render natively as HTML-in-XUL, and just display the raw version with &lt;i&gt;s in normal edit mode.

**Comment by dstillman** [comment]
(We also possibly cheat and create a hidden TinyMCE instance and just round-trip the contents through that before display, since we have that in our code already and it has purification logic.)

**Comment by dstillman** [comment]
(But yes, we should at least reduce this to just the italics in the meantime.)

**Comment by owcz** [comment]
This [appears to be resolved](https://citoid.wikimedia.org/api?format=mediawiki&search=https://en.wikipedia.org/wiki/African_art?jsoncallback=?)—I don't see junk HTML in the Title field anymore and last Title field update appears to be 149956a2b102cf141b73cb73ba17555828190a33 (several months before this ticket). Was it resolved @mvolz ?

**Comment by zuphilip** [comment]
(Closing this by @owcz's report; if a problem occurs again then open a new issue)
