### ISSUE TITLE
RIS export of "contributor" field for Book not handled

### ISSUE THREAD

**Issue by dbs** [zotero/translators#894]
While RIS.js includes an inline comment that the "contributor" field is not handled, later on it does handle it for the special cases of conferencePaper and film. This suggests that the RIS import/export should handle it in some way.

I'm working with a bibliography that includes a number of contributors for books that contain chapters co-authored by a number of different contributors, where "contributor" appears to be the most appropriate category for their contribution to the work.

For example, Roth in https://books.google.ca/books?id=bp3_Uv0Ul3MC&lpg=PA320&dq=1551930455&pg=PP8#v=onepage&q=roth&f=false appears as a credited contributor to a chapter in the book, where the primary authors are listed separately.

For now, I'm going to propose adding a custom A5 section for export purposes, as otherwise the data is silently dropped.

**Comment by adam3smith** [comment]
closing this as the corresponding PR is closed, too.
