### ISSUE TITLE
WorldCat Discovery Service.js

### ISSUE THREAD

**Issue by ericbradley** [zotero/translators#908]
The WorldCat Discovery translator is not pulling items that are a "Print book".  Items considered "eBook" or other formats pull just fine.  

Please see the following example: http://goshen.on.worldcat.org/search?sortKey=LIBRARY_PLUS_RELEVANCE&databaseList=&queryString=amish&changedFacet=format&scope=&format=all&format=Artchap&subformat=Artchap%3A%3Aartchap_artcl&subformat=Artchap%3A%3Aartchap_chptr&subformat=Artchap%3A%3Aartchap_digital&database=all&author=all&year=all&yearFrom=&yearTo=&language=all&topic=all

**Comment by adam3smith** [comment]
thanks -- it's the availability badge that's breaking this (the catalogs I tested this on didn't use that), should be a pretty easy fix over the weekend.

**Comment by zuphilip** [comment]
@adam3smith Can you also add the licence statement? This seems missing in the translator...

**Comment by adam3smith** [comment]
will do.

**Comment by zuphilip** [comment]
Thank you!

**Comment by ericbradley** [comment]
Thanks!
