### ISSUE TITLE
Nature translator successfully translating internal server error pages

### ISSUE THREAD

**Issue by mvolz** [zotero/translators#918]
http://www.nature.com/ijo/journal/v38/n1/full/ijo201369a.html

returns 

```
[[{"itemKey":"6HHC849F","itemVersion":0,"creators":[],"tags":[],"url":"http://www.nature.com/ijo/journal/v38/n1/full/ijo201369a.html","title":"Internal Server Error","accessDate":"CURRENT_TIMESTAMP","itemType":"webpage"}]]

```

(using translation-server)

**Comment by aurimasv** [comment]
This is probably more of an issue with how Zotero translation server works. It should fail immediately if the status code for the page that is returned is not one of the 2XX OK codes.

Nature and many other translators make assumptions that if the url matches something that is expected, the detectWeb passes. We only do further checks on page content where this could be confusing to the user. I don't think that's generally the case for 4XX or 5XX error codes.

**Comment by mvolz** [comment]
Agreed, closing.
