### ISSUE TITLE
Translator for Society for General Microbiology

### ISSUE THREAD

**Issue by rmzelle** [zotero/translators#919]
I currently only get the DOI translator with Zotero Standalone for e.g. http://jmm.sgmjournals.org/content/journal/jmm/10.1099/00222615-15-2-189, even though the page specifically has an export option for Zotero.

**Comment by rmzelle** [comment]
And is there a reason why I get the "folder" icon even though the DOI translator only finds a single item?

**Comment by dstillman** [comment]
We always show the folder icon for DOI now, since it's sometimes not actually the primary reference on the page and people would end up saving the wrong item.

**Comment by rmzelle** [comment]
So the folder icon is used for single items as an indicator that the Zotero Item Selector window will pop up? I still rather see a plain document icon if there is a single DOI. The selector could be tweaked a little as well for single items (e.g. the single item should be selected by default to save a click).

**Comment by dstillman** [comment]
Well, the folder icon is used because that's what's shown for a "multiple" return value for doWeb, which is what we now always return for DOI. If you're going to see the select-items dialog anyway, I'm not sure it makes sense to show the document icon. The folder preps you for what's about to happen, similar to an ellipsis in a menu option. Otherwise the dialog is a surprise.

**Comment by dstillman** [comment]
Selecting the one item probably makes sense, though.

**Comment by rmzelle** [comment]
Is the "page_white" ever used as the save icon (http://www.famfamfam.com/lab/icons/silk/previews/index_abc.png). I would much prefer that over the folder for single items, and an icon showing a blank page would also imply that Zotero doesn't know what's up.

**Comment by rmzelle** [comment]
Otherwise "folder_edit" and "page_white_edit" could also be used to suggest that the user has to make a selection.

**Comment by aurimasv** [comment]
Pre-selecting is ok, but we can't always know ahead of time how many
entries will appear in the list. It's possible that we find 4 DOIs on the
page in detectWeb, but we can only fetch 1 title (or none in the worst
case) from all of those DOIs, so only one item would be displayed anyway.
There's no way to get consistent behavior unless we always display the
folder icon.

**Comment by rmzelle** [comment]
Understood.
