### ISSUE TITLE
Support new(ish) google patents URLs & Layout

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#922]
Example: https://patents.google.com/patent/US7853881B1/en?q=networks
Requested here: https://forums.zotero.org/discussion/50751/new-url-layout-for-google-patents/#Item_0

**Comment by DmitriyC** [comment]
It appears Google is pushing hard for everyone to use the new service.  The page layout/formatting of the old engine (google.com/patents) is very basic now (see [example](https://www.google.com/patents/US7853881?dq=US7853881B1&hl=en&sa=X&ved=0ahUKEwiDuaGJou3JAhUJ_R4KHXufBtIQ6AEIHDAA)).  Perhaps it's just a temporary issue, but it's looked like that for at least a week (across different browsers/computers).  I should note that the translator still works, despite the poor browsing experience.

I've included a screenshot just in case the layout gets restored:

![patents-fs8](https://cloud.githubusercontent.com/assets/15699251/11934714/d9166eaa-a7d1-11e5-9950-06b3120fc367.png)

**Comment by carlodri** [comment]
looks like Google has renovated its [patent search](https://patents.google.com/patent/US7853881). Now the translator is almost useless, it only catches title and issue date. Would be great if it was updated in Zotero.

**Comment by DmitriyC** [comment]
That's what the original post was about -- you should use the old version at google.com/patents rather than the new patents.google.com until the translator is updated

**Comment by 121onto** [comment]
Is there some reason we can't update this?  I'd be happy to take a whack at it...

**Comment by adam3smith** [comment]
you can absolutely try. I haven't been able to get it to work. The way the page is loaded makes it exceedingly hard.

**Comment by 121onto** [comment]
@adam3smith before I try to throw myself into this... can you provide more details about your experience?

**Comment by adam3smith** [comment]
here's some code I had written
https://gist.github.com/adam3smith/e591a14f179d245f0b58
and here are some additional suggestions on the detect function
https://gist.github.com/aurimasv/eb6d403fa632876c052d

the biggest issue is to get monitorDOMChanges to look for changes in the right node to fire the detect function so that Zotero shows the URL-bar icon. In other words, getting this to work in Scaffold is fairly simple; it's the actual behavior in the browser that's tricky.

**Comment by adam3smith** [comment]
actually, here's the most recent version from me I think:
https://github.com/adam3smith/translators/commit/754878e94f866785cb8ec518b474c9681bf2ca17#commitcomment-12842005

**Comment by dclunie** [comment]
The old patent pages (https://www.google.com/patents/US7853881B1) now seem redirect to the new format pages (https://patents.google.com/patent/US7853881B1) and so Zotero fails miserably. e.g., does not capture inventors, patent number, etc.)

**Comment by zuphilip** [comment]
Pull request to fix this is here #1547.

**Comment by zuphilip** [comment]
Fixed with #1566.
