### ISSUE TITLE
encode < and > in DOI during Bib(La)TeX export

### ISSUE THREAD

**Issue by katrinleinweber** [zotero/translators#925]
possibly related to #853, but definitely to https://github.com/jgm/pandoc/issues/1640

There are [valid DOIs with `<`, `>` and other special characters](http://mr.crossref.org/iPage?doi=10.1130%2F0091-7613%282002%29030%3C0279%3AMNDFNM%3E2.0.CO%3B2). Could Zotero please exports them in [encoded form as recommended](http://www.doi.org/factsheets/DOIProxy.html#encoding) by the DOI Foundation?

Otherwise, broken URLs are generated downstream with for example pandoc-citeproc, which inserts `\textless{}` and `\textgreater{}`.

**Comment by aurimasv** [comment]
As URLs, http://doi.org/10.1002/I'm&lt;a>tag and http://doi.org/10.1002/I'm%3Ca%3Etag are equivalent (and the latter is preferred), but as DOIs 10.1002/I'm&lt;a>tag and 10.1002/I'm%3Ca%3Etag are not the same (DOIs themselves are never encoded). For Bib(La)TeX, Zotero exports DOIs, not URLs (in general). It's the responsibility of whatever is converting DOIs to URLs to ensure that DOIs are URL-encoded appropriately. (Zotero/citeproc-js may not be doing this correctly in some cases as well, but that's a different issue)

**Comment by adam3smith** [comment]
(Not related to #853 which is citekey specific). I agree with @aurimasv -- the Bib(La)TeX export is doing the right thing here. Encoding should occur (as the DOI foundation says) when using the DOI in URIs.
Closing this.

**Comment by katrinleinweber** [comment]
OK, thanks for explaining. Will report back to https://github.com/jgm/pandoc/issues/1640.
