### ISSUE TITLE
Library Catalog (Encore).js doesn't work outside of Zotero

### ISSUE THREAD

**Issue by Halibutt** [zotero/translators#933]
Recently the National Library of Poland (www.bn.org.pl) [switched to a new OPAC system Encore](http://katalogi.bn.org.pl/iii/encore/?lang=eng). The links work perfectly well in Zotero (FF, Chrome, all the same).  A book is correctly identified as a book, all the fields get imported correctly, it works like a charm. When I export the citation from Zotero using the native Wikipedia exporter, it looks perfectly healthy. 

BUT, it seems the translator does not work outside of the Zotero program, neither on test servers nor - more importantly for me - in Citoid, the new Wikipedia's citation system based on Zotero's translators. Links that were correctly scraped as books in Zotero either [return weird errors](http://katalogi.bn.org.pl/iii/encore/record/C__Rb1790808__SJemielniak__Ff%253Afacetmediatype%253Aa%253Aa%253AKsi%25C4%2585%25C5%25BCka%253A%253A__P1%252C25__Orightresult__U__X4?lang=pol&suite=cobalt) or are incorrectly identified as web pages, [this book for instance](http://katalogi.bn.org.pl/iii/encore/record/C__Rb3707725__SJemielniak__Orightresult__U__X4?lang=pol&suite=cobalt). 

I [filed a bug at Citoid's Phabricator](https://phabricator.wikimedia.org/T108772), but it seems the problem is with the translator and not with Citoid. Could anyone tell me how to make this beauty work?

**Comment by aurimasv** [comment]
In general, if the translator works in Zotero, then it's not a translator issue. We can't provide support for other scraping engines that use Zotero translators. I'm guessing it's an issue of what document is supplied to the translator (e.g. a document that has not completed loading).

>...does not work outside of the Zotero program, neither on test servers...

What test servers are you referring to? Zotero translation server? If so, the issue should be filed under the [appropriate repository](https://github.com/zotero/translation-server). Seems like that's what the Citoid issue thread is suggesting.
