### ISSUE TITLE
Support D-Lib Journal

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#939]
This journal has a focus in digital library research and the content is present at different mirrors, see http://www.dlib.org/about.html . There is currently only the doi translator working and it is only extracting one doi (the last one found on that page?), e.g. http://www.dlib.org/dlib/january15/mathiak/01mathiak.html . The metadata seem to be linked in the header: `01mathiak.xml`, `../01bib.meta.bib`, `../01ris.meta.ris`. The RIS and BibTeX files are for the whole issue and the XML looks like a easy to parse Dublin Core similar vocabulary. Probably, @kba may want to jump in here.

**Comment by adam3smith** [comment]
The DOI issue is this: https://github.com/zotero/zotero/issues/647

**Comment by adam3smith** [comment]
D-Lib stopped publishing in 2017, old articles work via DOI, no structured metadata availabl --> won't fix
