### ISSUE TITLE
American Meteorological Society journal import quick fix

### ISSUE THREAD

**Issue by gsever** [zotero/translators#945]
Hello,

I use Zotero Connector via Google Chrome to import references into Zotero standalone. When I import an article from AMETSOC (Atypoon Journals) (e.g., http://journals.ametsoc.org/doi/abs/10.1175/JAS-D-14-0363.1) it imports the word "Abstract" in the abstract text. Could you fix it to eliminate this word out? Thanks.

**Comment by aurimasv** [comment]
Should be fixed. Update your translators via Preferences -> Genreal -> Update Now, restart browser and try again.

Please report any further issues on [Zotero forums](https://forums.zotero.org/discussions/)

**Comment by pascaloettli** [comment]
The fix no longer works. Using the same URL, the Atypon translator is not activated and only embedded metadata are used to save to Zotero.

**Comment by gsever** [comment]
Works fine in Zotero v6.0.9
Could you update your version and try again?

**Comment by adam3smith** [comment]
Are you sure this works? AMS completely changed their site and I don't think uses Atypon at all anymore, so I don't see the translator even being used.

**Comment by gsever** [comment]
I tested with the original link: https://journals.ametsoc.org/view/journals/atsc/72/8/jas-d-14-0363.1.xml
using Zotero Connector extension (Version 5.0.97) on Google Chrome (Version 103.0.5060.114 (Official Build) (64-bit))
All fields (including abstract) are populated fine.
PS: The new AMS site is much slower and bloated compared to the old version. I would prefer an interface similar to EGU's publications (eg. https://acp.copernicus.org/articles/22/9129/2022/) which is very fast, user friendly and RSS works simply without registration.

**Comment by adam3smith** [comment]
Right, it works with the Embedded Metadata translator and includes the word "Abstract" in the abstract field, which this PR originally removed.
