### ISSUE TITLE
Atypon translator recently reports a lot of errors

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#958]
By studying the <a href="https://repo.zotero.org/errors">reported translator errors</a> one can see that Atypon translator seems to cause quite a lot of errors. The first type of errors seem to be connected to <a href="https://github.com/zotero/translators/blob/master/Atypon%20Journals.js#L192">this line</a> and may be easily solved. @dstillman Can you provide some details of these error reports? I guess especially one or several reproducible example(s) would be great.

**Comment by dstillman** [comment]
http://onlinelibrary.wiley.com/doi/10.2307/3586950/abstract 
 http://onlinelibrary.wiley.com/doi/10.1002/hec.2921/epdf
http://onlinelibrary.wiley.com/enhanced/doi/10.1111/puar.12217/
http://actachemscand.org/doi/10.3891/acta.chem.scand.52-0911

Also seeing it for advertisement URLs on ScienceDirect:

http://www.sciencedirect.com/science/advertisement/left/num/1257/mainCat/general/cat/general/acct/ddd49027ac058c4db14dac8cc0563abc/isn/09254005/doi/10.1016_j.snb.2005.04.042/page/article/artOAstatus/N
