### ISSUE TITLE
IACR translator broken?

### ISSUE THREAD

**Issue by FredericJacobs** [zotero/translators#965]
[Example link](http://eprint.iacr.org/2015/1018)

```
TypeError: Cannot read property '1' of null at eval at <anonymous> (chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/inject/translate_inject.js:50:9), <anonymous>:34
```

The problem appears to be the extraction of the filename

**Comment by adam3smith** [comment]
fixed in https://github.com/zotero/translators/commit/38a41f3ac2001657e240ad7642c3009006b809c7

**Comment by FredericJacobs** [comment]
Terrific, thanks :+1:
