### ISSUE TITLE
Die Zeit is broken

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#967]
reported
https://forums.zotero.org/discussion/54298/die-zeit-site-translator-no-longer-working/#Item_1
sample
http://www.zeit.de/mobilitaet/2015-10/deutsche-bahn-schienen-strecke-ueberlastung

Currently not detecting at all, likely requires a re-write.

**Comment by zuphilip** [comment]
Maybe also use schema.org here?

**Comment by zuphilip** [comment]
Okay, I have rewritten the translator and will test it a little more before creating a PR.
