### ISSUE TITLE
Atypon Journals date

### ISSUE THREAD

**Issue by owcz** [zotero/translators#980]
When I download from the Harv Ed R with the Atypon Journals (default) translator ([example](http://dx.doi.org/10.17763/haer.43.2.1v01524wlk183x66)), it pulls the date as "July 1, 1973". When I use the DOI translator, it correctly pulls "07/1973" (no day, just month+year). Is it helpful to report inconsistencies like this? Because I see many translators enter "1" as the date when it should really just be month+year.

**Comment by zuphilip** [comment]
The Atypon translator basically scrapes the RIS data from the publisher and there the day is in it, e.g. (click on "Export Citations" and choose RIS format):
```
TY  - JOUR
T1  - Essay Reviews
Y1  - 1973/07/01
PY  - 1973
DA  - 1973/07/01
N1  - doi: 10.17763/haer.43.2.1v01524wlk183x66
DO  - 10.17763/haer.43.2.1v01524wlk183x66
T2  - Harvard Educational Review
JF  - Harvard Educational Review
JO  - Harvard Educational Review
SP  - 258
EP  - 283
VL  - 43
IS  - 2
PB  - Harvard Education Publishing Group
SN  - 0017-8055
M3  - doi: 10.17763/haer.43.2.1v01524wlk183x66
UR  - http://dx.doi.org/10.17763/haer.43.2.1v01524wlk183x66
Y2  - 2015/12/20
ER  - 
```
Do you know for certain that the day here is wrong? You could ask the publisher/editor to correct the metadata. However, we could change the behaviour of the translator, if you have reliable information that the day is always wrong for all articles handled with the Aytpon translator.

**Comment by owcz** [comment]
The cover of the journal doesn't indicate more than the month+year and the BibTex and plain text exports don't include either the month or the day. I emailed the publisher anyway. I can check other examples of Atypon if you know which journals use it. For instance, I just pulled [a random MIT Press Journal](http://www.mitpressjournals.org/doi/abs/10.1162/tneq.2007.80.1.69), which has an online date of March 2007 (though I don't think anyone would want more than March 2007—the issue name), but imports with the translator as "March 1, 2007".

**Comment by owcz** [comment]
Response from the publisher's feedback form (welcome to the feedback loop):

>I'm sorry that the citation information we are posting for this journal does not follow the format of some other journals. Unfortunately, that is not something that we can change but it determined by the publisher for the journal. Perhaps your citation manager can be set to select just the month and year part of the date.

>Best regards,
Anne

>Allen Press Electronic Services Support
pinnaclesupport@allenpress.com

**Comment by adam3smith** [comment]
I generally don't mind fixing incorrect data in translators, even if it should be the publisher's job (and yes, reporting it is worthwhile) -- the problem here is that Atypon is extremely widely used as a publication system and I'm not comfortable applying this across the board (e.g. we almost certainly want to keep the day for online-first publications and possibly other cases where it's correct.). 
I suppose we could trigger this by URL?
The other thing is that on the Zotero side our citation styles ignore days of publication for journal articles in most cases, so this makes very little difference. Is that not the case with Wikipedia citations?

**Comment by owcz** [comment]
Do you have a contact at Atypon with whom we could escalate the question? This is the Wikipedia quick export for the above example:
```
{{Cite journal| doi = 10.17763/haer.43.2.1v01524wlk183x66| issn = 0017-8055| volume = 43| issue = 2| pages = 258–283| title = Essay Reviews| journal = Harvard Educational Review| accessdate = 2015-12-23| date = 1973-07-01| url = http://hepgjournals.org/doi/10.17763/haer.43.2.1v01524wlk183x66}}
```
So, yes, the export uses the full date (also, by the way, Wikipedia chokes on ymd dates without days specified, e.g., 1973-07 throws an error on WP and needs to be reformatted as mmmm yyyy)

**Comment by adam3smith** [comment]
This is still an issue 7 years later. The above example moved to Silverchair (where the data are even worse...) but all of our tests in Atypon have the publication date as the first of the months, e.g. https://pubs.rsna.org/doi/full/10.1148/rg.337125073

Given that this seems to be Atypon behavior across different sites, I do think it's worth considering testing for the 01 day there and just losing it and going to YYYY-MM 
@AbeJellinek thoughts?

**Comment by AbeJellinek** [comment]
Yeah, I don't see a better option. I can update the translator.
