### ISSUE TITLE
JSTOR book review multi

### ISSUE THREAD

**Issue by owcz** [zotero/translators#987]
1. Search for book reviews (type: reviews) on JSTOR ([sample](www.jstor.org/action/doAdvancedSearch?f3=all&c5=AND&f2=all&q4=&f0=all&q5=&acc=off&pt=&c4=AND&f6=all&c3=AND&q1=kelley&la=&group=none&c1=AND&f4=all&isbn=&c2=AND&sd=&f5=all&q3=&q2=&re=on&q6=&c6=AND&q0="yale%3A+a+history"&ed=&f1=all))
 2. Any review that doesn't have the reviewed book(s) in unlinked italics is not included in the multi
  - So "Yale: a history" (author: Kelley) will show nine results, but only two in the multi (default)
  - and "Reading Rousseau in the nuclear age" won't show a multi download at all

**Comment by adam3smith** [comment]
fixed in https://github.com/zotero/translators/commit/8389d0f5efb27ff2483a951bcf334365e57879f3, thanks!

**Comment by owcz** [comment]
I think this might have opened back up again:

![screenshot 2016-04-28 22 18 23](https://cloud.githubusercontent.com/assets/778011/14907468/2407521c-0d8f-11e6-88a0-83f9a8b191aa.png)

(Items in JSTOR search with bolded "Review: NAME" headers not showing in the multi.)
