### ISSUE TITLE
Clean translators from some deprecated code

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#990]
The functions `Zotero.done()` and `Zotero.wait()` are <a href="https://www.zotero.org/support/dev/client_coding/changes_in_zotero_3.0#zoterodone_and_zoterowait_are_deprecated">deprecated</a> since more than 4 years. However, there are still a lot of translators which are having such deprecated code inside them:
 * <a href="https://github.com/zotero/translators/search?utf8=%E2%9C%93&q=%22Zotero.done%28%29%22">137 results</a> for "Zotero.done()"
 * <a href="https://github.com/zotero/translators/search?utf8=%E2%9C%93&q=%22Zotero.wait%28%29%22&type=Code">114 results</a> for "Zotero.wait()"

What is the current effect of these lines? Could we just delete these lines or do we have to be more careful?

Some results found are also resulting from the translator framework. Are the lines still in the translator framework at the moment?

**Comment by aurimasv** [comment]
I wouldn't worry specifically about those function calls. `Zotero.wait()` literally does nothing. `Zotero.done()` usually does nothing, but it is still useful sometimes (asynchronous item type return for detectWeb). Removing these calls wouldn't really do much good, but they do indicate that the translators that contain those lines have not been properly updated in a long time.

While I think it would be great to go through all translators and make sure they are all clean and up to date, that is a huge huge huge undertaking and it is not currently worth our efforts. What needs to happen first is support for automated tests for all translators (import, export, search, and web; though this is not as critical) and for most websites (especially those that we cannot simply link to, i.e. require authentication or POST requests). Once we have that in place, we can think about cleaning up the translator database and maintaining it properly.

**Comment by zuphilip** [comment]
Okay, I will close this issue. This sounds like the other steps before cleaning up may take quite some time. Let me know if I can help somewhere.
